### ISSUE TITLE
GroupBy with complex metrics fails if there is a post-aggregator with the same name

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#1045]
See #1044 for unit tests catching this bug.

**Comment by xvrl** [comment]
@metacret I believe this is the issue you are encountering with approximate histograms. The work-around is to give the post-aggregator a different name than the aggregator.

**Comment by metacret** [comment]
Thanks  a lot. I will ask internal users to change post-aggregator name.

**Comment by xvrl** [comment]
@metacret You are welcome. I believe this bug is not new, and has been around for a very long time.
