### ISSUE TITLE
request/time not accurate measure of time spent processing request

### ISSUE THREAD

**Issue by cheddar** [druid-io/druid#1102]
Back in June, commit

https://github.com/druid-io/druid/commit/d2c729adec3b9b82705646c6f006ad55b8860a5e

Changed the semantics of `request/time`, prior to that commit, `request/time` meant the amount of time it took to process the entire request on the node.  After that commit `request/time` now means the amount of time it takes to process the first result to be sent back.

This means that for queries that take advantage of streaming, the metrics is measuring the amount of time to ***start*** streaming results back but not the amount of time taken actually streaming those results back.

**Comment by drcrallen** [comment]
the differences in `query/time`, `query/wait` and `request/time` are not immediately clear. There has been internal rumblings about "how can we make metrics better / more reasonable" but it hasn't gotten much traction yet.

**Comment by cheddar** [comment]
@drcrallen that is definitely true with the current semantics.  `request/time` is rather useless as a performance measurement tool right now.

The old semantics was

`request/time` - Amount of time it took to process the total request
`query/time` - Amount of time it took to process the query, where the query is an internal implementation detail (on broker it is the query sent back to historical, on historical, the query run against the segment)
`query/wait` - Amount of time query was waiting to be processed.  This used to be only meaningful on historicals because the broker implementation wasn't actually measuring things properly.  I'm not sure what the current state is.

**Comment by xvrl** [comment]
the request/time change was unintended, it should be possible to move the metrics emitting back into the streaming output response object. In practice though it may only matter for uncached timeseries queries, since in other case the query is almost fully materialized before getting returned.
