### ISSUE TITLE
Casing bug for dataSource in realtime

### ISSUE THREAD

**Issue by cheddar** [druid-io/druid#111]
Nebrera on the IRC channel today reported that he was ingesting data but couldn't query it.  His real-time schema had some capital letters in the dataSource and his query matched it but he couldn't get results.  I had him adjust it to be all lowercase and it started working.  So, we've got a casing bug in the real-time nodes right now.

**Comment by xvrl** [comment]
Closing since Druid 0.7.x is now case-sensitive. Please re-open if this is still a critical issue for 0.6.x
