### ISSUE TITLE
Handling nulls and empty strings is still inconsistent

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#1120]
The easiest way to verify is this:

On line 47 of druid.sample.json.bottom, add the following
"quality":""

Unit tests will fail in testDifferentMetrics as the test expects 1 unique for quality and this change generates 2 unique quality values.

change that line to:
"quality":null

Unit tests will now pass.

Sad face.

**Comment by xvrl** [comment]
#1262 should fix this

**Comment by nishantmonu51** [comment]
Its already fixed. made the change to test this in UT.

**Comment by xvrl** [comment]
Likely fixed in #1262, verified by #1456
