### ISSUE TITLE
Allow setting of port via environment variable

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#1124]
This is a proposal to allow setting of the service port via the `PORT` environment variable.

This can be overridden by the command line, and if both command line and environment variable are absent, then the defaults will be used.

**Comment by gianm** [comment]
I think the intent of this is to support running Druid from Marathon. I think that would be best done with a wrapper script that translates the Marathon environment variables to jvm args.

**Comment by potto007** [comment]
FWIW - internal projects on which I'm involved we've began using configuration handlers that use config files but individual configs are overridden by environment variables (ie: com.typesafe.config). Following this pattern makes moving towards Docker easier and avoids yet another script / file that can be affected by divergence.

**Comment by xvrl** [comment]
Agree that this would be better addressed by wrapper scripts passing JVM args rather than adding more ways of configuring things.
