### ISSUE TITLE
Cardinality aggregator not available in postAggregator

### ISSUE THREAD

**Issue by mrijke** [druid-io/druid#1127]
It would be nice if a Cardinality aggregator that has been specified in a query would also be available to a postAggregator.
I tried it (with 0.6.171) using a simple fieldAccess post-aggregator, but it returns a base-64 encoded string.

**Comment by drcrallen** [comment]
@mrijke : have you tried something like the following?
[Hyper Unique Post Aggregations](http://druid.io/docs/latest/Post-aggregations.html#hyperunique-cardinality-post-aggregator)

**Comment by xvrl** [comment]
@mrijke to access the estimated cardinality as part of a post-aggregation instead of the raw hyperUnique sketch of the cardinality aggregator you have to use the [`hyperUniqueCardinality` post-aggregator](http://druid.io/docs/latest/Post-aggregations.html#hyperunique-cardinality-post-aggregator) to convert the sketch to a floating point estimate. For example:

 ```json
"aggregations" : [
  {"type" : "count", "name" : "rows"},
  {"type" : "cardinality", "name" : "dim_card", "fieldName" : "mydimension"}
],
"postAggregations" : [{
  "type"   : "arithmetic",
  "name"   : "average_rows_per_unique_value",
  "fn"     : "/",
  "fields" : [
    { "type" : "fieldAccess", "name" : "rows", "fieldName" : "rows" },
    { "type" : "hyperUniqueCardinality", "fieldName" : "dim_card" }
  ]
}]
```

**Comment by mrijke** [comment]
From my initial discussion with FJ I was under the assumption that the hyperUniqueCardinality was only available on fields that were aggregated with the HyperUnique aggregator at ingestion time.
I adapted your example and I can make it work for "arithmetic" postaggregators. Is it also possible to use the hyperUniqueCardinality in a Javascript postaggregator?
Thanks for clearing up my confusion!
