### ISSUE TITLE
historical nodes do not replicate data

### ISSUE THREAD

**Issue by pdeva** [druid-io/druid#1209]
I have rules of the following form:
http://screencast.com/t/XNDJZuxJg0Yv

This implies there should be 2 replicas of each segment in my historicals.

I had 6 historical nodes.
I took down 1 of them.

Now this should not have affected any queries since I am assuming the other nodes would have a replica of the data. However, I see broker basically failing to respond to any query that goes to historicals. 

I do see a ton of network activity in the other historicals, so they seem indeed busy loading data.

However, this violates the high availibilty requirement of druid. Bringing down 1 historical shouldnt have impacted querying.

update:  

the coordinator loadqueue shows that everything is loaded, however that doesnt seem to be the reality.

Here is a screenshot showing network activity:
http://screencast.com/t/0cSgYPfW

the spike around 6:40 is when the other historical was killed.

**Comment by pdeva** [comment]
it seems like this is related to a different issue. closing for now.

**Comment by mentholi** [comment]
@pdeva Do you still remember what was your issue with this? I have exactly same problem and cannot figure it out.
