### ISSUE TITLE
BatchServerInventoryView using bad keys for caching of values

### ISSUE THREAD

**Issue by cheddar** [druid-io/druid#1217]
The BatchServerInventoryView code is only using the name of the znode as its key for the local cache of the contents of that znode.  A cluster in the community had two historical nodes that each created a znode at the exact same time.  Those two nodes were fighting with each other for the "correct" contents of that znode.  BatchServerInventoryView should instead be including the DruidServer information in the keys that it is using.

**Comment by drcrallen** [comment]
@cheddar If you are tackling this can you please put yourself on the Assignee?
