### ISSUE TITLE
Specifying plumber in realtimeIndexTask config breaks while parsing on overlord with Guice Errors 

### ISSUE THREAD

**Issue by nishantmonu51** [druid-io/druid#1228]
based on discussion in thread - 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/druid-development/NiRB141SM4Q/U6SDu1f8OykJ

Adding plumber to ioconfig in realtimeIndexTask fails on overlord while parsing task json due to guice bindings.  
"plumber": {
        "type": "realtime"
      }

Exception stack trace - 

1) Must override the binding for NodeTypeConfig if you want a DruidServerMetadata. at io.druid.guice.StorageNodeModule.getMetadata(StorageNodeModule.java:62) at io.druid.guice.StorageNodeModule.getMetadata(StorageNodeModule.java:62) while locating io.druid.server.coordination.DruidServerMetadata for parameter 0 at io.druid.server.coordination.SingleDataSegmentAnnouncer.<init>(SingleDataSegmentAnnouncer.java:46) at io.druid.guice.AnnouncerModule.configure(AnnouncerModule.java:43) while locating io.druid.server.coordination.SingleDataSegmentAnnouncer at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:112) at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:112) while locating com.google.common.base.Supplier<io.druid.server.coordination.DataSegmentAnnouncerProvider> at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:113) while locating io.druid.server.coordination.DataSegmentAnnouncerProvider while locating io.druid.server.coordination.DataSegmentAnnouncer

Its broken in both 0.6 and 0.7. 

removing the plumber from task config works fine.
If this is expected, we need to document this.

**Comment by gianm** [comment]
The plumber is supposed to be created at runtime rather than provided by the user, because the index task needs a special plumber to work properly. It actually used to be that you couldn't specify a plumber at all, but that got changed in the config refactoring. Now, you can, but it should be null so the task can create its own.

**Comment by nishantmonu51** [comment]
fixed by #1244
