### ISSUE TITLE
could druid support aggregator the conditional dims?

### ISSUE THREAD

**Issue by sundy-li** [druid-io/druid#1234]
Consider the data struct like :

```
 dim1 dim2  metric1 metric2
1        1        2        3
2        0        3        4
```

just like mysql query`select  sum(if(dim2 = 1, 1, 0)) as agg1, sum(metric1)  from table group by dim....`

**Comment by nishantmonu51** [comment]
druid has support for native FilteredAggregator where you can specify a filter (using and,or and selector) and your aggregator. for more details refer to - http://druid.io/docs/latest/Aggregations.html

**Comment by sundy-li** [comment]
well, but my need is to caculate the number according to the dims, not like make new Aggregator  with other Aggregators.

**Comment by nishantmonu51** [comment]
If you want to do a count of the number of dim2 rows matching values 1 and 0  you can do so e.g. 
{
  "type" : "filtered",
  "filter" : {
    "type" : "or", 
 "filters" : [ {
    "type" : "selector",
    "dimension" : dim2,
    "value" : 1}, 
    {
    "type" : "selector",
    "dimension" : dim2,
    "value" : 0
    }]
  },
  "aggregator" : { "type" : "count", "name" : "filteredRowCount" }
}

For more complex use cases, you can also have a look at writing JavaScript aggregator with any custom logic you need.

**Comment by xvrl** [comment]
I think this has been answered, so I am going to close this. Please reopen if not.
