### ISSUE TITLE
`max` aggregator on `__time` column returns double

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#1237]
Doing a `max` aggregator on the `__time` column returns a double value, not a long value.

A simple test of this is something like:

```json
{
  "queryType"  : "timeseries",
  "dataSource" : "tpch_year",
  "granularity": "all",
  "intervals": [ "1970-01-01T00:00:00.000/2019-01-03T00:00:00.000" ],
  "aggregations": [
    { "type": "max", "name": "lastItem", "fieldName": "__time" }
  ]
}
```

results in
```json
[ {
  "timestamp" : "1992-01-02T00:00:00.000Z",
  "result" : {
    "lastItem" : 9.12470376448E11
  }
} ]
```

An example use case for this would be to get a "last seen" timestamp when the query is either filtered or groupBy.

**Comment by xvrl** [comment]
This is the current expected behavior, each aggregator has an inherent type, so we would have to create `longMax` and `longMin` to allow returning long values.

**Comment by fjy** [comment]
I am closing this as I believe it is the expected behavior and long max/min should be used.
