### ISSUE TITLE
Add count parameter to history endpoints

### ISSUE THREAD

**Issue by tarekrached** [druid-io/druid#1266]
It would be super useful if we had a count parameter for the history endpoints, so in addition to getting the history over a specified interval, we could also ask for the last n changes.

AFAIK, the endpoints are:
- `/druid/coordinator/v1/rules/{dataSourceName}/history?count=<n>`
- `/druid/coordinator/v1/config/history?count=<n>`
- `/druid/indexer/v1/worker/history?count=<n>`

**Comment by tarekrached** [comment]
also would be great to have an endpoint somewhere that we can see all recent rule changes across all datasources - not sure where that would live, though...

**Comment by noddi** [comment]
I think, we can mark this issue as resolved.

**Comment by drcrallen** [comment]
@noddi thanks!
