### ISSUE TITLE
proxy /druid/indexer requests on the coordinator to the indexing overlord

### ISSUE THREAD

**Issue by tarekrached** [druid-io/druid#1290]
Please add a /druid/indexer/* http endpoint to the coordinator which would proxy those requests to the indexing-service overlord.  I think it should support arbitrary HTTP verbs, although AFAIK, only GET and POST are used by the overlord right now.

**Comment by himanshug** [comment]
curious as to what usecase needs this?

**Comment by nishantmonu51** [comment]
Proposal for the change is discussed here - 
https://groups.google.com/d/msgid/druid-development/873eac97-c605-4e4e-8568-78c302f5468f%40googlegroups.com

**Comment by fjy** [comment]
@himanshug I believe this is to expand the features of the coordinator console and enables the coordinator console to only talk to to the coordinator to get everything it needs.

**Comment by himanshug** [comment]
thanks for the info and the link. I guess, we should always put the link to proposal discussion in the issue/PR description/comments so that context is clear for anyone reading the PR or issue.

**Comment by tarekrached** [comment]
Thanks for answering, Nishant and Fangjin.

Himadri - as Fangjin said, this is in order to allow the coordinator console to access cluster endpoints (specifically the indexing overlord in this case) that are not served by the coordinator.  This will enable the coordinator console to provide a more complete view of the cluster.  Let me know if you have any questions.

**Comment by fjy** [comment]
@tarekrached @himanshug != Himadri :). Himanshu is a Druid developer at another organization.

**Comment by tarekrached** [comment]
doh!  my apologies to both @himanshug and our own Himadri - apparently I can only process the first 4 letters of a name :/

**Comment by himanshug** [comment]
@tarekrached no probs, happens :)
