### ISSUE TITLE
Realtime nodes are blocking ingestion

### ISSUE THREAD

**Issue by T0aD** [druid-io/druid#1321]
Hi,

An issue with realtime nodes (standalone, launched manually, using kafka ingestion) is triggered when a node is restarted.

Basically what the node does is 
1/ assign itself kafka partitions ownership (and so block any other nodes actually READING from kafka)
2/ see there are merging to be done (segments not handoff still on disk)
3/ decide to - of course - merge them first
4/ well I don't know about you guys, but some on our dimensions take ages to be indexed / merged (for instance io.druid.segment.IndexMerger - Completed dimension[tokens] in 97,724 millis. )
5/ once all is finished, it will actually start reading from kafka brokers

My question is:
- why isnt proper ingestion a priority of Druid ? Seems to me thats the one thing we all want: realtime ingestion, reading from kafka should be the main focus (in case all realtime nodes are restarted for instance, it will hang forever, creating a terrible downtime).
- why the ingestion is designed to block other consumers ?

I tried to be smart after some segments were not handed off from our boxes so in order to clean them (we had performance issues since all historical queries were also querying realtime nodes because of those segments not handed off to deep storage), so I stopped a realtime node at a time, cleaned them up, started them up again and wait for it to reingest again before stopping the next one.

The problem is it didnt work that way at all: it started to own kafka partitions, forbidding any other consumer from the same group to read those and started his merging job:

io.druid.segment.IndexMerger - Starting dimension[trigrams] with cardinality[731,855]
io.druid.segment.IndexMerger - Completed dimension[trigrams] in 606,939 millis.

So as you can see, 600 seconds is 10 minutes so whatever druid will read after that will be thrownAway (the window time being PT10M) and will force us to reindex this hour (still meaning the actual realtime data is incorrect).

Please could you check this issue and try to fix it ? Thanks !

**Comment by fjy** [comment]
Hi @T0aD,

I don't believe this is a software problem as much as it is a setup problem. Druid's realtime ingestion is designed to block ingestion is there are too many pending persists. This is to prevent nodes from running out of memory and crashing entirely. The times seen for creating some of your dimensions are absolutely insane and completely not normal, and points to improper configuration or improper setup.

I'm going to repeat what I've mentioned a few times already. Given the tidbits of information I have seen about your cluster, I strongly believe that your cluster is misconfigured. We'd be very happy to help straighten things out, but we need more information about how you guys are setting things up.

**Comment by T0aD** [comment]
Hi Fangjin,

First of all, thanks for the answer, I realize indeed we might have issues in our usage of Druid but still, aren't realtime nodes supposed to ingest data in realtime and answer clients' queries ? Because here this design is not respected and there is absolutely no logic behind throttling ingestion to the point of DISABLING ingestion completely on a group of kafka partitions.

I still feel there is a serious design problem in the way Druid ingests its data through Kafka:
if the ingestion is being throttled to save the node from crashing, why even claim ownership over partitions other nodes could trivially read from ? It only blocks other consumers from reading data they could ingest, triggering latency issues and ultimately forcing us to reindex data at a later point (meaning realtime data becomes incorrect, incomplete).

Thanks for addressing this issue, I'm sure you can see this is not a behaviour that can be acceptable.

And if you still think this is a correct behavior and you feel throttling ingestion is the way to go, then I suggest to throttle the whole process, not just the reading part but also the Kafka rebalancing part, that way, nodes not restarted have a chance to continue ingesting data while late nodes can catch up with their handing off process.

Thanks!

**Comment by gianm** [comment]
@T0aD, I think it makes sense to delay claiming partitions until the realtime node is finished starting up and ready to ingest. The linked PR makes that change.

**Comment by T0aD** [comment]
Waow ! Great news, can't wait to test it, thanks a bunch @gianm !
