### ISSUE TITLE
Test failing after #1323 got merged, and reverted by #1324 needs to be fixed

### ISSUE THREAD

**Issue by xvrl** [druid-io/druid#1325]
#1324 removed a test failing due to #1323, but it's unclear if that test is bad or if there's an actual bug.

**Comment by drcrallen** [comment]
Test was against the 05-06 conversion, which was eliminated in the "lost commit" in favor of the 06-07 conversion. Tests probably need to be rewritten for 06-07

**Comment by drcrallen** [comment]
@himanshug had created tests between the lost commit and the re-instatement of the lost commit, which were against the old 0.6.x branch version of the class.

**Comment by himanshug** [comment]
yes, i think it was testing 5to6 property conversions and not valid with changed code which does 6to7 conversion.
With #1323 we've sort-of made implicit decision that "convertProps" wouldn't support 5to6 conversions.
If we still want to support both 5to6 and 6to7 configuration updates then we can probably have classes

ConvertProperties5To6.java (command "convertProps5to6")
ConvertProperties6To7.java (command "convertProps6to7")
and this model can be extended to further version updates.

**Comment by xvrl** [comment]
It's unlikely that someone would be able to upgrade straight from 0.5.x to 0.7.x so we decided to remove the 0.5 -> 0.6 convertprops in 0.7, and only leave them in the 0.6 branch.

@himanshug would you like to contribute tests for the 0.6 -> 0.7 conversion instead?

**Comment by drcrallen** [comment]
The upgrade convention was one that was decided upon among a relatively small group of people: That any major version must be able to upgrade properties from the prior major version, but is not required to support upgrades from older versions. If that needs to change it would be very worth bringing up to a wider discussion.

**Comment by himanshug** [comment]
@xvrl sure, I will send updated UTs .
