### ISSUE TITLE
Middlemanagers should reinstate task states on zookeepers disconnect

### ISSUE THREAD

**Issue by nishantmonu51** [druid-io/druid#1328]
At present middle managers do not reinstate task states on zk disconnects, 
this leads to overlord state getting out of sync from the workers which leads overlord to over assign tasks to workers and leads to unnecessary task failure on zk reconnects.

**Comment by gianm** [comment]
This is a dupe of #709.

**Comment by nishantmonu51** [comment]
closing as it is dupe of #709
