### ISSUE TITLE
As a Druid user I would like to be able to distinguish between hyperLogLog and aproxHistogram

### ISSUE THREAD

**Issue by vogievetsky** [druid-io/druid#1365]
When running a segmentMetadata query I get the following results back:

```
      "revenue_hist": {
        "type": "STRING",
        "size": -1,
        "cardinality": null,
        "errorMessage": "error:noSizeFn"
      },
      ...
      "unique_visitors": {
        "type": "STRING",
        "size": -1,
        "cardinality": null,
        "errorMessage": "error:noSizeFn"
      },
```

One of those columns is a hyperLogLog and the other an aproxHistogram (guess which is which).
By checking the `errorMessage == "error:noSizeFn"` (which seems to be unique to hyperLogLog and aproxHistogram columns) I can determine that both of those columns are ether hyperLogLog or aproxHistogram. I would like there to be a way to actually tell them apart without making another query.

In general it would be great to be able to see the aggregate function that rolled up the metrics.

**Comment by theduderog** [comment]
+1

**Comment by arrawatia** [comment]
+1
