### ISSUE TITLE
Main page "load data" link to 404 page

### ISSUE THREAD

**Issue by zhouqianli** [druid-io/druid#1377]
The [Load Data](http://druid.io/docs/0.7.1.1/Tutorial:-Loading-Your-Data-Part-1.html) link to empty page on the [Main page](http://druid.io/).

**Comment by fjy** [comment]
Fixed via https://github.com/druid-io/druid-io.github.io/commit/ced812a11b61d354b26df9db66aa7b5487a1f4a4
