### ISSUE TITLE
Data from join not pushed to the outer groupby

### ISSUE THREAD

**Issue by Hikamare** [druid-io/druid#14088]
### Affected Version

The Druid version where the problem was encountered: 25.0.0

### Description

When doing a series of group by queries I have noticed that having more than one nested group by query results in data from join to be "lost".

Given the following query:
```json
{
    "queryType": "groupBy",
    "dimensions": ["related_object_id", "r.category_id"],
    "dataSource":
    {
        "type": "query",
        "query":
        {
            "queryType": "groupBy",
            "dimensions": ["related_object_id","r.category_id"],
            "intervals": "2020-03-20/2020-03-21",
            "dataSource":
            {
                "type": "join",
                "left":
                {
                    "type": "inline",
                    "name": "DRUID_INLINE_DATASOURCE",
                    "columnNames":
                    [
                        "__time",
                        "related_object_id"
                    ],
                    "rows":
                    [
                        [1584662400000,"3229"],
                        [1584662400000,"4510"]
                    ]
                },
                "right":
                {
                    "type": "inline",
                    "columnNames":
                    ["related_object_id","category_id"],
                    "rows":
                    [
                        ["3229", 2985],
                        ["4510", 2985]
                    ]
                },
                "rightPrefix": "r.",
                "condition": "related_object_id == \"r.related_object_id\"",
                "joinType": "LEFT"
            },
            "granularity": "day",
            "filter":
            {
                "type": "in",
                "dimension": "related_object_id",
                "values":
                [
                    "3229",
                    "4510"
                ]
            }
        }
    },
    "intervals": "2020-03-20/2020-03-21",
    "granularity": "all",
}
```
For the sake of explaining the problem all {post}aggregations were removed from the query (nothing changes if the aggs are added/removed)

**Expected results** (works with Druid 24.0.0):
| related_object_id | r.category_id |
| ------------------------|-----------------|
| 3229 | 2985 |
| 4510 | 2985 |

**Results** per Druid 25.0.0:
| related_object_id | r.category_id |
| ------------------------|-----------------|
| 3229 | _null_ |
| 4510 | _null_ |

**Comment by benkrug** [comment]
Also verified this, comparing older version (works) and 25.0 or trunk don't work.  To illustrate fully, run the above query, and also run it without lines 1-7 and 57-60 (to remove the outer groupby).  related_object_id and r.category_id are both returned for the inner group by query alone, but adding the outer groupBy drops r.category_id.

**Comment by Hikamare** [comment]
Confirmed that it's working with rc1 :) Thanks guys!
