### ISSUE TITLE
HadoopDruidDetermineConfigurationJob checks input files without first setting Job properties from spec file

### ISSUE THREAD

**Issue by michaelschiff** [druid-io/druid#1463]
HadoopDruidDetermineConfigurationJob.run() ensures the job input paths before setting any of the job properties specified in the indexing spec. This is problematic in the case where input files reside in S3 in a location that requires different access keys from those configured in core-site.xml.

Currently the work-around is to modify the keys in core-site.xml directly, but this is not ideal.  If job properties were set before ensuring paths then the indexing spec would be fully self-contained, all job properties can be set there, and no modifications to the hadoop *.xml files would be necessary.

**Comment by michaelschiff** [comment]
I have started work on this and will submit a PR with tests.

**Comment by michaelschiff** [comment]
Initial work:
2743da386a3f3d4649d0c47306f7f990ec7a76f3

The scope of changes is pretty minimal.  Before config.addInputPaths is called with the job, the configs job properties are inserted into the job.  The job will have been set with default configs, and overridden with any system properties prefixed by "hadoop." (which is an undocumented feature), so adding the configs from the job spec seems pretty safe.

Though these config values can be set from system properties, in the interest of not repeating oneself, it seems nice to only have to configure them in the job spec (where they will apply everywhere)

**Comment by michaelschiff** [comment]
A similar issue is present in IndexGeneratorJob.run()

Currently this method will attempt to add input paths to the config before adding properties from the config to the job.  This will fail in situations in which adding paths to the config depends on the properties in the config being set.  Reversing the order of these two lines should suffice.

**Comment by michaelschiff** [comment]
0adc51c07af4b411ab3006e3209e7b8769a970f5
Test for JobHelper.ensurePaths

**Comment by michaelschiff** [comment]
https://github.com/druid-io/druid/pull/1484

**Comment by drcrallen** [comment]
@michaelschiff Is this resolved?

**Comment by michaelschiff** [comment]
@drcrallen yep, merged in my pull-request
