### ISSUE TITLE
Dimension introspection does not work on realtime segments

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#1474]
Sink.getSegment always returns an empty list for the dimensions. This is troublesome for people that want to run dimension introspection queries (like the broker's dimensions endpoint) on new datasources that don't have historical segments yet.

**Comment by gianm** [comment]
I think since the completing of #1739, we can guide people to use the SegmentMetadataQuery for introspection rather than the broker dimensions and metrics endpoints.

**Comment by xvrl** [comment]
should we deprecate the broker endpoints then?

**Comment by fjy** [comment]
I think we can mark them as deprecated and include comments on what to use instead and remove things a few versions from now.
