### ISSUE TITLE
All images are broken in docs

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#1478]
e.g. http://druid.io/docs/latest/development/integrating-druid-with-other-technologies.html

@himanshug

**Comment by himanshug** [comment]
let me take a look

**Comment by himanshug** [comment]
ok got it, 
images are referred by "../img/xyz.png"
docs are moved to specific folders and should refer to "../../img/xyz.png"
not sure why I dint notice while my testing. sending PR soon.

**Comment by fjy** [comment]
@himanshug things still appear broken

**Comment by fjy** [comment]
at elast this is still broken: http://druid.io/docs/latest/development/integrating-druid-with-other-technologies.html

**Comment by himanshug** [comment]
https://github.com/druid-io/druid-io.github.io/tree/master/docs/img

**Comment by himanshug** [comment]
@fjy I'm sending PR to add missing images

**Comment by himanshug** [comment]
@fjy https://github.com/druid-io/druid-io.github.io/pull/141/
