### ISSUE TITLE
There are still broken documentation links

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#1481]
E.g. http://druid.io/docs/latest/ingestion/ingestion-faq.html

@himanshug

**Comment by himanshug** [comment]
hmm... some of the filenames were changed in https://github.com/himanshug/druid/commit/d2346b68344ad56e05da85519f4572ef7ff00384 but it link to them were not updated.

let me fix those

**Comment by himanshug** [comment]
actually, links were updated too
@fjy is there something linking to http://druid.io/docs/latest/ingestion/ingestion-faq.html ?

**Comment by himanshug** [comment]
@fjy ok I see now, filename changed made in  https://github.com/druid-io/druid/commit/d2346b68344ad56e05da85519f4572ef7ff00384 are not done to the toc.textile file. let me fix that

**Comment by himanshug** [comment]
@fjy https://github.com/druid-io/druid/pull/1483

**Comment by himanshug** [comment]
PR to update website https://github.com/druid-io/druid-io.github.io/pull/142/

**Comment by himanshug** [comment]
@fjy PR to update website https://github.com/druid-io/druid-io.github.io/pull/142/
