### ISSUE TITLE
Store aggregatorFactories in segment metadata

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#1514]
Storing aggregatorFactories in segment metadata will make it possible to reindex existing segments without having to provide the original aggregators out-of-band. As a bonus, it would also be nice to store the QueryGranularity used for indexing. This isn't required for reindexing, since it would work fine to use QueryGranularity.NONE, but it would still be cool.

**Comment by himanshug** [comment]
I wrote some code towards this as part of segment metadata work in #1609 but separated it from that PR and made that contain only essential segment metadata that was required for that PR, so that code sits on my machine.
But, If we store QueryGranularity in the segment metadata and two segments are merged/appended, what should be the QueryGranularity of that final segment for example in the case of AppendTask ?

**Comment by gianm** [comment]
IMO the LCM of the underlying granularities makes sense, as that's all that we can guarantee will be available for queries.

This can get weird if we have funky granularities, but I think that's ok since at least it's honest. Like, if we have one segment with queryGranularity DAY - Los_Angeles and one with queryGranularity DAY - UTC then the LCM is ALL.

**Comment by xvrl** [comment]
I don't think we should ever destroy data on merge / append. We could also simply not merge things that have incompatible granularities, or default to NONE, and leave it to the user at query time.

**Comment by gianm** [comment]
hmm, maybe we should discuss how we expect people to use this metadata and decide based on that.

I was thinking that the QueryGranularity metadata would be used by UIs so they could use it to decide which queryGranularities to use without needing to be preconfigured by the user. For that I think the LCM is reasonable- you wouldn't want to offer hourly granularity queries on an interval that has mixed hour granularity and day granularity.

Using NONE is gonna make the logic for a UI kind of messy, since they'll think millisecond granularity is available.

I think it's ok to avoid automatic merges of incompatible granularities, but IMO it should be possible for a user to ask for a merge of two segments with incompatible granularities.

**Comment by himanshug** [comment]
@gianm I don't think QueryGranularity exposes enough methods to come up with LCM .

@xvrl 
wrt destroying data, aggregators should still be merged (so if 2 segments have aggregator with same name, one of them will go away) ? 
For QueryGranularity, I like the option of NONE in any case.

is it OK for me to send a PR with partial code that does not handle merge/append of segment metadata, then we can discuss more concretely in the PR.

**Comment by gianm** [comment]
I think if we store NONE it wouldn't actually be useful for much. Maybe that is a failure of imagination, though…

**Comment by himanshug** [comment]
@gianm I typed my comment w/o seeing yours. but anyway, Given that there is no intelligent way to combine QueryGranularity, how will things like coordinator merge work ?

**Comment by gianm** [comment]
@himanshug when you're actually doing a merge, you can always just use NONE for the indexing- it doesn't matter what's in the underlying segments. But storing NONE in the metadata is not really useful if you want it to represent what is actually usefully queryable.

Fwiw I think it would be fine for now to leave QueryGranularity out of the metadata, and ask users to "know" what it should be. Having the aggregators in there is the real win since it makes automatic reindexing possible.

**Comment by xvrl** [comment]
@gianm my concern with updating query granularity at merge time would be to cause downstream queries to return different results after a merge than they did before if the goal is to expose the query granularity to the client.

**Comment by gianm** [comment]
@xvrl yeah, I agree that's kind of weird. I think we could probably do one of these to make it less weird,

1) potentially include multiple queryGranularities per segment; split up by interval. When the merge process merges segments that don't all cover the same interval, it can faithfully represent what's there in different areas of the timeline. Users would presumably already have some code to handled different queryGranularities on different parts of the timeline, since different segments could have different queryGranularities.

2) don't include queryGranularities, establish an expectation that it's the user's problem.

Even if we do (1) we still have the potential to throw away information (when two segments for the same interval have different granularities) but I think that's ok. If you merge a queryGranularity = HOUR segment with a queryGranularity = DAY segment and the intervals overlap, then the resulting segment really should represent itself as DAY.

**Comment by himanshug** [comment]
@gianm 
1) If two segments for same interval have different granularities, there is no way to find which one is coarser granularity
2) sounds like delaying the queryGranularity stuff for another time and just do AggregatorFactory in metadata for now. Actually, I have the code to just put AggregatorFactory in segment metadata.. I should probably submit a PR for just that.

**Comment by gianm** [comment]
@himanshug I'm OK with (2)

**Comment by cheddar** [comment]
(1) doesn't actually solve the "Los Angeles Day" versus "UTC Day" question because those will end up merging together.

That said, I think (1) is fine (as is throwing away the finer granularities) as long as we ensure that aggregations are done on the same timezone and throw an error otherwise.

**Comment by gianm** [comment]
@cheddar throw an error when? Original ingestion, merging, querying?

**Comment by cheddar** [comment]
merging

**Comment by gianm** [comment]
As long as there's a reasonable way to rescue yourself from your merge cronjob failing every day saying "cannot combine segments with mismatched granularities… cannot combine segments with mismatched granularities…"

Reindex your data, I guess?

Is there any valid reason to have queryGranularities that do not fit cleanly into a hierarchy?

I can't really think of one other than "oops, my older data was on UTC days but what I really wanted was Los Angeles days. But I don't want to reindex my older data so I'll just set new ingestion to work on Los Angeles"

**Comment by cheddar** [comment]
That's the only one I can come up with as well.  I think that the correct solution to that problem, however, is to store the new granularity in a different table.  If you co-locate daily data aggregated on UTC days with Pacific Days, the query side won't really make sense either.
