### ISSUE TITLE
Typo: "HadoopBatchIndexer" should be "HadoopDruidIndexer"

### ISSUE THREAD

**Issue by solimant** [druid-io/druid#1525]
> Running the Task
The Hadoop Index Config submitted as part of an Hadoop Index Task is identical to the Hadoop Index Config used by the ~~HadoopBatchIndexer~~ HadoopDruidIndexer except that three fields must be omitted: segmentOutputPath, workingPath, updaterJobSpec. The Indexing Service takes care of setting these fields internally.

Locations affected:
* docs/content/ingestion/batch-ingestion.md
* docs/content/misc/tasks.md

**Comment by fjy** [comment]
@solimant Thanks for this catch. Do you mind submitting a PR with the fix?

**Comment by solimant** [comment]
@fjy Sure, I will do that.

**Comment by solimant** [comment]
@fjy I've created the pull request.
