### ISSUE TITLE
Better documentation of 0.6.171 MSYQL UTF8 notes

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#1556]
https://github.com/druid-io/druid/releases/tag/druid-0.6.171

Has notes about MYSQL that don't seem to be captured anywhere in the official docs

This ask is that specific db dependent configurations be captured in the documentation.

(maybe in http://druid.io/docs/latest/dependencies/metadata-storage.html ?)

**Comment by drcrallen** [comment]
Came up as a result of https://groups.google.com/d/msg/druid-user/ZTMTbm4c30c/4HoK6WTjMIIJ

**Comment by fjy** [comment]
Fixed by https://github.com/druid-io/druid/pull/1571/files
