### ISSUE TITLE
brokers like to disagree once in a while for a sec or so

### ISSUE THREAD

**Issue by sixtus** [druid-io/druid#157]
to avoid the effects of realtime intake, I use ruby-druid with

start = (Date.today - 7).to_time
stop = (Date.today - 1).to_time

and in my nagios check I do

if result.any? { |answer| answer != result[0]}
  puts "brokers disagree #{result.to_json}"
  exit 2
end

Given the whole cluster is up, why can the brokers ever disagree?

Nagios tells me they do:

Once in a while, for roughly 10%, for like 5mins in a week or so.

It's frequent enough to file a ticket.

**Comment by fjy** [comment]
I am closing this as there have been no updates for a long time. Please reopen if it is still an issue.
