### ISSUE TITLE
Parent Pom file inccorrect

### ISSUE THREAD

**Issue by gbarton** [druid-io/druid#1575]
When I go to pull artifacts from maven central I get errors on all jars like this:

Invalid artifact descriptor for io.druid:druid-aws-common:jar:0.8.0: 3 problems were encountered while building the effective model for io.druid:druid-aws-common:0.8.0 [ERROR] Invalid packaging for parent POM io.druid:druid:0.8.0, must be "pom" but is "tar.gz" @ io.druid:druid:0.8.0 [ERROR] 'dependencies.dependency.version' for com.amazonaws:aws-java-sdk:jar is missing. @ [ERROR] 'dependencies.dependency.version' for junit:junit:jar is missing. @

**Comment by drcrallen** [comment]
@gbarton What command are you running to get this error?

**Comment by gbarton** [comment]
We have a thin wrapper around aether to pull deps from maven artifacts down into our artifactory.  That is whats coughing up on the parent pom.  I have nearly 12,000 artifacts in my artifactory and never seen this before.
I have browsed the pom files and don't see any obvious place where this is coming from. The parent pom looks reasonable to me.  Where are you building the tar from?

**Comment by drcrallen** [comment]
@gbarton are you using pull-deps in druid or an external aether client?

**Comment by gbarton** [comment]
External aether client.  I could be doing something dumb within it, just never came across this error before.

**Comment by drcrallen** [comment]
You can check out Druid's pull-deps command as per http://druid.io/docs/latest/tutorials/tutorial-a-first-look-at-druid.html#making-maven-druid-dependencies-available-offline And if that is broken please let us know. Additionally, if you find something about the way that druid packages things that breaks aether or maven specifications, then I would also be very interested in knowing about it.

For releases, the procedure at https://github.com/druid-io/oss-parent  is followed.

Unfortunately, external aether clients cannot be supported unless there's something that Druid is doing that breaks a specification. Closing until there is more evidence that there is a problem with the druid build system. At which point this should most definite be reopened.
