### ISSUE TITLE
Error in the documentation: Field accessor post-aggregator

### ISSUE THREAD

**Issue by MarConSchneid** [druid-io/druid#1584]
Issue open based on the discussion: https://groups.google.com/forum/#!topic/druid-user/zUpDX1H2_Nw

The general example for the Field accessor post-aggregator (http://druid.io/docs/latest/querying/post-aggregations.html) has a wrong syntax:
 { "type" : "fieldAccess", "fieldName" : <aggregator_name> }

and further down the page in the example you can find this code example (which works):
{ "type" : "fieldAccess", "name" : "tot", "fieldName" : "tot" }

With best regards
Martin Schneider

**Comment by fjy** [comment]
@MarConSchneid do you think you can submit a PR for this fix?

**Comment by MarConSchneid** [comment]
Sorry, for letting you wait, but I'm currently on parental leave. Let me know if I did it correct. (first time for me to contribute to a big project).

**Comment by xvrl** [comment]
@MarConSchneid it looks like you submitted the PR to your own repository instead of druid-io. If it's too much trouble the re-submit, I can merge your changes directly from your repo. We just need you to sign our CLA first here, http://druid.io/community/cla.html Thanks!

**Comment by MarConSchneid** [comment]
@xvrl I've signed the CLA. And sorry for the trouble.

**Comment by xvrl** [comment]
fixed by https://github.com/druid-io/druid/pull/1629
