### ISSUE TITLE
how to install druid database?

### ISSUE THREAD

**Issue by zengzhihai110** [druid-io/druid#1606]
i see the docs 
i can't understand  

please give better install docs?

**Comment by fjy** [comment]
@zengzhihai110 This is a very vague question. What exactly are you confused about? Have you tried the tutorials?

**Comment by zengzhihai110** [comment]
您能听懂中文吗？我英文不大好。那个官方文档，我按照上面的走，都不能正常的按照那个的结果显示出来，你能给下更好地方式让我明白安装druid的 过程吗？

**Comment by fjy** [comment]
@zengzhihai110 

我可以讲中文，但是我们希望用英文来作为主要语言，以方便Druid社区查询问题。在线有一些教程可以帮助你理解Druid setup：http://druid.io/docs/0.8.0/tutorials/index.html。Druid是一个分布式系统，所以我很难用短篇的中文来解释setup的过程，最好的方法还是学习在线教程。

I do speak Chinese but we prefer to keep the language here in English so the community can easily search for issues. There are a few tutorials related to setting up Druid for the first time: http://druid.io/docs/0.8.0/tutorials/index.html. Druid is a distributed system so it is very difficult for me to write a short summary of how you can set it up without you spending some time to learn about the system.

**Comment by zengzhihai110** [comment]
ok  thank you

**Comment by fjy** [comment]
You can also ask questions and get help through our user group: https://groups.google.com/forum/#!forum/druid-user

**Comment by zengzhihai110** [comment]
thank you very much
