### ISSUE TITLE
travis has come to a crawl and failing builds with timeout based tests

### ISSUE THREAD

**Issue by himanshug** [druid-io/druid#1621]
it seems to be failing too much for timeouts and concurrency, seems like something that needs attention

https://travis-ci.org/druid-io/druid/jobs/75361405
```
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.384 sec - in io.druid.server.namespace.cache.JDBCExtractionNamespaceTest

Running io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest

Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 50.297 sec <<< FAILURE! - in io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest

testDelete(io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest)  Time elapsed: 50.024 sec  <<< ERROR!

java.lang.Exception: test timed out after 50000 milliseconds

	at io.druid.server.namespace.cache.NamespaceExtractionCacheManager.removeNamespaceLocalMetadata(NamespaceExtractionCacheManager.java:296)

	at io.druid.server.namespace.cache.NamespaceExtractionCacheManager.delete(NamespaceExtractionCacheManager.java:514)

	at io.druid.server.namespace.cache.OnHeapNamespaceExtractionCacheManager.delete(OnHeapNamespaceExtractionCacheManager.java:99)

	at io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest.testDelete(NamespaceExtractionCacheManagerExecutorsTest.java:333)

	at 
```

https://travis-ci.org/druid-io/druid/jobs/75361404
```
Results :

Failed tests: 

  IncrementalIndexTest.testConcurrentAddRead:362 Did not hit concurrency, please try again

Tests run: 8007, Failures: 1, Errors: 0, Skipped: 16
```

**Comment by himanshug** [comment]
sometimes I notice failures like zookeeper failing on a path existence which should have teared down etc and db not having something that was supposed to happen via setup. I am wondering, is this related to 2 jobs (java7, java8) running in parallel.
do they both run on same container in parallel?

**Comment by xvrl** [comment]
@himanshug we can try reducing parallelism. I do notice that builds tend to fail less often when building independently, so we may be running into races between the two builds somewhere.

**Comment by xvrl** [comment]
@himanshug I reduced travis build concurrency to 1, let's see if this works, or if it causes things to become unbearably slow. Let's reopen if it remains an issue.

**Comment by himanshug** [comment]
@xvrl I am wondering if we can disable java-8 build as well. We don't release java-8 compiled artifacts so it is not really necessary for now. We will need it once druid switches to java-8 exclusive.
