### ISSUE TITLE
MySQL 5.7.6 breaks Druid mysql metadata storage adapter

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#1701]
MySQL version 5.7.6 changed permissions required for `SHOW VARIABLES` (see https://dev.mysql.com/doc/refman/5.7/en/show-variables.html). Druid uses this to check the default database character set. Default MySQL permissions are not enough anymore, causing Druid to fail this check and preventing startup.

**Workaround:** use MySQL <= 5.7.5 or to set `show_compatibility_56 = on` in the MySQL configuration.

**Comment by gilmichlin** [comment]
+1 on that
