### ISSUE TITLE
about Production Cluster Configuration  ERROR [main] io.druid.cli.CliCoordinator - Error when starting up.  Failing.

### ISSUE THREAD

**Issue by zengzhihai110** [druid-io/druid#1706]
i use http://druid.io/docs/0.8.0/configuration/production-cluster.html

but i don't understand this why  ?

please give me a clearly Course?

**Comment by nishantmonu51** [comment]
A complete stack trace for the error you are getting would be helpful. 
Please use druid-user group for any further questions. 
https://groups.google.com/forum/#!forum/druid-user
Github Issues are meant for bugs and feature requests.
