### ISSUE TITLE
about indexing service question

### ISSUE THREAD

**Issue by zengzhihai110** [druid-io/druid#1707]
Is the Indexing service necessary? Is there any problem if I set up my cluster without indexing service?

**Comment by nishantmonu51** [comment]
No, Its not necessary to use indexing-service, you can directly spawn realtime nodes. 
Please drop a mail to druid-user group for any further questions. 
https://groups.google.com/forum/#!forum/druid-user
Github Issues are meant for bugs and feature requests.
