### ISSUE TITLE
about the question  i don't understand when i see the torials

### ISSUE THREAD

**Issue by zengzhihai110** [druid-io/druid#1708]
Sounds like Indexer nodes are optional, and you can ingest using Realtime nodes directly?
Indexer node how to HA?
Without using Indexer, the Realtime nodes are not HA?
If using Indexer then you don't need Realtime nodes?

**Comment by nishantmonu51** [comment]
Please drop a mail to druid-user group for any general questions. 
https://groups.google.com/forum/#!forum/druid-user
Github Issues are meant for bugs and feature requests.
