### ISSUE TITLE
how to get all distinct dimensions? 

### ISSUE THREAD

**Issue by zengzhihai110** [druid-io/druid#1733]
how to get all distinct dimensions?

**Comment by zengzhihai110** [comment]
i mean i want to get distinct dimesion values,if demesions has three. a , b , c 
for example:
a : 'e' , b : 'r' , c: 'fs'
a : 'sa' , b : 'r' , c: 'fs'
a : 'e' , b : 'kjkj' , c: 'fs'

i want get dimesion a distinct value 'e','sa'

**Comment by nishantmonu51** [comment]
@zengzhihai110 I believe you can get it via select query http://druid.io/docs/latest/development/select-query.html
Also If you are only interested on Top N values you can use a TopN query.

**Comment by fjy** [comment]
@zengzhihai110 your best bet is a lexicographic topN, which can paginate
through all values of a dimension.

http://druid.io/docs/latest/querying/topnmetricspec.html

**Comment by zengzhihai110** [comment]
thanks
