### ISSUE TITLE
SegmentMetadataQuery should return metadata.drd metadata

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#1749]
The main reason for this is so when #1728 is ready, the SegmentMetadataQuery will be a simple way to figure out what aggregators can be used to query Druid data.

**Comment by xvrl** [comment]
@gianm not sure if this is beyond the scope of this, but it would also me nice to have actual column byte size and index size information in there.

**Comment by gianm** [comment]
I think it is beyond scope but that would be a good change.

**Comment by gianm** [comment]
we went a different way with this in #2295; the `AGGREGATORS` AnalysisType retrieves those in an aggregators-specific way.
