### ISSUE TITLE
SegmentMetadataQuery should have flags for specific kinds of metadata

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#1750]
The reason being that some kinds of metadata (like estimated size) can be expensive to compute. Callers may not want all of them. I think a reasonable way to do this is to have an enum of flags and to have the query take an EnumSet of them. The default should probably be what exists now, for backwards compatibility.

**Comment by xvrl** [comment]
which kinds of metadata do you think should be optional? Do you have anything specific in mind?

**Comment by gianm** [comment]
The estimated size for sure, since it ends up reading a bunch of parts of the columns that otherwise wouldn't need to be read.

**Comment by gianm** [comment]
But also possibly everything??

**Comment by gianm** [comment]
This was done through analysisTypes.
