### ISSUE TITLE
IngestSegmentFirehose fails to read all rows from segment

### ISSUE THREAD

**Issue by jtmhom88** [druid-io/druid#1785]
The situation is that I tried delta ingestion with 0.8.1 stable release.
I used the following spec to do the "multi" ingestion.
```json
"ioConfig" : {
    "type" : "hadoop",
    "inputSpec" : {
      "type" : "multi",
      "children": [
        {
            "type" : "dataSource",
            "ingestionSpec" : {
                "dataSource": "events",
                "interval": "2015-09-13T03:00:00/PT3H"
            }
        },
        {
            "type" : "static",
            "paths": "hdfs://ipaddress/file1.gz,hdfs://ipaddress/file2.gz,hdfs://ipaddress/file3.gz, ..."
        }
      ]
    },
```
Here is a basic description of the problem.
1. I have 10 data files
2. I static batch ingest 10 of them
3. Issue a count query or a longsum query. 
10files, count:16311627, longsum:17826751
4. Use 7 of the 10 files, batch ingest them.
5. Issue a count/longsum query.
7files, count: 12428400, longsum: 13580744
6. Then take the 3 remaining files and delta ingest them.
7. Issue count/longsum query.
7+3 multi count:4559291, longsum:5062801
Notice that not only do the counts not match up, but they drop by 40%.
If you then look at the console, you will notice a concurrent drop in the segment size by the same amount.

I have data files to reproduce the bug, but I would like to send them via email and not post them publicly.
Please send me a request to jhom@kochava.com and I will send them to you with instructions on how to reproduce the issue.

**Comment by xvrl** [comment]
@jtmhom88 the fact that counts don't match up shouldn't be a problem, that's expected if some rows in the remaining 3 files have the same timestamp + dimension combination as in the existing 7 files. Those rows would get aggregated together into a single row. Count only returns the number of aggregated Rows.

For longSum however, the sums should match up as long as the aggregation spec during ingestion is also longSum for that same column. What aggregations do you use during ingestion?

**Comment by jtmhom88** [comment]
Here is the longsum query:
{
  "queryType": "timeseries",
  "dataSource": "events",
  "intervals": [
    "2015-09-12/2015-09-12T01:00:01"
  ],
  "granularity": {
    "type": "period",
    "period": "PT1H",
    "timeZone": "Etc/UTC"
  },
  "aggregations": [
    {
      "name": "cnt",
      "type": "longSum",
      "fieldName": "count"
    }
  ]
}

Here is the full ingestion spec:
{
  "dataSchema" : {
    "dataSource" : "events",
    "parser" : {
      "type" : "string",
      "parseSpec" : {
          "format" : "json",
          "timestampSpec" : {
            "column" : "event_time_registered",
            "format" : "posix"
          },
          "dimensionsSpec" : {
            "dimensions": [
              "app_guid",
              "app_id",
              "app_platform",
              "attribution_campaign",
              "attribution_country",
              "attribution_date",
              "attribution_ko_click_id",
              "attribution_legacy_tracker_id",
              "attribution_network",
              "attribution_network_id",
              "attribution_network_key",
              "attribution_tier",
              "attribution_timestamp",
              "attribution_tracker",
              "attribution_tracker_id",
              "device_id",
              "device_os",
              "device_type",
              "device_version",
              "dimension_data",
              "event_name",
              "event_time_registered",
              "geo_city",
              "geo_country",
              "geo_lat",
              "geo_lon",
              "geo_region",
              "geo_zip",
              "request_ip",
              "request_ua"
            ],
            "dimensionExclusions" : [],
            "spatialDimensions" : []
          }
        }
    },
      "metricsSpec" : [
        {
          "type" : "count",
          "name" : "count"
        },
        {
          "type": "doubleSum",
          "name": "dimension_count",
          "fieldName": "dimension_count"
        },
        {
          "type": "doubleSum",
          "name": "dimension_sum",
          "fieldName": "dimension_sum"
        },
        {
          "type": "doubleSum",
          "name": "event_time_processed",
          "fieldName": "event_time_processed"
        },
        {
          "type": "hyperUnique",
          "name": "unique_devices",
          "fieldName": "device_id"
        }
      ],
     "granularitySpec" : {
        "type" : "uniform",
        "segmentGranularity" : "HOUR",
        "queryGranularity" : "MINUTE",
        "intervals" : [ "INTERVALSPEC" ]
      }

**Comment by jtmhom88** [comment]
What about the segment sizes on the console?
The new replacement segments are significantly smaller than the old segments.
It looks like the resulting size of the segment is of the magnitude of the delta files.
Clearly aggregation cannot be responsible for shrinking the data by that much.

**Comment by himanshug** [comment]
I will try and repro it over the weekend.

**Comment by himanshug** [comment]
@jtmhom88 I was able to reproduce the issue with the data you provided. There is indeed a bug, it is related to not being able to read all rows from existing input segments in some cases, I will be sending patch to fix that soon.

**Comment by drcrallen** [comment]
@himanshug Can you update the title of this issue to better reflect the bug?

**Comment by himanshug** [comment]
IngestSegmentFirehose fails to read all rows from segment which results in batch delta ingestion producing partial data from existing dataSource interval specified.

**Comment by jtmhom88** [comment]
Do you have an approximate ETA on the patch?

**Comment by jtmhom88** [comment]
OK. I posted a request for ETA. Waiting for reply.

**Comment by himanshug** [comment]
@jtmhom88 is it possible for you to build java-utils with https://github.com/metamx/java-util/pull/32 and use that in your cluster and verify that it fixes the issue?

**Comment by jtmhom88** [comment]
I looked at the source code of the latest release https://github.com/druid-io/druid/releases/tag/druid-0.8.1
I don't see the source file ConcatSequence.java as part of the build.
I'm not quite sure what you want me to do with the metamx/java-util#32 that you're pointing out. 
Sorry, can you give me more explanation?

**Comment by himanshug** [comment]
@jtmhom88 ConcatSequence.java is not part of core druid source code but a library called "java-util" to which PR https://github.com/metamx/java-util/pull/32 is made. One way to try it out would be to git clone java-util project, apply that patch and do a "mvn clean install" which will create and place java-utils-0.27.4-SNAPSHOT.jar in your local maven repository.
then in the druid code, update pom.xml make following change..
```
-        <metamx.java-util.version>0.27.3</metamx.java-util.version>
+        <metamx.java-util.version>0.27.4</metamx.java-util.version>
```
then do a mvn clean install from base directory of druid code and that will produce the druid uber jar in services/target/, you can use that to run druid.

That said, I've tested the patch to be working.

**Comment by himanshug** [comment]
@jtmhom88 since java-util-0.27.4 is released now, you can get the fix only by changing druid code base pom.xml
```
-        <metamx.java-util.version>0.27.3</metamx.java-util.version>
+        <metamx.java-util.version>0.27.4</metamx.java-util.version>
```

**Comment by jtmhom88** [comment]
@himanshug  Hey thanks. I am looking at the druid build. It looks like all you did was change that one line in the pom.xml on the druid top level. Is this correct?

**Comment by himanshug** [comment]
@jtmhom88 yes

**Comment by jtmhom88** [comment]
I tested it. The patch appears to work. Thank-you!

**Comment by drcrallen** [comment]
@jtmhom88 Thanks for verifying! We're trying to get the last polish on 0.8.2-RC, which means we should have a stable release with this fix in it "soon".
