### ISSUE TITLE
io.druid.initialization.LogLevelAdjuster uses log4j directly

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#1805]
Ideally nothing in druid would explicitly depend on anything other than slf4j for logging. But `io.druid.initialization.LogLevelAdjuster` explicitly uses

```
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
```

This makes using alternate slf4j implementations like logback much harder.

**Comment by drcrallen** [comment]
@cheddar / @fjy / @xvrl do we even need `io.druid.initialization.LogLevelAdjuster` since log4j2 can be adjusted via jmx?

**Comment by himanshug** [comment]
sounds like it is not useful post log4j2 upgrade.

**Comment by gomezd** [comment]
Would it be possible to add a config to disable log4j mbean registration, similar to what [zookeeper does](https://github.com/apache/zookeeper/blob/master/src/java/main/org/apache/zookeeper/jmx/ManagedUtil.java#L65)?

**Comment by drcrallen** [comment]
Put in a patch to just remove it instead.
