### ISSUE TITLE
Druid 0.8.1 coordinator console ui issues

### ISSUE THREAD

**Issue by pdeva** [druid-io/druid#1817]
The 'cluster' panel has:

1. Duplicate links to 'old console'
2. A perpetual 'loading' spinner

Screenshot:
http://screencast.com/t/Cxh3rltYf

**Comment by drcrallen** [comment]
That stuff in the upper right is supposed to be auto refresh. Does the page load other than the persistent spinner?

**Comment by pdeva** [comment]
the rest of the page does load. but the spinner and the duplicate links remain forever

**Comment by xvrl** [comment]
@pdeva if you don't have an indexing service, it will show the coordinator twice. I've noticed that a while back but a quick fix introduced other layout problems, so I left it at that. As a workaround you can spin up an overlord :)

Regarding the spinner, I'm not quite sure what may be happening, how are you accessing the console?
Are you running a standalone console or accessing it from the coordinator?

**Comment by pdeva** [comment]
i am accessing it from the coordinator

**Comment by drcrallen** [comment]
Without having looked into it, it would not surprise me in the least if the code was waiting for the indexing service part to finish loading before implementing the auto-refresh. The loading spinner is probably stuck because it can't load the indexing service data (the ui is not very smart)

**Comment by drcrallen** [comment]
This is actually a bug in https://github.com/druid-io/druid-console and not druid, so I'm closing it out here in favor of an issue over there.

**Comment by drcrallen** [comment]
https://github.com/druid-io/druid-console/issues/5
https://github.com/druid-io/druid-console/issues/6
