### ISSUE TITLE
Retry for transient exceptions while doing cleanup for Hadoop Jobs

### ISSUE THREAD

**Issue by nishantmonu51** [druid-io/druid#1828]
From : https://github.com/druid-io/druid/pull/1815#discussion_r42021133

If there is any transient exception while doing cleanup in Hadoop Jobs, right now we simply propagate the exception. It would be better add Retry logic for transient exceptions in this case.

**Comment by drcrallen** [comment]
@nishantmonu51 is this fixed with #1815?

**Comment by fjy** [comment]
@nishantmonu51 is this still an issue?
