### ISSUE TITLE
Ability to flatten JSON objects during ingestion

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#1839]
This would probably make sense as additional options on the JSONParseSpec. Maybe something that lets people say they want "foo.bar" to mean pulling the "bar" key out of the "foo" object rather than pulling the root key "foo.bar".

It should also still be possible for someone to have a root key that is actually called "foo.bar".

**Comment by fjy** [comment]
+1

This is great.

**Comment by gianm** [comment]
Would be good to support stuff like:

`foo.bar` - bar key of the foo object
`foo[0].bar` - bar key of the first element of the foo array

Anything that doesn't exist should become null. If anything resolves into an object, it should probably also be null? I guess? (what do we do now?)

**Comment by fjy** [comment]
Fixed by https://github.com/druid-io/druid-api/pull/65
