### ISSUE TITLE
Wrong configuration example on querying/lookups.html

### ISSUE THREAD

**Issue by jaebinyo** [druid-io/druid#1853]
I tried to use the namespaced lookup functionality with 0.8.1 by following the example configuration in the doc (http://druid.io/docs/latest/querying/lookups.html)
but it didn't work. I ended up reading the source code and found that the configuration for namespaces should be

druid.query.extraction.namespace.lookups=[]

And the druid extension name to include is "io.druid.extensions:druid-namespace-lookup" not "io.druid.extensions:namespace-lookup"

The other thing I had to do is to include mysql connector jar in the classpath (which is not documented) for the case of mysql example in the doc.

**Comment by b-slim** [comment]
@jaebinyo thanks, i have sent a PR #1854

**Comment by drcrallen** [comment]
Should be fixed as per @b-slim 's comment
