### ISSUE TITLE
Ability to express SUBSTR as an extractionFn

### ISSUE THREAD

**Issue by vogievetsky** [druid-io/druid#1874]
This is part of Plywood/PlyQL and is currently being done using `javascript`

```sql
SELECT SUBSTR(`language`, 0, 3) FROM `wikipedia` GROUP BY 1
```

I would like to express this:

```json
{
  "type": "javascript",
  "function": "function(str) { return str.substr(0, 3); }"
}
```

as

```json
{
  "type": "substr",
  "index": 0,
  "length": 3
}
```

or equivalent

**Comment by xvrl** [comment]
you can use regex extraction function `.{0}(.{3}).*`, which should be faster than what you are doing

**Comment by vogievetsky** [comment]
The docs for the regex extraction function state: "Returns the first matching group for the given regular expression. If there is no match, it returns the dimension value as is."

Your suggestion would work when index is 0 i.e. `(.{x}).*` where x is length (I will prob add that). But it would not work in general for index > 0. since `.{9}(.{3}).*` would transform the strings of length <= 9 incorrectly to themselves (instead of `""`)

Clever regex hacks aside I think a substr would be very cool. Something akin to https://dev.mysql.com/doc/refman/5.0/en/string-functions.html#function_substr
