### ISSUE TITLE
Make 'search' filter have a case sensitive option

### ISSUE THREAD

**Issue by vogievetsky** [druid-io/druid#1878]
Right now is is case insensitive and I am forced to use javascript filters to create a case sensitive contains.

Maybe add a 'contains' query that can take case sensitivity as a parameter?

Something like:

```json
{
  "filter": {
    "type": "search",
    "dimension": "product",
    "query": {
      "type": "contains",
      "value": "foo",
      "caseInsensitive": false  (default)
    }
  }
}
```

**Comment by markgrover** [comment]
I think this can be closed since https://github.com/druid-io/druid/pull/1892 took care of this. I don't think I have the privs to close this.
