### ISSUE TITLE
Add a range filter option (for numeric dimensions and strings)

### ISSUE THREAD

**Issue by vogievetsky** [druid-io/druid#1879]
This is part of Plywood/PlyQL and is currently being done using `javascript`

```sql
SELECT COUNT(*) AS 'Count' FROM `people` WHERE `age` BETWEEN 18 AND 30
```

**Note:** *age* is a dimension

Right now I have to do:

```json
{
  "type": "javascript",
  "dimension": "age",
  "function": "function(a) { a = Number(a); return 18 <= a && a < 30; }"
}
```

Sometimes I have to filter on a range of string values like so:

```json
{
  "type" : "javascript",
  "dimension" : "name",
  "function" : "function(x) { return(x >= 'bar' && x <= 'foo') }"
}
```

I would love it if you could add a between filter

Something like:

```json
{
  "type": "between",
  "dimension": "age",
  "lower": 18,
  "upper": 30
}
```

The bounds to default to `lower <= x <= upper` but should be **configurable**

**Comment by fjy** [comment]
Fixed by #1936
