### ISSUE TITLE
Conflicting versions of the Apache HTTP Client

### ISSUE THREAD

**Issue by mmcgowan** [druid-io/druid#1915]
The main pom.xml file has both the deprecated Apache HTTP Client:
            <dependency>
                <groupId>commons-httpclient</groupId>
                <artifactId>commons-httpclient</artifactId>
                <version>3.1</version>
            </dependency>

and the new one:
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpclient</artifactId>
                <version>4.5.1</version>
            </dependency>

**Comment by drcrallen** [comment]
While I agree having different dependencies like this is not desired, is there a particular error or confusion that comes out of them both being present? (that helps prioritize fixes)

**Comment by xvrl** [comment]
@mmcgowan some libraries that Druid depends on still depend on the old http client, hence why we need to include it.

**Comment by fjy** [comment]
@xvrl which libraries?

**Comment by xvrl** [comment]
@mmcgowan for what it's worth commons-httpclient and org.apache.httpcomponents are essentially two distinct libraries. They should not be conflicting in any way. Are you having any actual issues from depending on both?

@fjy currently the hadoop jars depend on the old commons-httpclient, but maybe we can remove that dependency explicitly unless we overrode the version for some other reason

**Comment by mmcgowan** [comment]
Hi @drcrallen, @xvrl, 

I see. 

I've built a Druid metrics to Datadog Druid extension. It depends on Dropwizard metrics, which uses org.apache.httpcomponents:httpclient:4.3.5.

I'm currently on Druid 0.8.1. I had issues with this version. But since the two dependencies are different, it looks like this should be able to work with Druid 0.8.2.

Michael

**Comment by sascha-coenen** [comment]
@mmcgowan you mentioned that you have build a Datadog Druid extension.
This sounds very interesting. I searched for it but couldn't find anything.
Can you tell me anything about it? Is it open-source?
thanks
Sascha

**Comment by drcrallen** [comment]
FYI, I did a lot of dependency resolution to get 0.9.0 to work with some of our extensions. The results can be found here: https://github.com/druid-io/druid/pull/2596

This might affect how this extension manages exclusions. Hopefully the information in the PR (and expanded documentation in the PR) helps.
