### ISSUE TITLE
How to achieve the count(distinct ) function;

### ISSUE THREAD

**Issue by chenzhaohangbj12** [druid-io/druid#1916]
hello:
I  query like:
  "aggregations": [
    { "type": "cardinality", "name": "busi", "fieldNames":  ["cookie"]  }
  ],
but the result is 
  "timestamp" : "2015-11-04T03:00:00.000Z",
  "result" : {
    "busi" : 11.029647221949576
  }

"11" may be is what i want.What is behind the decimal point?

Whether there are other ways to achieve the count(distinct ) function?

**Comment by xvrl** [comment]
cardinality aggregator uses hyper-log-log, which is a probabilistic approach to counting distinct values. As such it is not an exact count, but a floating point approximation.

**Comment by xvrl** [comment]
Another possible way to count distinct values would be to do a topN sorted lexicographically, and page through the results to count them.

**Comment by chenzhaohangbj12** [comment]
thanks
