### ISSUE TITLE
I would like to have a RegExp based ingestion parse spec

### ISSUE THREAD

**Issue by vogievetsky** [druid-io/druid#1930]
So I could provide a regexp with a bunch of matching groups and a list of labels for the matching group and have Druid ingest a file where each line can be parsed by the provided RegExp.

**Comment by gianm** [comment]
Man was not meant to have such power.

**Comment by xvrl** [comment]
@vogievetsky we might as well embed perl then :)

**Comment by gianm** [comment]
we need the `perl -pi` parser next

**Comment by gianm** [comment]
or #1931

**Comment by gianm** [comment]
this exists now, see http://druid.io/docs/0.9.0-rc1/ingestion/data-formats.html
