### ISSUE TITLE
I would like to have JavaScript ingestion parse spec

### ISSUE THREAD

**Issue by vogievetsky** [druid-io/druid#1931]
JavaScript.

JavaScript. JavaScript. JavaScript.

I would like to JavaScript data into Druid.

**Comment by vogievetsky** [comment]
I :heart: JavaScript

**Comment by drcrallen** [comment]
Since we have javascript stop-gaps for other actionable items in druid, it makes sense to have a parse spec as well.

**Comment by gianm** [comment]
this exists now, see http://druid.io/docs/0.9.0-rc1/ingestion/data-formats.html
