### ISSUE TITLE
Druid ParseSpec validator

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#1939]
As a user of Druid, I would like to be able to take example, or sub-sampled data, and pass it through a ParseSpec in such a way that I can easily debug and validate that my ParseSpec settings are correct, that my input data is not corrupt, and I am getting the values I expect to get.

**Comment by CHOIJAEHONG1** [comment]
@drcrallen  This issue seems to be sorted out refering to https://github.com/druid-io/druid/pull/2028#issuecomment-162640070
