### ISSUE TITLE
If Rejection Policy is Noop,Index

### ISSUE THREAD

**Issue by Hailei** [druid-io/druid#1971]
If Rejection Policy is set to "none",index can't be merged.
the log as following:
Start time [2015-11-16T03:00:00.000+08:00] >= [1970-01-01T08:00:00.000+08:00] min timestamp required in this run. Segment will be picked up in a future run.

Deep into the code 
```java
DateTime minTimestampAsDate = segmentGranularity.truncate(
        new DateTime(
            Math.max(
                windowMillis,
                rejectionPolicy.getCurrMaxTime()
                               .getMillis()
            )
            - windowMillis
        )
    );
    long minTimestamp = minTimestampAsDate.getMillis();

    log.info("Found [%,d] segments. Attempting to hand off segments that start before [%s].", sinks.size(), minTimestampAsDate);

    List<Map.Entry<Long, Sink>> sinksToPush = Lists.newArrayList();
    for (Map.Entry<Long, Sink> entry : sinks.entrySet()) {
      final Long intervalStart = entry.getKey();
      if (intervalStart < minTimestamp) {
        log.info("Adding entry [%s] for merge and push.", entry);
        sinksToPush.add(entry);
      } else {
        log.info(
            "Skipping persist and merge for entry [%s] : Start time [%s] >= [%s] min timestamp required in this run. Segment will be picked up in a future run.",
            entry,
            new DateTime(intervalStart),
            minTimestampAsDate
        );
      }
    }

```

minTimestampAsDate always is 1970-01-01T08:00:00.000+08:00,because rejectionPolicy.getCurrMaxTime().getMillis() is 0.

```java
  return new RejectionPolicy()
    {
      @Override
      public DateTime getCurrMaxTime()
      {
        return new DateTime(0);
      }

      @Override
      public boolean accept(long timestamp)
      {
        return true;
      }
    };
```

**Comment by Hailei** [comment]
If Rejection Policy is set to "none",index can't be merged.
the log as following:
Start time [2015-11-16T03:00:00.000+08:00] >= [1970-01-01T08:00:00.000+08:00] min timestamp required in this run. Segment will be picked up in a future run.

Deep into the code 
```java
DateTime minTimestampAsDate = segmentGranularity.truncate(
        new DateTime(
            Math.max(
                windowMillis,
                rejectionPolicy.getCurrMaxTime()
                               .getMillis()
            )
            - windowMillis
        )
    );
    long minTimestamp = minTimestampAsDate.getMillis();

    log.info("Found [%,d] segments. Attempting to hand off segments that start before [%s].", sinks.size(), minTimestampAsDate);

    List<Map.Entry<Long, Sink>> sinksToPush = Lists.newArrayList();
    for (Map.Entry<Long, Sink> entry : sinks.entrySet()) {
      final Long intervalStart = entry.getKey();
      if (intervalStart < minTimestamp) {
        log.info("Adding entry [%s] for merge and push.", entry);
        sinksToPush.add(entry);
      } else {
        log.info(
            "Skipping persist and merge for entry [%s] : Start time [%s] >= [%s] min timestamp required in this run. Segment will be picked up in a future run.",
            entry,
            new DateTime(intervalStart),
            minTimestampAsDate
        );
      }
    }

```

minTimestampAsDate always is 1970-01-01T08:00:00.000+08:00,because rejectionPolicy.getCurrMaxTime().getMillis() is 0.

```java
  return new RejectionPolicy()
    {
      @Override
      public DateTime getCurrMaxTime()
      {
        return new DateTime(0);
      }

      @Override
      public boolean accept(long timestamp)
      {
        return true;
      }
    };
```

**Comment by fjy** [comment]
@Hailei  do you mind posting this in the user groups?

**Comment by Hailei** [comment]
Great! In China,I can't access google user groups.Thanks

**Comment by himanshug** [comment]
@Hallei can you use apache.org mailing lists in china e.g. dev@hadoop.apache.org ?

@fjy may be another reason to move to ASF :)

**Comment by himanshug** [comment]
@Hailei can you use apache.org mailing lists in china e.g. dev@hadoop.apache.org ?

@fjy may be another reason to move to ASF :)

**Comment by himanshug** [comment]
also to answer the question, this behavior is expected. in production, you would use batch ingestion for historical data and serverTime rejection policy for current streamed events.
none and messageTime are just for prototyping.

**Comment by himanshug** [comment]
see faq http://druid.io/docs/latest/ingestion/faq.html

**Comment by Hailei** [comment]
@himanshug  why i choose noop. Because my log event is not strictly chronological. eg. current event is 10:05,next maybe 10:00, In this scenario,Whether message time or server time  can throw away some event.

**Comment by himanshug** [comment]
@Hailei unfortunately, your options are limited for now. you could use serverTime rejetion policy and use lambda architecture to periodically make corrections.
we are improving realtime ingestion to fix this use case but that will probably release sometime next quarter.

**Comment by Hailei** [comment]
@himanshug THANKS.good idea!
