### ISSUE TITLE
Inconsistent handling for interval in DataSourcesResource

### ISSUE THREAD

**Issue by nishantmonu51** [druid-io/druid#2021]
The /druid/coordinator/v1/datasources endpoint uses / for DELETE /{dataSourceName}?interval=... query parameters, but uses _ for GET /{dataSourceName}/intervals/{interval} path parameters. 
We should have a consistent way of representing intervals. 

https://github.com/druid-io/druid/pull/2015#discussion_r46210822

**Comment by harshjain2** [comment]
We are supporting GET operation on these APIs
1. /druid/coordinator/v1/datasources/{dataSourceName}/intervals/{interval} 
2. /druid/coordinator/v1/datasources/{dataSourceName}/intervals/{interval}?simple 
3. /druid/coordinator/v1/datasources/{dataSourceName}/intervals/{interval}?full

We should also support DELETE operation on these APIs
1. /druid/coordinator/v1/datasources/{dataSourceName} 
2. /druid/coordinator/v1/datasources/{dataSourceName}?kill=true
3. /druid/coordinator/v1/datasources/{dataSourceName}/intervals/{interval} 
4. /druid/coordinator/v1/datasources/{dataSourceName}/intervals/{interval}?kill=true 

This will ensure single way to represent intervals. 

As of now, we support Delete Operation with interval as QueryString parameter resulting in inconsistency in handling intervals as compared to corresponding GET APIs where interval is in Path parameter.
/druid/coordinator/v1/datasources/{dataSourceName}?kill=true&**interval={myISO8601Interval}**

Let me know if you agree/disagree on this approach.

**Comment by harshjain2** [comment]
Submitted PR for this. https://github.com/druid-io/druid/pull/2276

**Comment by xvrl** [comment]
Fixed by #2276
