### ISSUE TITLE
druid-0.8.3 release notes

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#2044]
This is a tracking issue for the upcoming druid-0.8.3.

# Release notes:

## Updating from 0.8.x

- You must set `druid.selectors.coordinator.serviceName` to your Coordinator's `druid.service` value (defaults to `druid/coordinator`) in common.runtime.properties of all nodes. Realtime handoff will only work if this config is properly set. (See #2015)

- Instead of the normal rolling update procedure, for this release you should update your Coordinator nodes before updating the overlord. (See #2015)

- Min/max aggregators are now deprecated and will be removed in Druid 0.9.0. Please use longMin, longMax, doubleMin, or doubleMax aggregators as appropriate.

## New Features

- #1881 Restorable indexing tasks
- #1897, #1991 complex aggregator based on http://datasketches.github.io
- #1943 Enable caching on intermediate realtime persists
- #1957 Ability to skip Incremental Index during query using query context

## Improvements

- #1770 Add segment merge time as a metric
- #1791 EventReceiverFirehoseMonitor
- #1824 Add hashCode and equals to UniformGranularitySpec
- #1889 update server metrics and emitter version
- #1920 Update curator to 2.9.1
- #1929 separate ingestion and query thread pool
- #1960 optimize index merge
- #1967 Add datasource and taskId to metrics emitted by peons
- #1973 CacheMonitor - make cache injection optional
- #2015 Remove ServerView from RealtimeIndexTasks and use coordinator http endpoint for handoffs
- #2045 Update mmx emitter to 0.3.6
- #2145 druid.indexer.task.restoreTasksOnRestart configuration

## Bug Fixes

- #1387 Add special handler to allow logger messages during shutdown
- #1799 Support multiple outer aggregators of same type
- #1815 Fix Race in jar upload during hadoop indexing
- #1842 Do not pass `druid.indexer.runner.javaOpts` to Peon as a property
- #1867 fixing hadoop test scope dependencies in indexing-hadoop
- #1888 forward cancellation request to all brokers, fixes #1802
- #1917 RemoteTaskActionClient: Fix statusCode check.
- #1932 DataSchema: Exclude metric names from dimension list.
- #1935 ForkingTaskRunner: Log without buffering.
- #1940 Move Jackson Guice adapters into io.druid
- #1954 EC2 autoscaler: avoid hitting aws filter limits
- #1985 Change LookupExtractionFn cache key to be unique
- #2036 Disable javadoc linting
- #1973 Make cache injection optional
- #2141 Fix some problems with restoring
- #2227 Update bytebuffer-collections to 0.2.4 (upstream bugfixes in roaring bitmaps)
- #2240 Fix loadRule when one of the tiers had no available servers
- #2207 Fix bug for thetaSketch metric not working with select queries
- #2266 Fix loss in segment announcements when segments do not fit in zNode
- #2189 add ChatHandlerServerModule to realtime example
- #2338 Fix tutorial so indexing service can start up

## Documentation

- #1832 add examples for duration and period granularities
- #1843 "druid.manager.segment" should be "druid.manager.segments
- #1854 Fix documentation about lookup
- #1900 fix doc - correct default value for maxRowsInMemory

Thanks to all the contributors to this release!

@b-slim
@binlijin
@dclim
@drcrallen
@fjy 
@gianm
@guobingkun
@himanshug
@nishantmonu51
@pjain1
@xvrl

**Comment by gianm** [comment]
Added #2015, #1973, #2045, #2045, #1770, #1967, #1889 which were in rc2 & rc3

**Comment by xvrl** [comment]
https://github.com/druid-io/druid/releases/tag/druid-0.8.3
