### ISSUE TITLE
Wrong title on Overlord console

### ISSUE THREAD

**Issue by guobingkun** [druid-io/druid#2080]
![image](https://cloud.githubusercontent.com/assets/11789051/11749705/ee546c48-9ff4-11e5-9471-af9677cb3039.png)

For some reason it's showing Coordinator Console.

**Comment by xvrl** [comment]
@guobingkun that's the wrong url, remove the `/console.html` part.
It just happens that resources are shared between overlord and coordinator so those pages are available on both.

**Comment by xvrl** [comment]
I also have a PR out to make this less confusing, so you never have to worry about the url

**Comment by xvrl** [comment]
https://github.com/druid-io/druid/pull/1949

**Comment by xvrl** [comment]
fixed by #1949
