### ISSUE TITLE
Segments path is not consistent between real-time and batch in S3

### ISSUE THREAD

**Issue by spektom** [druid-io/druid#2083]
When looking at the deep storage (S3 in our case), I've found that real-time segments are stored in these paths:

      <s3-path-prefix>/<data source name>/<interval>

While hadoop indexer segments are stored under:

      <s3-path-prefix>/<data source name>/<data source name>/<interval>

Note the duplicated data source name in path.

Is it a bug?

**Comment by xvrl** [comment]
I believe this is fixed for HDFS by #1702, not sure about S3. @himanshug ?
