### ISSUE TITLE
Make hadoop delta ingestion retries easier

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#2099]
Hadoop delta ingestion retrying is problematic because it's not idempotent. It's possible for the job to push segments and insert them into the metadata store, but then fail after that for some reason (maybe some hardware died at an inopportune time). Currently, users desiring to retry delta ingestion tasks need to deal with this outside of Druid - possibly by checking the metadata store before retrying.

It would be good for Druid to help with automating this or some other method of doing retries.

**Comment by himanshug** [comment]
user can see the segments information before/after the task using the http endpoint `/datasources/{dataSourceName}/segments` and make the decision on retrying or not based on that ? they might have to wait for `druid.manager.segments.pollDuration` after the task finishes (with success/failure).

**Comment by gianm** [comment]
@himanshug that seems a bit brittle, as the coordinator could be down / slow (for a while our coordinators actually took longer than `druid.manager.segments.pollDuration` to poll the metadata store, due to poor tuning…)

I think this feature will be hard to use unless we can make it idempotent.

Maybe we can make it idempotent by rather than having people provide "intervals", instead they provide specific segments. They could potentially get these from checking for the currently active segments.

**Comment by himanshug** [comment]
@gianm hmm... so the flow would be like..
1) user sends overlord request to get list of DataSegments for desired interval
2) then sends the hadoopIndexTask and puts the above list in the task json
then even if user retries same task it would stay idempotent ?

also, I think user will have to provide interval as well so that we can do the VersionedIntervalTimeline stuff to create WindowedDataSegment, I don't think user can take the pain of doing all that.

**Comment by himanshug** [comment]
@gianm implementing that idea is trivial, see https://github.com/druid-io/druid/pull/2109 . let me know if that sounds OK.

**Comment by gianm** [comment]
@himanshug sorry for taking so long to reply, this approach in #2109 does sound good to me though.

Is there an existing endpoint on the overlord/coordinator that gets the list of segments from the metadata store for an interval? Or do we need to add that?

**Comment by himanshug** [comment]
@gianm there is SegmentsListUsed task action that returns list of used segments. overlord accepts `POST /druid/indexer/v1/action` so user can do it. However, should I wrap it inside a `Task`, it appears that task action is druid internal communication medium. so, i think, we should create a brand new endpoint then?

**Comment by gianm** [comment]
@himanshug I think a new endpoint makes sense if it doesn't already exist (I don't see one) as yeah, the task actions are meant to be internal.
