### ISSUE TITLE
Non-deterministic io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#2114]
Running io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.66 sec - in io.druid.server.namespace.cache.NamespaceExtractionCacheManagerExecutorsTest
Running io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest
Tests run: 20, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.924 sec <<< FAILURE! - in io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest
testReverseFunction[[.gz]:[io.druid.server.namespace.cache.OffHeapNamespaceExtractionCacheManager]](io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest)  Time elapsed: 0.016 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:621)
	at org.junit.Assert.assertNotNull(Assert.java:631)
	at io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest.testReverseFunction(URIExtractionNamespaceFunctionFactoryTest.java:325)

**Comment by b-slim** [comment]
@drcrallen this should fix it https://github.com/druid-io/druid/pull/2110/files

**Comment by fjy** [comment]
Duplicated bt #2115
