### ISSUE TITLE
io.druid.server.namespace.cache.JDBCExtractionNamespaceTest can stall builds

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#2120]
Running io.druid.server.namespace.cache.JDBCExtractionNamespaceTest
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated

**Comment by fjy** [comment]
I've seen this same problem occur on multiple test runs

**Comment by drcrallen** [comment]
@fjy can you link to any of them?

**Comment by fjy** [comment]
https://travis-ci.org/druid-io/druid/jobs/97624306

https://travis-ci.org/druid-io/druid/jobs/96045200

**Comment by drcrallen** [comment]
https://travis-ci.org/druid-io/druid/jobs/98252322

**Comment by drcrallen** [comment]
each individual test has a 10s timeout, and there should be 8 of them, meaning less than 2 minutes worth of tests if each surpasses its maximum timeout. So that leaves me to believe there's a `@Before` or `@After` problem. So I'm checking that out next
