### ISSUE TITLE
Add on array / set query aggregators on dimension columns.

### ISSUE THREAD

**Issue by steventranjs** [druid-io/druid#2166]
Currently, druid only support numeric aggregators like sum, min, max... on METRIC columns.

It would be great if druid can support (array / set) aggregators on DIMENSION columns, for example:
- With: "dimensions": ["city": String, "device_type": String], "metrics": ["number_of_used": longSum]
1. List the top 10 cities by total device usage? => groupBy "city" and orderBy "number_of_used"
2. For each city, find all distinct device name? => ???

**Comment by fjy** [comment]
@steventranjs do you mean something similar to what Pivot (https://github.com/implydata/pivot) does with its nested tables?

**Comment by steventranjs** [comment]
Hi @fjy yes, this is exactly what I want. So for now, I'll temporary use pivot instead. Hope this would be implemented soon. Thanks.
