### ISSUE TITLE
BUG: thetaSketch metrics column cannot be included in "select" query

### ISSUE THREAD

**Issue by hamlet-lee** [druid-io/druid#2178]
When ingestion
```
{
       "type": "thetaSketch",
       "name": "userid_sketch",
       "fieldName": "userid"
}
```

when you issue such query

```
{
    "queryType": "select",
    "dataSource": "mysource",
    "granularity": "all",
    "dimensions": [
        "my_dimension"
    ],
    "metrics": [
        "userid_sketch"  #not allowed
    ],
    "intervals": [
        "2015-12-26T00:00:00+08:00/2015-12-31T00:00:00+08:00"
    ],
    "pagingSpec": {
        "pagingIdentifiers": {},
        "threshold": 100
    }
}
```

you get error message like:
com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input: expected close marker for OBJECT (from [Source: java.io.SequenceInputStream@9d71041; line: -1, column: -1]) at [Source: java.io.SequenceInputStream@9d71041; line: -1, column: 2410] (through reference chain: java.util.ArrayList[0])

**Comment by fjy** [comment]
@hamlet-lee I'm not sure if complex metrics ever worked with the select query...

@himanshug have you tried this case before?

**Comment by himanshug** [comment]
@fjy i haven't tried it but it looks like select queries probably doesn't work with complex types, @hamlet-lee does this work for hyperUnique ?

**Comment by hamlet-lee** [comment]
select works for hyperUnique, which produces string like: AQAAAQAAAAFKAQ==
select also works for histogram fold, which produces string like: 	/5wBRQ6AAA==
both works on 0.8.3-rc2

**Comment by hamlet-lee** [comment]
@himanshug the patch at https://github.com/himanshug/druid/pull/2 also can fix this bug.
