### ISSUE TITLE
Transient failure on io.druid.indexing.overlord.TaskLifecycleTest testRealtimeIndexTaskFailure

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#2180]
io.druid.indexing.overlord.TaskLifecycleTest
testRealtimeIndexTaskFailure[taskStorageType=MetadataTaskStorage](io.druid.indexing.overlord.TaskLifecycleTest)  Time elapsed: 60.644 sec  <<< ERROR!
java.lang.Exception: test timed out after 60000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at io.druid.indexing.overlord.TaskLifecycleTest.testRealtimeIndexTaskFailure(TaskLifecycleTest.java:941)

**Comment by fjy** [comment]
@pjain1 Please take a look and resolve this problem. This is high priority.

**Comment by fjy** [comment]
I was able to reproduce this locally sometimes where an exception in the persist thread kills it and causes the task storage to try and sync indefinitely

**Comment by pjain1** [comment]
@fjy sorry I could not look into it because I am traveling as I was on leave for past few weeks. I just glanced over your fix and that looks good to me.
