### ISSUE TITLE
drop rules don't make much sense

### ISSUE THREAD

**Issue by sixtus** [druid-io/druid#220]
It's really hard to grasp dropByPeriod being inclusive not exclusive. To understand it, you have to be aware of rule orders.

Moreover, the time parameter doesn't make any sense (the examples having 100 years proofs the point).

It would probably make more sense to just have a "dropSegments" rule w/o any parameter, bonus points for forcing it to the end of the rule list.

Once you got there, just unloading everything that's not explicitly loaded and totally getting rid of the drop* rules makes even more sense.

**Comment by fjy** [comment]
I am closing this issue as I believe dropForever rules have solved this problem. We should open a separate issue to discuss not needing explicit drop rules.
