### ISSUE TITLE
Still, complement of roaring bitmap does not work correctly

### ISSUE THREAD

**Issue by sirpkt** [druid-io/druid#2218]
I said complement bug of roaring bitmap was fixed at RoaringBitmap 0.5.13 in #2175 
but sorry it is wrong information. 
I found that flip() of ImmutableRoaringBitmap still does not work correctly with 0.5.13,
and results in incorrect result of NotFilter
(however, MutableRoaringBitmap and RoaringBitmap work fine).

This bug is fixed with the newest version of RoaringBitmap(0.5.16).
So, we need
- new release of bytebuffer-collections whose pom.xml depends on RoaringBitmap 0.5.16
- updated Druid pom.xml that depends on the new release

**Comment by fjy** [comment]
@drcrallen @xvrl @nishantmonu51 we need another bytebuffer collections to be released
