### ISSUE TITLE
Segments parent directory not removed on permanent deletion with NFS deep-storage

### ISSUE THREAD

**Issue by msspadoni** [druid-io/druid#2272]
I have setup a Druid cluster on five KVM (CentOs 6.5-based) on our private Joyent cloud.
The cluster executse the Coordinator, Historical, Overlord, Broker and Realtime node each one on a separate VM, whilst the middleManager is on the same VM of the Overlord (even if configured with druid.indexer.runner.type=remote).
Deep storage is configured on NFS (provided on NetApp appliance).
Using the "old coordinator console", I am able to disable a datasource and then to permanently delete its segments; however parent directories of removed segments are not removed from the deep storage.
As an example, if I have this segment-related file:
/NFS/sso024/2015-08-13T00\:00\:00.000Z_2015-08-14T00\:00\:00.000Z/2016-01-13T14\:30\:02.644Z/0/index.zip
after the deletion I have:
/NFS/sso024/2015-08-13T00\:00\:00.000Z_2015-08-14T00\:00\:00.000Z/2016-01-13T14\:30\:02.644Z/
Notice that killing tasks are marked "SUCCESSFULL" in the Overlord Web UI.

**Comment by drcrallen** [comment]
@himanshug do you know if this behavior exists for the HDFS deep storage as well?

**Comment by drcrallen** [comment]
Thanks for the detailed report @msspadoni !

**Comment by himanshug** [comment]
@drcrallen  we fixed this for hdfs in https://github.com/druid-io/druid/pull/1659/ , same needs to be done to LocalDataSegmentKiller i guess. will send a PR to fix that.
