### ISSUE TITLE
[Feature] Hadoop Ingestion with Parquet Support

### ISSUE THREAD

**Issue by du00cs** [druid-io/druid#2333]
Parquet format  is efficient with less storage and faster query and we use heavily in our data center. I am wondering about how to do ingestion directly from parquet file ( offline hadoop ingestion only).

I found this discussion [Hadoop Indexer and non-text batch ingestion (parquet)
](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/druid-user/parquet/druid-user/-a1BPJQ_9HY/cWGCZ7uDrCIJ). Refer to the implementation of Avro Ingestion, maybe it is not too hard ( with some limitation on data structure ) to add this feature.

@fjy any idea? If the feature is needed, I am also happy to work on that~

**Comment by xvrl** [comment]
@du00cs it should not be too hard to implement using the [parquet input format](https://github.com/Parquet/parquet-mr/blob/master/parquet-hadoop/src/main/java/parquet/hadoop/ParquetInputFormat.java). If you want to take a stab at implementing an extension, please do, I think it would be a great contribution!

**Comment by fjy** [comment]
@du00cs the best place to start is to look at how the Avro extension was implemented: 
https://github.com/druid-io/druid/tree/master/extensions/avro-extensions

**Comment by fjy** [comment]
@du00cs Definitely think this is useful

**Comment by himanshug** [comment]
https://github.com/Parquet/parquet-mr/blob/master/parquet-hadoop/src/main/java/parquet/hadoop/ParquetInputFormat.java is `ParquetInputFormat<T>` , I think you can use that InputFormat as it is and write an InputRowParser that parses T in druid InputRow . That should be enough.

**Comment by du00cs** [comment]
Thanks for so many tips ~

**Comment by fjy** [comment]
Closed by #2369
