### ISSUE TITLE
producing v9 regardless of the buildV9Directly option does not seem right.

### ISSUE THREAD

**Issue by CHOIJAEHONG1** [druid-io/druid#2350]
When the `buildV9Directly` is set to `false`, Druid is supposed to build a v8 using IndexMerger. However, IndexMerger produces a v9 no matter what value of `buildV9Directly` is set, which might not be indented . This is because although IndexMerger produce a v8 at first but end up with converting it into v9 using `convertV8toV9` at the end of `IndexMerger::makeIndexFiles()`.
This issue might have something to do with #2290 I guess.

IndexMerger.java
```
  protected File makeIndexFiles(
      final List<IndexableAdapter> indexes,
      final AggregatorFactory[] metricAggs,
      final File outDir,
      final ProgressIndicator progress,
      final List<String> mergedDimensions,
      final List<String> mergedMetrics,
      final Function<ArrayList<Iterable<Rowboat>>, Iterable<Rowboat>> rowMergerFn,
      final IndexSpec indexSpec
  ) throws IOException
.....
....
....
    createIndexDrdFile(
        IndexIO.V8_VERSION,
        v8OutDir,
        GenericIndexed.fromIterable(mergedDimensions, GenericIndexed.STRING_STRATEGY),
        GenericIndexed.fromIterable(mergedMetrics, GenericIndexed.STRING_STRATEGY),
        dataInterval,
        indexSpec.getBitmapSerdeFactory()
    );

    indexIO.getDefaultIndexIOHandler().convertV8toV9(v8OutDir, outDir, indexSpec);
    FileUtils.deleteDirectory(v8OutDir);

    return outDir;
  }
```

**Comment by fjy** [comment]
@CHOIJAEHONG1 This is the intended behavior. Segments in Druid are always v9 before they can be queried.

**Comment by CHOIJAEHONG1** [comment]
I thought that when `buildV9Directly` is set to false, v8 is to be built and convert it into v9 manually using a convert task.

By the way, I found this trying to build a v8 segment to test this code below which appears not to work when a metric is a type of LONG. I was able to produce a v8 segment and got the result of all zeros querying on it. Of source this version of segment would be destined to disappear I guess.
https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/segment/IndexIO.java#L952

**Comment by CHOIJAEHONG1** [comment]
I will open a separate PR for the issue related to LONG type.

**Comment by gianm** [comment]
@CHOIJAEHONG1 the intended behavior of `buildV9Directly` set to false is that segments are built as v8 first but then immediately converted to v9 before being published. So either way you would get a v9 segment, the only difference is how it is built.
