### ISSUE TITLE
Druid docs need best practices for handling time zones

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#2356]
Documentation on druid.io needs to have best practices around timezones. Currently all the docs really say is to set `user.timezone` to UTC, but don't really give much other information if you don't want to use UTC in queries or query results. Examples of how to issue queries in other timezones and how to ensure results return in the timezone you desire would be helpful.

**Comment by du00cs** [comment]
Ingestion with UTC is nice, what you care about maybe more likely related to query side. [Granularity Doc](http://druid.io/docs/latest/querying/granularities.html) mentioned that 
```json
   "granularity":{"type": "period", "period": "P1D", "timeZone": "America/Los_Angeles", "origin": "1970-01-01T20:30:00-08:00"}
```

**Comment by PanYifeng** [comment]
I have some problem about timezone. I am in China and I want to set my timezone to Standard Time in China.  I tried many, such as "Asian/Beijing", "Asian/Shanghai" and "Asian/Chongqing". But none of them work as expected. Who can tell me what's wrong and list the valid timezone values?
Any ideas would be appreciated!

**Comment by gianm** [comment]
@PanYifeng, there is a list on wikipedia here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones. An offset should also work, like "+08:00" or "-03:00".

**Comment by PanYifeng** [comment]
@gianm Thank you! On referring to List_of_tz_database_time_zones, I found I had made a spelling mistake. As I replaced "Asian/Shanghai" with "Asia/Shanghai", the problem was solved.
