### ISSUE TITLE
HadoopTask does not load extension jars into isolated classpath

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#2428]
HadoopTask's creation of the isolated classloader creation finds the extension jar URLs but does not actually use them in the classloader. It instead simply includes them as dependent jars.

As such any extension classes used in runTask will fail since they are not in the isolated classloader.

**Comment by gianm** [comment]
Do you have an example of what you mean here?

Also was this busted in 0.8.x too or just master?

**Comment by drcrallen** [comment]
@gianm it affects the spark batch indexer. I'm not certain if it is a regression or not.
