### ISSUE TITLE
RemoteTaskRunner blocks assignment of tasks on a single slow node

### ISSUE THREAD

**Issue by cheddar** [druid-io/druid#2497]
After assigning a task, the RemoteTaskRunner appears to wait for that task to be acknowledged before trying to assign another one, even if it is to a different node.

We had a production issue today where one of our middle managers was having a bad day and not successfully spinning up tasks.  This, quite surprisingly resulted in the overlord totally blocking waiting for that one guy to finish assigning his task even though there were other replicas of the task that could've been assigned and forward progress could've been made.

Specifically, we eventually saw the error from this line of code

https://github.com/druid-io/druid/blob/91f23583f5f624c60c1c099c4fa5b7d120e0bb37/indexing-service/src/main/java/io/druid/indexing/overlord/RemoteTaskRunner.java#L713

**Comment by drcrallen** [comment]
Should that be an alert level msg then?

**Comment by cheddar** [comment]
Perhaps.  What I'm commenting on is more that I think the overlord shouldn't totally block just because one of the MM's is acting up.  The comment in the code above that seems to indicate that such is expected behavior, but I don't think we should settle for that.

**Comment by drcrallen** [comment]
@cheddar it should not be acceptable for the managing thingy to get caught when one thing it manages gets caught :)

I was typing fast and didn't mean it that way.

**Comment by cheddar** [comment]
Ah, ok.  Yes, the message should likely *also* be an alert message :).

**Comment by himanshug** [comment]
currently RTR uses SingleThreadExecutor that cause overlord to be blocked waiting for a worker to acknowledge the task assigned. We can use a multiple thread executor instead and keep a set of workers (who have not acknowledged at least one task) and not consider them in the pool of workers to which a new task can be assigned.
then if one worker is down, only one task will fail but overlord will continue to make progress with other tasks.

@gianm @drcrallen @cheddar how does that sound?

**Comment by gianm** [comment]
@himanshug that sounds reasonable, it should still accomplish the goal of avoiding flooding a worker with tasks.

**Comment by himanshug** [comment]
ok, i will soon make that change in a PR then.
