### ISSUE TITLE
Half-ingested events are possible when exceptions are caught on IncrementalIndex.add

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#2510]
Pre-0.8.2, and post #2505, RealtimeManager catches ParseExceptions on `plumber.add`, increments the unparseable counter, and continues. Post #2505 RealtimeIndexTask does too. This can cause half-ingested events, because the ParseExceptions get thrown while the index is updating aggregators in its facts map. In this case:

- other aggregators are not updated,
- but a row does end up in the facts table (with potentially some aggregators updated and some not),
- and the event is counted "unparseable" rather than "processed" which is strange as now the "processed" count does not match the number of events actually added to the index.

One example of when a ParseException can get thrown is if you have a longSum aggregator reading from a field in the InputRow that cannot be parsed as a number. (& other things like this)

Possible better behaviors,

1. abort realtime processing, like happened between 0.8.2 and #2505. Folks might have a hard time with this one, though, if they aren't validating their inputs before passing them to Druid.
2. don't include the event in the index at all, and count it "unparseable". But this might be tough to implement given that when this exception is thrown, the facts table has already been partially updated.
3. keep the same indexing behavior, but count the event as "processed" instead of "unparseable"
4. catch ParseException on `agg.aggregate()` in OnheapIncrementalIndex, and move on to the next aggregator, and count the event as "processed".

potential risk with options 3 & 4: inconsistent aggregator state, if any aggregator out there is implemented such that its state cannot be relied on after it encounters an exception during `aggregate`.

**Comment by himanshug** [comment]
so far (1) hasn't been a pain, so reverting to that behavior would be OK for 0.9.0.

(2) would be ideal
(3) and (4) are effectively the same other than whether the event is counted as processed or unparseable, but the rows has been added with a subset of aggregators updated. that means data inconsistency. it is probably ok for some user analytics use cases where some errors in numbers is tolerable.

**Comment by himanshug** [comment]
on second thought (1) would be a major pain if/when hit, (4) is probably the best for now if not (2).

**Comment by fjy** [comment]
I prefer (2), but in the interest of moving forward if it takes too long to implement, (4) is cool

**Comment by gianm** [comment]
@himanshug @fjy do guys you see a straight forward way to do (2)? I do not see one, and agree (1) is a huge pain if hit, so I am leaning towards (4).

this would cause issues if any aggregators leave themselves in an inconsistent state after parse exceptions, I am not sure how likely this is although my guess is it is not very likely. as my guess is that most aggregators would parse input first and then do something with it.

**Comment by jon-wei** [comment]
@gianm What if you changed the Aggregator interface to allow:
- Peeking ahead at what the selector would return next
- Aggregating an arbitrary value passed in (not from selector) 

In addToFacts, you could pull all of the next selector values out and validate before facts.putIfAbsent is called

Then use the second aggregating function to feed in the previously read values to the aggs

**Comment by gianm** [comment]
@fjy @himanshug @jon-wei implemented (4) in #2519
