### ISSUE TITLE
Inconstancy / Typo in 0.9.0_rc1 API

### ISSUE THREAD

**Issue by vogievetsky** [druid-io/druid#2535]
The newly added parameters to `regex` extractionFn are inconsistent / contain a typo.

Notice these two examples from http://druid.io/docs/0.9.0-rc1/querying/dimensionspecs.html

```json
{
  "type" : "regex",
  "expr" : <regular_expression>,
  "replaceMissingValues" : true,
  "replaceMissingValuesWith" : "foobar"
}
```

and 

```json
{
  "type":"lookup",
  "lookup":{
    "type":"map",
    "map":{"foo":"bar", "baz":"bat"}
  },
  "retainMissingValue":false,
  "injective":false,
  "replaceMissingValueWith":"MISSING"
}
```

One has `retainMissingValue` and `replaceMissingValueWith` and the other has `replaceMissingValues` and `replaceMissingValuesWith`.

One set has 'Value' (singular) the other 'Value**s**' (plural). This extra 's' is inconsistent and super hard to see. I personally spent quite some time figuring out why my code did not work when using `regex` since I copy+pasted the `replaceMissingValueWith` from `lookup` assuming it would be the same.

Since RC1 is still RC I suggest the `replaceMissingValues` and `replaceMissingValuesWith` keys in 'regex' extractionFn be changed to `replaceMissingValue` and `replaceMissingValueWith`. I believe there is no reason to worry about back compat. as these keys never appeared in astable release yet but if back compat. is a problem `replaceMissingValue` and `replaceMissingValueWith` should still be added and the docs should be changed to use them instead.

Note: I am **not** concerned about the `retain` / `replace` inconstancy - it is necessary for back compatibility.

**Comment by gianm** [comment]
fixed by #2536
