### ISSUE TITLE
Docs for migrating extensions configs to 0.9.0 (including mysql)

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#2539]
The current 0.9.0 release notes (#2404) don't make it very clear how most users should migrate their configs when upgrading.

- it's not clear that the core extensions are generally bundled in the release tarball
- it's not clear what a reasonable value of `druid.extensions.directory` is, and whether you could use the release tarball's extensions directory for that
- it's not clear what "You only need to provide the name of the extension in the loadList." means— an example of a before/after migration would be good
- it's not clear how to get the mysql extension, as it is _not_ part of the tarball and will no longer automatically be downloaded at runtime.

As part of this we might want to update our release process to do something useful with the mysql tarball, like include a version number in it and upload it somewhere. or maybe decide we don't actually need a separate tarball after all… I'm not sure if we ever got a formal decision on that.

**Comment by guobingkun** [comment]
Sent #2553 and #2554. I also have updated the release notes, please check.
