### ISSUE TITLE
Peon port assignment/re-use

### ISSUE THREAD

**Issue by boneill42** [druid-io/druid#2545]
Peon port assignment appears to increase infinitely.    The `PortFinder` discovers new ports, which it returns to the `ForkingTaskRunner`, but those ports are never put back in the pool and re-used.

This becomes a big issue if you have security groups that restrict the connectivity between machines.  Any small port range is quickly exhausted and you are forced to open up connectivity to the entire machine.

We will attempt to patch, and submit from our fork.

**Comment by drcrallen** [comment]
@boneill42 patch #2543 already in for review, fyi

**Comment by drcrallen** [comment]
@boneill42 I had filed the patch before I saw the issue

**Comment by boneill42** [comment]
even better. =)

**Comment by drcrallen** [comment]
ported to 0.9.0 in https://github.com/druid-io/druid/pull/2547
