### ISSUE TITLE
Configuring 100% accuracy

### ISSUE THREAD

**Issue by mehdi-cit** [druid-io/druid#2628]
Hello,
I'm totally new to druid. Actually i'm just investigating whether we can/should use it for the company I work for.
Our requirements are for absolute accuracy. We'd rather have our apps crash then return anything that is not 100% accurate/right and "precise".
Is it possible to force druid to be 100% accurate. We can live with slower response times (less than 10 seconds though) in order to guarantee accuracy.
The data-sets we'd use druid on are about 10 gigs (well, theoretically they can get to few hundreds gigabytes in total). We can assume that our data can be made to be fully held in memory and in a single machine.
Sorry to ask here but I did not find this information elsewhere.

**Comment by fjy** [comment]
use groupBys instead of topNs is the big one, although for topNs, if you issue a top 1000 query, the first 900 or so elements are going to be 100% accurate most likely

**Comment by gianm** [comment]
"100% accurate most likely" is kind of a funny statement :)

You should avoid these approximate features if you need 100% guaranteed accuracy:

- topN queries
- cardinality, approxHistogram, hyperUnique aggregators

These features are exact:

- groupBy, timeseries queries
- *Sum, *Max, *Min, count aggregators

Although keep in mind that many computations in Druid are floating-point, and depending on how serious your accuracy needs are, it may matter to you than even our exact algorithms may be using floating-point numbers.

Closing this issue - if you have further questions, please use the mailing list (https://groups.google.com/forum/#!forum/druid-user).
