### ISSUE TITLE
new search count field documented to be off by default, but is on

### ISSUE THREAD

**Issue by rasahner** [druid-io/druid#2662]
PR https://github.com/druid-io/druid/pull/2260 added a count for each value to search query returns.  The documentation says that there's a computeCount property in the query spec that is off by default.  But I don't see that property implemented anywhere in the code, and the count is on by default (making some of the integration tests fail).  @navis, do you think we should just remove that from the documentation and let the count be on by default?  Or, should we truly make it be a query parameter and let it be off by default?  (It's easy enough to adjust the integration tests if it will always be on; I can do that.)

**Comment by navis** [comment]
@rasahner My bad. The option `computeCount` was removed addressing comments. I should have removed it from document.
