### ISSUE TITLE
Different results from broker vs historical node query

### ISSUE THREAD

**Issue by waltonseymour** [druid-io/druid#2773]
I receive different results from a simple topN query:

```JSON
{
    "queryType": "topN",
    "dataSource": "citibike",
    "granularity": "all",
    "dimension": "start station name",
    "metric": "count",
    "threshold": 5,
    "aggregations": [
        {"type": "count", "name": "count"},
        {"type": "longSum", "fieldName": "tripduration", "name": "total_time"}
    ],
    "intervals": [
    "2015-11-01T00:00:00.000/2015-12-01T00:00:00.000"
    ]
}
```

When I hit the historical node I get the incorrect count values:
```JSON
[ {
  "timestamp" : "2015-11-01T00:00:00.000Z",
  "result" : [ {
    "count" : 10061,
    "total_time" : 8854418,
    "start station name" : "Pershing Square North"
  }, {
    "count" : 8571,
    "total_time" : 6359995,
    "start station name" : "Lafayette St & E 8 St"
  }, {
    "count" : 8039,
    "total_time" : 6356663,
    "start station name" : "W 21 St & 6 Ave"
  }, {
    "count" : 5785,
    "total_time" : 5453625,
    "start station name" : "E 17 St & Broadway"
  }, {
    "count" : 4779,
    "total_time" : 4343114,
    "start station name" : "Penn Station Valet"
  } ]
} ]
```
But when I hit the broker node, I get the correct values of:
```JSON
[ {
  "timestamp" : "2015-11-01T00:00:00.000Z",
  "result" : [ {
    "count" : 11267,
    "total_time" : 10331775,
    "start station name" : "Pershing Square North"
  }, {
    "count" : 8810,
    "total_time" : 6627403,
    "start station name" : "Lafayette St & E 8 St"
  }, {
    "count" : 8268,
    "total_time" : 6693397,
    "start station name" : "W 21 St & 6 Ave"
  }, {
    "count" : 7740,
    "total_time" : 6797656,
    "start station name" : "E 17 St & Broadway"
  }, {
    "count" : 7175,
    "total_time" : 6870773,
    "start station name" : "Broadway & E 14 St"
  } ]
} ]
```
Is there any reason these should differ? I thought the broker simply delegated calls to historical and realtime nodes and merged the results.

**Comment by xvrl** [comment]
@waltonseymour this would only be true if you have a single historical node, and no realtime nodes or realtime tasks. How many nodes and what kind do you have?

**Comment by waltonseymour** [comment]
I'm running it locally, so yes there's only a single historical with no realtime.
Any reason that behavior should be expected?

**Comment by xvrl** [comment]
@waltonseymour this is expected for topN. The broker will rewrite the query to be at least top-1000 from each segment before merging and pruning results. When you query the historical directly that is not the case, instead it's taking the top-5 from each segment, which is going to be very inaccurate. Try setting the top-N threshold to 1000 on the historical, the first 5 results should then match.

**Comment by waltonseymour** [comment]
Ok, that makes sense thanks
