### ISSUE TITLE
Inconsistent null/empty str handling for multi-value/single-value dimensions in QueryableIndexStorageAdapter

### ISSUE THREAD

**Issue by jon-wei** [druid-io/druid#2776]
In the Cursor returned by QueryableIndexStorageAdapter, the DimensionSelectors created from the Cursor have different null handling behavior for multi-value and single-value dimensions.

In the implementation of DimensionSelector.lookupName(id):
- For multi-value dimensions, Strings.nullToEmpty() is called on the value before it is returned or passed to the extractionFn.
- For single-value dimensions, there is no null->empty str conversion.

DimensionSelectors originating from an IncrementalIndex do not perform the null->empty str conversion either.

**Comment by xvrl** [comment]
@jon-wei @gianm can we put together a larger issue to aggregate all the null issues you've been seeing lately? It might make sense to have a more comprehensive view of all the issues to help figure out what needs to be done.

**Comment by jon-wei** [comment]
@xvrl I've opened an issue here: https://github.com/druid-io/druid/issues/2778

**Comment by jon-wei** [comment]
Fixed in #2690
