### ISSUE TITLE
Druid - 0.9.0 - Link to Configuration Logging page is broken

### ISSUE THREAD

**Issue by skilledmonster** [druid-io/druid#2838]
Links to the following pages are broken:
Configuration Logging - http://druid.io/docs/0.9.0/development/configuration/logging.html
Production Cluster Configuration - http://druid.io/docs/0.9.0/development/configuration/production-cluster.html
Production Hadoop Configuration - http://druid.io/docs/0.9.0/development/configuration/hadoop.html
Production Zookeeper Configuration - http://druid.io/docs/0.9.0/development/configuration/zookeeper.html

**Comment by drcrallen** [comment]
`development` has been removed from the url for the 0.9.0 docs.

**Comment by drcrallen** [comment]
Not saying this is good or bad :), just stating what the change is.

**Comment by fjy** [comment]
@skilledmonster Where are you getting these links from?

**Comment by fjy** [comment]
@skilledmonster @drcrallen 
These links don't even work in 0.8.3 and I'm sure have never worked...
e.g. http://druid.io/docs/0.8.3/development/configuration/logging.html doesn't exist
