### ISSUE TITLE
Contextual timestamp parsing

### ISSUE THREAD

**Issue by javasoze** [druid-io/druid#2866]
Currently when we parse time from a dateString using a DateFormat, we treat each row individually using DateFormat.parse(), which is a relatively expensive operation.

In many scenarios, especially with realtime under heavy load, such as log processing, the granularity of time is seconds (normally you don't log an event for process every ms), which makes the records being sent load be in batches with same timestamp.

So with that context, it is possible to make the parsing operation a candidate for optimization by remembering the last time string parsed along with its parsed result.

For details, please follow [this thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/druid-development/S4naG6r-oXM/mxyZ3M9tBgAJ)

**Comment by javasoze** [comment]
Pull request: [https://github.com/druid-io/druid/pull/2867](https://github.com/druid-io/druid/pull/2867)

**Comment by gianm** [comment]
fixed in #2867
