### ISSUE TITLE
Graphite emitter should not block when queue is full

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#2868]
Currently the Graphite emitter blocks up to 1 sec if the queue is full. If communication to Graphite is disrupted then this will potentially block up query threads, etc, throughout the Druid process. To avoid this it would be better to drop events immediately on queue full rather than waiting for space to free up.

It'd also be nicer for the logs to only log an error periodically rather than on every dropped metric.

Generally I'm thinking something more like the implementation in `HttpPostEmitter.emit`.

**Comment by b-slim** [comment]
Ok will look into that

**Comment by b-slim** [comment]
@gianm are you guys using this ? should we move to core ?

**Comment by gianm** [comment]
@b-slim we aren't using this, I was just looking at the code when writing https://groups.google.com/d/msg/druid-user/oLFcigBYN9c/ypjSwgGhBwAJ and saw some room for improvement.

**Comment by gianm** [comment]
Fixed by #2869
