### ISSUE TITLE
duplicate detection in realtime nodes

### ISSUE THREAD

**Issue by pdeva** [druid-io/druid#2876]
Druid version used: 0.8.3

I noticed this while restarting one of my kafka replicas.

It seems the realtime node read a msg twice due to this and ended up aggregating it. We saw metrics everywhere doubled due to that.

Realtime nodes should check for duplicates. if entire row is exactly the same as previous, then discard it.

**Comment by gianm** [comment]
Hey @pdeva, this is out of scope for what realtime nodes are intended to do ("best effort" reads from an arbitrary streaming source).

But the new Kafka indexing service (http://druid.io/docs/latest/development/extensions-core/kafka-ingestion.html) does handle this in its own way, via transaction checks based on Kafka message offsets. You could take a look at that for stricter behavioral guarantees when reading from Kafka.
