### ISSUE TITLE
pull-deps fails when not using --clean flag

### ISSUE THREAD

**Issue by brwebb** [druid-io/druid#2885]
`--clean` Will remove the extensions directory
If you call pull-deps without the flag, it should attempt to use the existing extensions directory without removing any existing extensions. However, in this case an exception is thrown:

```
Exception in thread "main" com.metamx.common.ISE: Unable to create extensions directory at [/usr/local/druid-0.9.0/extensions]
	at io.druid.cli.PullDependencies.createRootExtensionsDirectory(PullDependencies.java:453)
	at io.druid.cli.PullDependencies.run(PullDependencies.java:223)
	at io.druid.cli.Main.main(Main.java:105)
```

The problem is that the code will always attempt to create the extensions directory:
https://github.com/druid-io/druid/blob/master/services/src/main/java/io/druid/cli/PullDependencies.java#L223

```Java
    createRootExtensionsDirectory(extensionsDir);
    createRootExtensionsDirectory(hadoopDependenciesDir);
```

And `createRootExtensoinsDirectory()` will throw an exception if the directory already exists. This is because `mkdirs()` returns false if the directory already exists.
https://github.com/druid-io/druid/blob/master/services/src/main/java/io/druid/cli/PullDependencies.java#L451
```Java
    if (!atLocation.mkdirs()) {
      throw new ISE(
          String.format(
              "Unable to create extensions directory at [%s]",
              atLocation.getAbsolutePath()
          )
      );
    }
```

**Comment by fjy** [comment]
The workaround is documented here FWIW: http://imply.io/docs/latest/extensions

**Comment by guobingkun** [comment]
Thanks for reporting the issue @brwebb . It's unnecessary to crash the program if there is no conflicting extensions.

**Comment by drcrallen** [comment]
@fjy can that example be added to the official druid docs?

**Comment by zzl0** [comment]
@fjy @drcrallen I met this problem too, is it a feature ?!

**Comment by fjy** [comment]
@drcrallen yes we haven't ported it yet. We actually need to rewrite all the extension installation docs for Druid

**Comment by drcrallen** [comment]
@zzl0 no, it is a limitation of the existing pull-deps tool. Overcoming this limitation for smarter pull-deps would be a feature.

**Comment by zzl0** [comment]
@drcrallen thanks for your explanation
