### ISSUE TITLE
Can I work with multiple timesamps

### ISSUE THREAD

**Issue by MrMauricioLeite** [druid-io/druid#2895]
Hi guys, I'm new here and I'm sorry if this question is a little dumb but, having the sharding based on a timestamp column that is ingested by druid, how can I work with a dataset that have something like:

created_timestamp
paid_timestamp
delivery_timestamp
...
(other dimensions)
...
(my metrics)

**Comment by dclim** [comment]
@MrMauricioLeite Hi Mauricio, we have a Google Druid User group for these types of questions, could you please repost this question there? : https://groups.google.com/forum/#!forum/druid-user. This will help keep issues separate from inquiries and have the question available for future users.

**Comment by MrMauricioLeite** [comment]
sure, sorry.
