### ISSUE TITLE
Druid Indexer Console - Duration is always 0 under Completed Tasks

### ISSUE THREAD

**Issue by skilledmonster** [druid-io/druid#2958]
Task Duration for Completed Tasks is always shown as 0. Duration is probably not saved to Meta Storage correctly.

![task duration](https://cloud.githubusercontent.com/assets/2034585/15222713/0592958e-183f-11e6-92cb-962e4ab06569.png)

**Comment by drcrallen** [comment]
This is fixed under 0.9.1 . Here's a screenshot I just took from our cluster running master:
![screen shot 2016-05-12 at 9 49 02 am](https://cloud.githubusercontent.com/assets/8213081/15222951/d9fe628a-1826-11e6-9100-b2475490d0a3.png)

**Comment by drcrallen** [comment]
Closing because the code is already in.
