### ISSUE TITLE
Multi-valued Dimension via API

### ISSUE THREAD

**Issue by valenpo** [druid-io/druid#2970]
Hi, all. 

Is it possible some how put multivalued dimension to segment via API? I read it is possible to use multi-value dimensions. 

I'm using MapBasedInputRow and put for multi-value dimension List<String> of values, but such information are not saved on segment. 

Any clue? 

Regards,
Valentin.

**Comment by fjy** [comment]
@valenpo If you have a value in your data of the form "key":["val1","val2"], druid will automatically pick it up as a multi val dimension

**Comment by fjy** [comment]
Please use https://groups.google.com/forum/#!forum/druid-user for usage questions.

**Comment by valenpo** [comment]
@fjy thanks. Will follow you recommendations.
