### ISSUE TITLE
Add "numeric" compare to queries and bound filter

### ISSUE THREAD

**Issue by vogievetsky** [druid-io/druid#2989]
The `alphaNumeric` compare is not actually suitable for numbers. In particular it does not work with negative numbers because it does not treat the "-" as part of the number (nor should it).

This makes topNs on dimensions that have negative numbers and bound filters with negative ranges fail.

Proposal: add a `numeric` compare to both the sortSpec of all queries and the `bounds` filter

### Broken bounds filter:

```javascript
{
  "type": "bound",
  "dimension": "deltaBucket100",
  "alphaNumeric": true,
  "lower": -300,
  "upper": 300
}
```

Wanted something that will work like so:

```javascript
{
  "type": "javascript",
  "dimension": "deltaBucket100",
  "function": "function(a) { a = Number(a); return -300 <= a && a <= 300; }"
}
```

### Problematic topN:

To repro see: https://github.com/implydata/datazoo which has the docker image that sets up the dataset that reproduces this query.

```javascript
{
  "queryType": "topN",
  "dataSource": "wikipedia",
  "intervals": "1000/3000",
  "granularity": "all",
  "dimension": {
    "type": "default",
    "dimension": "deltaBucket100",
    "outputName": "DeltaBucket100"
  },
  "aggregations": [
    {
      "name": "TotalEdits",
      "type": "doubleSum",
      "fieldName": "count"
    }
  ],
  "metric": {
    "type": "inverted",
    "metric": {
      "type": "alphaNumeric"
    }
  },
  "threshold": 10
}
```

Results in:

```javascript
[
  {
    "timestamp": "2015-09-12T00:46:00.000Z",
    "result": [
      {
        "TotalEdits": 1246,
        "DeltaBucket100": "-500"
      },
      {
        "TotalEdits": 1690,
        "DeltaBucket100": "-400"
      },
      {
        "TotalEdits": 2532,
        "DeltaBucket100": "-300"
      },
      {
        "TotalEdits": 6443,
        "DeltaBucket100": "-200"
      },
      {
        "TotalEdits": 55463,
        "DeltaBucket100": "-100"
      },
      {
        "TotalEdits": 1,
        "DeltaBucket100": "242100"
      },
      {
        "TotalEdits": 1,
        "DeltaBucket100": "232900"
      },
      {
        "TotalEdits": 1,
        "DeltaBucket100": "205800"
      },
      {
        "TotalEdits": 1,
        "DeltaBucket100": "199900"
      },
      {
        "TotalEdits": 1,
        "DeltaBucket100": "199800"
      }
    ]
  }
]
```

**Comment by gianm** [comment]
Sounds like we should probably leave the "alphanumeric" comparator untouched, but add a "numeric" comparator, and update the docs for bound, topN, and groupBy to clarify what the comparators do. Would also be nice to have some tests for the alphanumeric comparator, I don't see any right now.

**Comment by vogievetsky** [comment]
Yep, as @gianm said I did not suggest removing alphanumeric. It's cool. I just want something that would work for decimals and negatives

**Comment by vogievetsky** [comment]
I should also add that I think it makes sense for the boudns filter API to change from:

```json
{
  "...": "...",
  "alphaNumeric": true
}
```

to:

```json
{
  "...": "...",
  "compare": "lexicographic OR alphaNumeric OR numeric"
}
```

with `"alphaNumeric": true` translating to `"compare": "alphaNumeric"` for backwards compatibility

**Comment by gianm** [comment]
For color: the alphaNumeric comparator sorts `["-1", "-1.10", "-1.2", "-100", "-2", "0", "1", "1.10", "1.2", "2", "100"]` as `[0, 1, 1.2, 1.10, 2, 100, -1, -1.2, -1.10, -2, -100]`. This is what it does and that is fine (it's only supposed to work on natural numbers).

The numeric comparator should sort them as `[-100, -2, -1.2, -1.10, -1, 0, 1, 1.10, 1.2, 2, 100
]`.
