### ISSUE TITLE
ImmutableBitmap.get(int value) behaves differently for Concise and Roaring

### ISSUE THREAD

**Issue by jon-wei** [druid-io/druid#2997]
Suppose I have a bitmap with bits 0,4,9 set.

When using Concise-backed ImmutableBitmap, if I call `bitmap.get(9)`, I get an IndexOutOfBoundsException. 

The `get()` function seems to expect `get(2)`, if I want to read the value for bit 9, i.e., the `value` input is treated as a position within the ConciseSet's set of values [0,4,9], not as a bitmap position.

Also, given this behavior, if I have a Concise-backed ImmutableBitmap and I call get() in a loop from 0 to bitmap.size(), get(0) returns `false`, while the range from 1 to `bmp.size() - 1` returns `true` (0 should return `true` as well)

If I switch to Roaring-backed, `get()` works as expected, the input is treated as a bitmap position.

----

Nothing within Druid currently uses `ImmutableBitmap.get(int value)`, opening this issue for future reference.

**Comment by drcrallen** [comment]
This should probably go against https://github.com/metamx/bytebuffer-collections/

**Comment by jon-wei** [comment]
@drcrallen 

I'll close this then, the issue is now at:
https://github.com/metamx/bytebuffer-collections/issues/31
