### ISSUE TITLE
[Feature] Hadoop Ingestion with Orc Support

### ISSUE THREAD

**Issue by sirpkt** [druid-io/druid#3017]
Hadoop ingestion from parquet file is already supported in Druid #2333.
I think ingestion directly from orc file is also beneficial
because many people use Hive in their data center and Hive has better performance with Orc than Parquet.

To do so, I'm plan to make InputRowParser work on OrcStruct, which is from OrcRecordReader of OrcNewInputFormat.
One issue in implementing InputRowParser is that
even though Orc file has schema information in itself, I cannot retrieve that schema information from OrcStruct which is the only given to me in the above approach.

As an easy first step, I think a way that InputRowParser explicitly receives StructTypeInfo as a parameter and get schema information from that.

**Comment by fjy** [comment]
@sirpkt are you planning on doing this as an extension?

**Comment by sirpkt** [comment]
@fjy Yes. contrib extension like Parquet support #2333.

**Comment by nishantmonu51** [comment]
closing, fixed by #3019

**Comment by udayakumarp** [comment]
Is this done as an extension? Can you pls. more info on this? How to use this etc?

Thanks,
Uday.

**Comment by fjy** [comment]
@udayakumarp please read the documentation

**Comment by udayakumarp** [comment]
Thanks fjy - Can you pls. point me to the documentation (in GIT you mean?)

**Comment by udayakumarp** [comment]
Never mind! Got it - http://druid.io/docs/0.9.2-rc2/development/extensions-contrib/orc.html 

Thanks,
Uday.
