### ISSUE TITLE
Logging emitter is active when noop is set

### ISSUE THREAD

**Issue by l15k4** [druid-io/druid#3053]
Hey,

if I set `druid.emitter` to `nopp` I can still see logging emitter logs : 
```
com.metamx.emitter.core.LoggingEmitter ...
```

```
~/imply-1.2.1# cat conf/druid/_common/common.runtime.properties | grep emitter
druid.emitter=noop
druid.emitter.logging.logLevel=warn
druid.emitter.graphite.hostname=?????
druid.emitter.graphite.port=2004
druid.emitter.graphite.alertEmitters=["noop"]
druid.emitter.graphite.eventConverter={"type":"whiteList", "namespacePrefix": "druid", "ignoreHostname":false, "ignoreServiceName":false, "mapPath": "dist/druid/extensions/graphite-emitter/defaultWhiteListMap.json"}
druid.extensions.loadList=["druid-histogram", "druid-datasketches", "druid-s3-extensions", "graphite-emitter"]
```

I'm using the 1.2.1 implydata distribution. I use graphite in production but I want to disable emitter for testing and development ...

**Comment by drcrallen** [comment]
What service are you seeing the emitter logs on, and what version of druid is your imply distribution running?

**Comment by fjy** [comment]
0.9.0

**Comment by fjy** [comment]
Cany ou post your full common.runtime.properties? FWIW this post should be in the user groups https://groups.google.com/forum/#!forum/druid-user until we confirm it is an actual Druid issue

**Comment by gianm** [comment]
@l15k4 You might be running against the quickstart config in `conf-quickstart` rather than the clustered config in `conf`, could you double-check that?

**Comment by l15k4** [comment]
Ou my, sorry guys. After triple checking everything, it turns out that I really supplied quickstart conf instead of the modified one, sorry !!!
