### ISSUE TITLE
KafkaIndexTasks Stop Scheduling After Exception

### ISSUE THREAD

**Issue by drewdahlke** [druid-io/druid#3054]
Hey, I'm trying out druid .9.1's new KafkaIndexTask. It seemed to be working pumping out hourly segments to S3, but after 4hrs I got an IOException and everything ground to a halt (no new index tasks getting generated after that). Did I hit a bug/should the overlord just skip to the next hour if something goes south on a middle manager?

From the middle managers:
`
{"t": "2016-06-01T18:56:43.931+0000", "message": "Pushing task log /mnt/data/druid/task/index_kafka_imetrics_66b3064361431ee_gmoekdaj/log to: druid/analytics-druid-v3/v3/logs/middlemanager/index_kafka_imetrics_66b3064361431ee_gmoekdaj/log", "level": "INFO", "logger_name": "io.druid.storage.s3.S3TaskLogs", "thread_name": "forking-task-runner-1"}
{"t": "2016-06-01T18:56:44.175+0000", "message": "Exception caught during execution", "level": "INFO", "logger_name": "io.druid.indexing.overlord.ForkingTaskRunner", "thread_name": "forking-task-runner-0"}
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162) ~[?:1.7.0_75]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:280) ~[?:1.7.0_75]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334) ~[?:1.7.0_75]
	at java.io.FilterInputStream.read(FilterInputStream.java:107) ~[?:1.7.0_75]
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:175) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:432) [druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:219) [druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
{"t": "2016-06-01T18:56:44.180+0000", "message": "Removing task directory: /mnt/data/druid/task/index_kafka_imetrics_7f75267cb06b630_nehheoci", "level": "INFO", "logger_name": "io.druid.indexing.overlord.ForkingTaskRunner", "thread_name": "forking-task-runner-0"}
{"t": "2016-06-01T18:56:44.184+0000", "message": "Exception caught during execution", "level": "INFO", "logger_name": "io.druid.indexing.overlord.ForkingTaskRunner", "thread_name": "forking-task-runner-1"}
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162) ~[?:1.7.0_75]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:280) ~[?:1.7.0_75]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334) ~[?:1.7.0_75]
	at java.io.FilterInputStream.read(FilterInputStream.java:107) ~[?:1.7.0_75]
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:175) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:432) [druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at io.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:219) [druid-indexing-service-0.9.1-SNAPSHOT.jar:0.9.1-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
{"t": "2016-06-01T18:56:44.184+0000", "message": "Removing task directory: /mnt/data/druid/task/index_kafka_imetrics_66b3064361431ee_gmoekdaj", "level": "INFO", "logger_name": "io.druid.indexing.overlord.ForkingTaskRunner", "thread_name": "forking-task-runner-1"}
{"t": "2016-06-01T18:56:44.190+0000", "message": "Job's finished. Completed [index_kafka_imetrics_7f75267cb06b630_nehheoci] with status [FAILED]", "level": "INFO", "logger_name": "io.druid.indexing.worker.WorkerTaskMonitor", "thread_name": "WorkerTaskMonitor"}
{"t": "2016-06-01T18:56:44.196+0000", "message": "Job's finished. Completed [index_kafka_imetrics_66b3064361431ee_gmoekdaj] with status [FAILED]", "level": "INFO", "logger_name": "io.druid.indexing.worker.WorkerTaskMonitor", "thread_name": "WorkerTaskMonitor"}
`

Funny enough that log file druid/analytics-druid-v3/v3/logs/middlemanager/index_kafka_imetrics_66b3064361431ee_gmoekdaj/log made it into S3 just fine despite the exception. Nothing particularly interesting in it.

From the overlord

`
{"t": "2016-06-01T18:56:43.418+0000", "message": "Running scheduled cleanup for Worker[172.18.11.171:8091]", "level": "INFO", "logger_name": "io.druid.indexing.overlord.RemoteTaskRunner", "thread_name": "RemoteTaskRunner-Scheduled-Cleanup--0"}
{"t": "2016-06-01T18:56:43.431+0000", "message": "Failing task[index_kafka_imetrics_7f75267cb06b630_nehheoci]", "level": "INFO", "logger_name": "io.druid.indexing.overlord.RemoteTaskRunner", "thread_name": "RemoteTaskRunner-Scheduled-Cleanup--0"}
{"t": "2016-06-01T18:56:43.431+0000", "message": "Received FAILED status for task: index_kafka_imetrics_7f75267cb06b630_nehheoci", "level": "INFO", "logger_name": "io.druid.indexing.overlord.TaskQueue", "thread_name": "RemoteTaskRunner-Scheduled-Cleanup--0"}
`

**Comment by dclim** [comment]
@drewdahlke could you post more of the overlord logs? I don't see any activity from the supervisor in those logs so it's hard to decipher what's going on. The expected behavior is that a failed task should be replaced with another task by the supervisor shortly after the failure, and that task should start reading from where the previous task started. If you can post the supervisor spec there might be some hints in there as well.

**Comment by drewdahlke** [comment]
Sure thing

[overlord.txt](https://github.com/druid-io/druid/files/296014/overlord.txt)
[spec.txt](https://github.com/druid-io/druid/files/296013/spec.txt)

**Comment by drewdahlke** [comment]
Looking at the supervisor.d log I don't think the process crashed, just the task runner. I attached the middle manager log & a pic of the overlord console. I got two of those errors 

220144:{"t": "2016-06-01T18:56:44.175+0000", "message": "Exception caught during execution", "level": "INFO", "logger_name": "io.druid.indexing.overlord.ForkingTaskRunner", "thread_name": "forking-task-runner-0"}

Not seeing new ones created
'
mysql> select created_date from druid_tasks;
+--------------------------+
| created_date             |
+--------------------------+
| 2016-06-01T16:18:54.977Z |
| 2016-06-01T16:54:37.468Z |
| 2016-06-01T16:54:37.519Z |
| 2016-06-01T16:54:37.538Z |
| 2016-06-01T16:54:37.557Z |
| 2016-06-01T17:54:44.499Z |
| 2016-06-01T17:54:44.526Z |
| 2016-06-01T17:54:44.545Z |
| 2016-06-01T17:54:44.564Z |
| 2016-06-01T18:00:49.204Z |
| 2016-06-01T18:00:49.221Z |
| 2016-06-01T18:00:49.238Z |
| 2016-06-01T18:00:49.250Z |
| 2016-06-01T18:31:50.016Z |
| 2016-06-01T18:31:50.048Z |
| 2016-06-01T18:31:50.027Z |
| 2016-06-01T18:31:50.070Z |
| 2016-06-01T18:56:43.838Z |
| 2016-06-01T18:56:48.697Z |
+--------------------------+
19 rows in set (0.00 sec)
'

But in the overlord log I get these once a minute

'
{"t": "2016-06-02T18:17:43.697+0000", "message": "Synced 4 tasks from storage (0 tasks added, 0 tasks removed).", "level": "INFO", "logger_name": "io.druid.indexing.overlord.TaskQueue", "thread_name": "TaskQueue-StorageSync"}
{"t": "2016-06-02T18:17:48.703+0000", "message": "{id='imetrics', generationTime=2016-06-02T18:17:48.703Z, payload={dataSource='imetrics', topic='RawInteractionMetrics', partitions=3, replicas=2, durationSeconds=3600, active=[{id='index_kafka_imetrics_66b3064361431ee_lmlnofmn', startTime=null, remainingSeconds=null}, {id='index_kafka_imetrics_66b3064361431ee_lkmbhmdb', startTime=null, remainingSeconds=null}, {id='index_kafka_imetrics_7f75267cb06b630_lfjnnfod', startTime=null, remainingSeconds=null}, {id='index_kafka_imetrics_7f75267cb06b630_jnnoddbp', startTime=null, remainingSeconds=null}], publishing=[]}}", "level": "INFO", "logger_name": "io.druid.indexing.kafka.supervisor.KafkaSupervisor", "thread_name": "KafkaSupervisor-imetrics-0"}
{"t": "2016-06-02T18:18:18.720+0000", "message": "{id='imetrics', generationTime=2016-06-02T18:18:18.720Z, payload={dataSource='imetrics', topic='RawInteractionMetrics', partitions=3, replicas=2, durationSeconds=3600, active=[{id='index_kafka_imetrics_66b3064361431ee_lmlnofmn', startTime=null, remainingSeconds=null}, {id='index_kafka_imetrics_66b3064361431ee_lkmbhmdb', startTime=null, remainingSeconds=null}, {id='index_kafka_imetrics_7f75267cb06b630_lfjnnfod', startTime=null, remainingSeconds=null}, {id='index_kafka_imetrics_7f75267cb06b630_jnnoddbp', startTime=null, remainingSeconds=null}], publishing=[]}}", "level": "INFO", "logger_name": "io.druid.indexing.kafka.supervisor.KafkaSupervisor", "thread_name": "KafkaSupervisor-imetrics-0"}
{"t": "2016-06-02T18:18:40.674+0000", "message": "Generating: http://localhost:4000", "level": "INFO", "logger_name": "com.metamx.http.client.pool.ChannelResourceFactory", "thread_name": "HttpPostEmitter-1-0"}
'

[middlemanager.txt](https://github.com/druid-io/druid/files/296247/middlemanager.txt)
<img width="1144" alt="screen shot 2016-06-02 at 2 23 28 pm" src="https://cloud.githubusercontent.com/assets/9967543/15756102/c64ec448-28cd-11e6-807c-06cd0a368616.png">

**Comment by gianm** [comment]
@drewdahlke Your overlord seems to have got itself into a weird state, but restarting should fix that. Does restarting help?

**Comment by drewinin** [comment]
Yeah, bouncing the overlord gets things back in gear. I noticed when it was in a bad state all the active tasks had empty offsets, null startTime, null remainingSeconds. Attaching the before/after payloads 

[overlord_unhappy.txt](https://github.com/druid-io/druid/files/297688/overlord_unhappy.txt)
[overlord_happy.txt](https://github.com/druid-io/druid/files/297689/overlord_happy.txt)


currentOffsets": {
        },
        "startTime": null,
        "remainingSeconds": null

I wonder if there's an edge case where loosing a peon to an IOException from S3 throws off the overlord's state.

**Comment by dclim** [comment]
@drewdahlke cool, glad you were able to get things going again. I tried to reproduce it by forcing an exception at that point in the code but the MM and overlord were able to recover so I'm not exactly sure what sequence of events happened to get your overlord into that state. If you happen to see it again and can write up a fairly reliable repro for it, that would be super helpful. 

In the meantime, I noticed that in your spec you had specified a replication factor of 2 but were only running one middle manager. Just wanted to make sure it was clear that replication works by enforcing that replica tasks run on separate middle managers so that ingestion won't be interrupted by the failure of an MM; hence for 2 replicas, you'll want to run at least 2 MMs (otherwise they'll just sit in pending and be killed when the running one succeeds without doing any work).

**Comment by dclim** [comment]
@fjy this issue is almost definitely not specifically related to the KafkaIndexTask or supervisor and probably not a regression introduced in 0.9.1 either, but seems to be some pre-existing weirdness where the RTR doesn't have a correct view of the cluster and doesn't realize there's available MM capacity; it's probably okay for us to push the fix to a later release

**Comment by drewinin** [comment]
Thanks for looking @dclim. Good to hear its probably unrelated to KafkaIndexTask and I'll go multi-mm next week (just prototyping right now). I'll keep baking it and let y'all know if it re-occurs.

**Comment by drewdahlke** [comment]
I just discovered I had been packaging the mysql metadata .9.0 extension with druid .9.1. Fixing that fixed another weird state problem I was seeing, so I'm thinking we can probably close this one out. I'll re-open if I see the problem again post-fix. While that's my fault, a sanity check requiring extension versions to match the server they're being loaded into might be cool. Anyways, Thanks everyone!
