### ISSUE TITLE
killDataSourceWhitelist cannot be set using Coordinator UI

### ISSUE THREAD

**Issue by pjain1** [druid-io/druid#3055]
![screen shot 2016-06-02 at 9 47 18 am](https://cloud.githubusercontent.com/assets/11787983/15749171/16bc48d2-28a7-11e6-834f-213eb258007c.png)
![screen shot 2016-06-02 at 10 29 29 am](https://cloud.githubusercontent.com/assets/11787983/15750652/edbf845c-28ac-11e6-9b8a-d61f58a34a5e.png)

```
error:"Can not deserialize instance of java.util.HashSet out of VALUE_STRING token↵ at [Source: HttpInputOverHTTP@7522095a; line: 1, column: 220]"
```

**Comment by xvrl** [comment]
@pjain1 this looks like a bigger problem, it actually breaks the coordinator ui entirely if a whitelist has been set through the REST API. Looks like this was broken in https://github.com/druid-io/druid/pull/1990 when adding that field. @himanshug can you look into that?

**Comment by himanshug** [comment]
@xvrl i have little/no experience with the coordinator ui, coffeen, node etc so far, can someone more knowledgeable point me to the place where problem lies and I can take a look at it. I see that most of it is written by @tarekrached , is he still maintaining it ?

**Comment by fjy** [comment]
@himanshug no he is not.

At some point we will rebuild the coordinator UI but for the time being we need to fix this

**Comment by fjy** [comment]
@himanshug the problem is with #1990 not the UI

**Comment by gianm** [comment]
If I had to guess, the UI probably doesn't support sending/receiving json arrays, which it would have to in order to deal with killDataSourceWhitelist.

**Comment by fjy** [comment]
@gianm that makes sense

**Comment by himanshug** [comment]
@gianm that sounds true, @fjy POST api directly to coordinator works as expected.

**Comment by himanshug** [comment]
actually deserialization of json array works fine, so if someone updated killDataSourceWhitelist using direct POST request and then viewing the config in the coordinator UI, it shows up as a comma separated list of dataSources fine.
however, if someone now wants to save updated config via the ui, then that does not work because request sent does not have a json array in killDataSourceWhitelist but a string.

**Comment by himanshug** [comment]
I'm gonna fix it on the server by optionally accepting comma separated list of things in a string in addition to a json array... UI sends comma separated list as a string , so that would work fine.
