### ISSUE TITLE
Stalls after running QueryGranularityTest

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#3067]
See https://github.com/druid-io/druid/pull/3060#issuecomment-223440871 and https://github.com/druid-io/druid/pull/3062#issuecomment-223473989

These stalls seem to be after QueryGranularityTest runs but before the next one runs? Also both were on java7. @jon-wei said he saw the same thing on a third PR, also java 7. Maybe related to `testDeadLock` and java 7 doesn't like having a thousand classloaders get made?

**Comment by gianm** [comment]
another https://travis-ci.org/druid-io/druid/jobs/134913904

**Comment by drcrallen** [comment]
I find it odd that the test finishes, reports as complete, THEN pukes and dies.

**Comment by gianm** [comment]
Yeah that is weird.

**Comment by gianm** [comment]
Another https://travis-ci.org/druid-io/druid/jobs/134920880

**Comment by gianm** [comment]
Another https://travis-ci.org/druid-io/druid/jobs/134913904

**Comment by drcrallen** [comment]
They all freeze during the coveralls step.
