### ISSUE TITLE
hadoopDependencyCoordinates seems to be hided by hadoop jars in druid-hdfs-storage extensions

### ISSUE THREAD

**Issue by jaehc** [druid-io/druid#3129]
Even though I am not quite sure of this, after a few testing it turns out that `hadoopDependencyCoordinates` is hided by hadoop jars in `druid-hdfs-storage`. To give a example, if I changed `hadoop.compile.version` in pom.xml to 2.6.0 and ask a indexing with `hadoopDependencyCoordinates` of 2.3.0, the index task loads classes in 2.6.0, not 2.3.0.

I think after #2596 which puts the hadoop dependencies at the LAST position, hadoop jars in `druid-hdfs-storage` go before `hadoopDependencyCoordinates` in class loading.

Is there any workaound or solutions for this?

**Comment by drcrallen** [comment]
See https://github.com/druid-io/druid/issues/2476

**Comment by jaehc** [comment]
@drcallen
Thanks!! I will close this issue and follow up #2476
