### ISSUE TITLE
Tuning second granularity does not work

### ISSUE THREAD

**Issue by andremleblanc** [druid-io/druid#3156]
Druid 0.9.1-rc3
Tranquility Core 0.8.1

**Description**
If tuning granularity is set to `com.metamx.common.Granularity.SECOND` a `failed to create merged beam` error will be generated which is caused by `java.lang.IllegalArgumentException: No gross firehose id hack for granularity[SECOND]`.

It looks like the definition might just be missing here: https://github.com/druid-io/tranquility/blob/master/core/src/main/scala/com/metamx/tranquility/druid/DruidBeamMaker.scala#L245

**Steps to Reproduce**
1. Setup a DruidBeam using this example: http://static.druid.io/tranquility/api/latest/#com.metamx.tranquility.druid.DruidBeams$
2. Set `ClusteredBeamTuning` to `Granularity.SECOND`
3. Write a datapoint.

**Comment by fjy** [comment]
@andremleblanc Thanks for this catch. Do you mind submitting a PR with the fix?

**Comment by fjy** [comment]
I'm guessing this is a bug but @gianm might have deeper insight

**Comment by andremleblanc** [comment]
@fjy absolutely, I should be able to do that over the next couple days.

**Comment by gianm** [comment]
I think I was just not open minded enough to imagine that anyone would want segmentGranularity = SECOND :)

@andremleblanc out of curiosity what would you use this for?

**Comment by andremleblanc** [comment]
@gianm it would just be used during testing as a workaround for the other issue I opened (#3154). 

I am using DruidBeams to build a Tranquilizer to send data to Druid. In between tests I want to clean the datasource so there are no points. Ideally, I'd like to disable the datasource, issue a kill task to delete the data I wrote, and go to the next test. The issue is that disabling a datasource with a running task doesn't actually disable the datasource so issuing a kill task on the interval doesn't work.  Even if it did, after issuing a kill task, it seemed like writing to an interval that had a completed task containing that interval does not work.

As a workaround for this, I can use the overlord API to shutdown the running task, disable the datasource, and issue a kill task for the data I've written. The issue with this is noted above, I can't write to an interval that is contained in a completed task. The message drops and the log has message that says something like `Turns out we decided not to actually make beams for identifier[druid:overlord/datasource_name] timestamp[2016-06-14T19:00:00.000Z]. Returning None.` I don't really consider this behavior problematic since I doubt there is a good use-case for killing a running task and then trying to write to the same interval; but, maybe the more appropriate solution would be changing this behavior.

By changing the granularity to seconds, I can shutdown the running task, issue a kill task for the data I've written, and, as long as my next write is in the next second, I can avoid the above issue. The reason I thought I should be able to use a second is because it is defined here: https://github.com/metamx/java-util/blob/master/src/main/java/com/metamx/common/Granularity.java#L43 but I see now this is a common class so it is probably getting used somewhere else where second is anticipated.

I also see that this issue should have really been opened in the Tranquility repo, sorry about that. I've started working on adding second to the list and have tests passing, I am about to build a .jar and see if adding that definition allows me to run tests the way I was planning. Assuming it does, I was planning on opening a PR on the Tranquility repo. I can definitely run my projects tests in an alternate way, I was just trying to match how we run them for other data stores.

**Comment by andremleblanc** [comment]
Submitted PR here: https://github.com/druid-io/tranquility/pull/178

**Comment by gianm** [comment]
@andremleblanc, got it, that makes sense, thanks for explaining! I'll close this issue in favor of the one in tranquility.

Btw, one other thing you could try for your testing is making a new dataSource for each test. That might make things easier, rather than worrying about cleaning up all the stuff for an existing dataSource.
