### ISSUE TITLE
Large change in cache hit rate for 0.9.1

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#3169]
We are seeing a significant change in cache hit rate and response rate for 0.9.1 vs 0.9.0. 

![screen shot 2016-06-20 at 2 35 23 pm](https://cloud.githubusercontent.com/assets/8213081/16213815/2ce9c74c-3707-11e6-8193-62be29db0154.png)

The above screenshot shows cache hit rate over time. Vertical lines are day boundaries. The discontinuity and drop in cache hit rate directly correlates with the 0.9.1 rollout to this node. Rolling back to 0.9.0 causes an increase in reported cache hit rate.

The Memcached metric  `[MEM] Response Rate: All (Failure + Success + Retry)` correlates with the change in cache hit rate. 

The only queries registered on this node are of type dataSourceMetadata, topN, or timeseries.

I don't have enough data yet to determine if there is an impact on query performance.

**Comment by gianm** [comment]
@drcrallen When the hit rates are depressed, is the majority of the cluster running 0.9.1 or 0.9.0? #2643 changed cache keys for all of the filters, so I would expect a single 0.9.1 node amongst a sea of 0.9.0s to experience depressed hit rates.

**Comment by gianm** [comment]
If that's what's going on, you should see a difference if you split the hit rate by "has filters" vs "does not have filters".

Also if you're using approximate histograms, #2891 adjusted cache keys for those.

**Comment by drcrallen** [comment]
@gianm some historicals are on 0.9.1 but not all of them. I'll update this when I have everything on 0.9.1

**Comment by drcrallen** [comment]
General FYI, this is a communicative measure rather than a bug report, since it is not obvious if this is actually a bug or an artifact of configuration, or a release not that simply needs to be written.

**Comment by drcrallen** [comment]
Early results are positive that this is an upgrade side-effect that needs a callout in the release notes and not a regression or drop in caching.

**Comment by drcrallen** [comment]
Will have more information after peak.

**Comment by xvrl** [comment]
@gianm is it possible to make the cache keys backwards compatible? Is that something we should strive for between releases?

**Comment by gianm** [comment]
@xvrl In #2891 no, although in #2690 probably yes? Although in general I don't strive for it (& I think others generally don't either) on the grounds that it would potentially clutter the code, the impact is nil if you use local cache, and probably not too awful if you use remote cache.

**Comment by drcrallen** [comment]
Values have returned to nominal levels. Will update release notes.
