### ISSUE TITLE
500 Error on SegmentMetadataQuery against router for datasource with no data

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#3178]
```json
{
    "intervals": "2016-06-21T19/pt1h",
    "queryType": "segmentMetadata",
    "dataSource": "notExist"
}
```

results in a 500 error with

```json
{"error":"Can not construct instance of io.druid.query.metadata.metadata.SegmentMetadataQuery$AnalysisType, problem: No enum constant io.druid.query.metadata.metadata.SegmentMetadataQuery.AnalysisType.MINMAX\n at [Source: HttpInputOverHTTP@59cc5787; line: 1, column: 337] (through reference chain: java.util.RegularEnumSet[3])"}
```

When issued to the router.

This ALSO occurs when issued over a time range where an otherwise fine datasource has no data. This is easily checked by doing a query in the future beyond when any data should exist in a cluster.

**Comment by nishantmonu51** [comment]
by any chance is the router talking to broker running on old version ?

**Comment by drcrallen** [comment]
@nishantmonu51 no but some historicals are still rolling to 0.9.1

**Comment by drcrallen** [comment]
If there was an incompatible change to SegmentMetadataQuery that needs called out in the release notes, and we really shouldn't break queries during upgrades like that.

**Comment by drcrallen** [comment]
@nishantmonu51 do you know of a SegmentMetadataQuery change that would cause this?

**Comment by gianm** [comment]
@drcrallen the rolling update order must be respected; historicals need to be updated before broker/router. Compatibility is not guaranteed otherwise.

This particular change was in #2208.

**Comment by drcrallen** [comment]
Normally upgrades aren't so strict, I'll chalk it up to impatience on my part if I can get confirmation after our upgrades finish rolling.

**Comment by drcrallen** [comment]
Yeah, works once upgrade finished. User error
