### ISSUE TITLE
SearchQueryDimFilter needs to take DimensionSpec

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#3190]
Currently `SearchQueryDimFilter` only takes a string dimension. It should be able to take a `DimensionSpec`

**Comment by gianm** [comment]
No filter takes dimensionSpec, they all take dimension + extractionFn (including SearchQueryDimFilter). the rationale is: https://github.com/druid-io/druid/issues/3082#issuecomment-224397267

**Comment by drcrallen** [comment]
@gianm thanks, I went blind for some reason, and didn't see the `extractionFn` in the search filter. Will close this out.
