### ISSUE TITLE
caravel: refresh druid metadata

### ISSUE THREAD

**Issue by birdspring** [druid-io/druid#3213]
When I followed the druid quickstart tutorial and loaded some data into the wikiticker datasource.
I also queried druid and it certainly returned some data.
But as I added the cluster into Caravel and hit the "refresh druid metadata" it only replied "Please define at least one metric for your table “.
Any advice? Thanks.

**Comment by fjy** [comment]
You should try the Caravels issues list to get your question answered as
none of the committers are really familiar with operating Caravel.
https://github.com/airbnb/caravel/issues
