### ISSUE TITLE
druid version

### ISSUE THREAD

**Issue by ouoc** [druid-io/druid#3214]
where could I get an old druid version, like druid 0.8.0 ro 0.8.1?
Thanks

**Comment by fjy** [comment]
@ouoc http://static.druid.io/artifacts/releases/druid-<version>-bin.tar.gz

**Comment by ouoc** [comment]
@fjy Thanks, buy I cannot open this link, the error code is 404.

**Comment by fjy** [comment]
@ouoc you have to fill in versiongoeshere with the actual version....

**Comment by ouoc** [comment]
@fjy  That is so embarrassing...So sorry about that I didn't catch the point.
But now I got another druid version.
Thanks a lot.
