### ISSUE TITLE
Lease exceptions on push in HdfsDataSegmentPusher with replicas

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#3219]
Looks to be something related to the fact that the N replica tasks are all going to try to publish the same segment to the same location. See https://groups.google.com/d/msg/druid-user/kZVNO0MgCs4/mu-SHoXDBgAJ

It might work better for the hdfs pusher to create a tmp file first (index.zip.uuid?) and then rename it into place.

**Comment by du00cs** [comment]
I am working on some related code and notice that this issue I have met before too.

**Comment by gianm** [comment]
Fixed by #3494.
