### ISSUE TITLE
BatchServerInventoryView is created twice

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#3237]
Brokers retain two copies of `BatchServerInventoryView`. One through `BatchServerInventoryViewProvider` and one through `FilteredBatchServerInventoryViewProvider`. This causes excessive use of heap when there are a large quantity of segments and servers.

**Comment by drcrallen** [comment]
This is a 0.9.1 regression from https://github.com/druid-io/druid/pull/2848

**Comment by drcrallen** [comment]
![screen shot 2016-07-12 at 3 50 55 pm](https://cloud.githubusercontent.com/assets/8213081/16786404/7398ebb6-4849-11e6-8ab3-5c7d420ed4b2.png)

Here's an example of the Eclipse MAT analysis of a heap dump from one of the brokers.

**Comment by gianm** [comment]
Why does the broker need both? Shouldn't it only have a `FilteredServerInventoryView`?

**Comment by drcrallen** [comment]
@himanshug  / @nishantmonu51 ^^^^?

**Comment by gianm** [comment]
It looks like the one place it asks for injection of a `ServerInventoryView` instead of `FilteredServerInventoryView` is DruidBroker.java. Switching that to a FilteredServerInventoryView should work too and seems like a cleaner solution.

**Comment by drcrallen** [comment]
@gianm I'd like to get https://github.com/druid-io/druid/pull/3238 anyways so the space that replicants of a segment take up are minimized

**Comment by nishantmonu51** [comment]
agree with @gianm DruidBroker needs to be fixed to use FilteredServerInventoryView
will submit a fix shorty.
