### ISSUE TITLE
imply start servers

### ISSUE THREAD

**Issue by birdspring** [druid-io/druid#3240]
When I use imply to start both master and data servers, it always alerts 'Cannot lock svdir, maybe another 'supervise' is running:".
How could I to solve this?
Any idea, thanks.

**Comment by gianm** [comment]
@birdspring, the intent with the Imply packaging is that you would start just one supervisor per machine. If you want to run master and data services on the same machine, you could combine them into a single supervisor config (see http://imply.io/docs/latest/operations.html). Or you could use the bundled quickstart.conf, which starts all services (master, data, and query).

Also, this repo is for Druid itself; you can file Imply distribution specific issues here in the future: https://github.com/implydata/distribution

**Comment by birdspring** [comment]
I truly used this method...I wonder if there have other solutions before.
Now it seems not.
Thank you very much.
