### ISSUE TITLE
how druid integrate with hadoop

### ISSUE THREAD

**Issue by gaoxuesong** [druid-io/druid#3251]
Does druid integrate with Hortonworks Hadoop platform - HDP? 
How install druid in HDP 2.4?

**Comment by nishantmonu51** [comment]
@gaoxuesong, druid can be configured to work with HDP 2.4 (which includes Hadoop 2.7.1 version) 
You will need to follow the steps documented here - 
http://druid.io/docs/latest/operations/other-hadoop.html

**Comment by gaoxuesong** [comment]
@nishantmonu51 Thanks
