### ISSUE TITLE
The difference between string and hadoopystring

### ISSUE THREAD

**Issue by billbargens** [druid-io/druid#3260]
Under the quickstart folder of druid, there is a example file: wikiticker-index.json.  It defines a ingestion task with task type "index_hadoop" and parser type "string".

But in the official doc(http://druid.io/docs/latest/ingestion/) about parser type, you mentioned:

> This should say string in general, or hadoopyString when used in a Hadoop indexing job.

So what's the difference between string and hadoopyString?

**Comment by gianm** [comment]
The difference is that in addition to the String type, hadoopyString also supports the Hadoop Text and BytesWritable types. This isn't always necessary but it does let Druid work with more kinds of Hadoop InputFormats.

I raised this PR to adjust the example: #3263. Thanks for the report.
