### ISSUE TITLE
KafkaIndexTask maxRowsInMemory is per-Sink, should be not-per-Sink

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#3271]
Since there is up to one Sink per time range per partition, you can actually potentially get a lot more rows in memory than you expect. Would be nice for it to apply across all Sinks.

**Comment by navis** [comment]
seemed related to #2459, but that is for realtime task

**Comment by gianm** [comment]
should be fixed by #3284 for appenderator/kafka.

@navis thanks for pointing out #2459, will take a look.

**Comment by fjy** [comment]
👍
