### ISSUE TITLE
how druid caches query result？

### ISSUE THREAD

**Issue by wanyisunflower** [druid-io/druid#3272]
After I query some dimension using groupBy query, I found that using groupBy query to query other dimensions become more efficient, anyone can explain druid's caching principle？

**Comment by gianm** [comment]
Hey @wanyisunflower, there are two kinds of "caching" in Druid. One is your OS's page cache, which caches portions of data segments in memory. Another is Druid's builtin query cache, which caches on a per-query-per-segment basis. The Druid query cache is off by default.

Odds are the effect you noticed was based on the OS's page cache.

If you have some follow up questions, please feel free to post on https://groups.google.com/forum/#!forum/druid-user (we use github issues more for bugs and feature requests).
