### ISSUE TITLE
Netty HttpClient worker threads are not configurable

### ISSUE THREAD

**Issue by dclim** [druid-io/druid#3301]
This issue belongs with the metamx/http-client project:

The Netty client worker pool uses a non-configurable Runtime.getRuntime().availableProcessors() \* 2 threads. This can create an excessive number of threads on machines with a high number of cores that run a large number of Druid processes (e.g. MMs with lots of peon processes).

https://github.com/metamx/http-client/blob/master/src/main/java/com/metamx/http/client/HttpClientInit.java#L119

It would be good if this could be overridden through configuration. DruidHttpClientConfig has a numMaxThreads field (set from 'druid.global.http.numMaxThreads') which is not currently being honored and probably makes sense to use here.

**Comment by drcrallen** [comment]
ugh, yeah... that needs to be fixed by making it configurable in http-client

**Comment by gianm** [comment]
http-client patch in https://github.com/metamx/http-client/pull/25

**Comment by gianm** [comment]
http-client 1.0.5 includes that patch.

**Comment by leventov** [comment]
@dclim could this issue be closed?

**Comment by dclim** [comment]
@leventov yes, thank you
