### ISSUE TITLE
Standardized "Resource limit exceeded" error

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#3336]
Currently we have three "standard" error codes ("Query interrupted", "Query timeout", "Query cancelled") and all other errors are reported in a more free form manner.

I think it'd be nice to add a standard "Resource limit exceeded" error code as well, for things like the groupBy max rows limit, so callers can differentiate those kinds of things from arbitrary server errors.

Would also be nice to document these error codes so users can write automated handling for them.

Related: #3335

**Comment by gianm** [comment]
Potential patch that would apply after #3335: https://github.com/gianm/druid/compare/fix-query-errors...gianm:resource-limit-error?expand=1

Errors generated look like:

```json
{
  "error": "Resource limit exceeded",
  "errorMessage": "Maximum number of rows [500000] reached",
  "errorClass": "io.druid.query.ResourceLimitExceededException",
  "host": "druid1.example.com:8083"
}
```

or:

```json
{
  "error": "Resource limit exceeded",
  "errorMessage": "Grouping resources exhausted",
  "errorClass": "io.druid.query.ResourceLimitExceededException",
  "host": "druid1.example.com:8083"
}
```

**Comment by fjy** [comment]
👍 I think having more standardized errors would be helpful

**Comment by gianm** [comment]
PR: #3338
