### ISSUE TITLE
Theta sketch column type inconsistency in segmentMetadata

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#3339]
segmentMetadata queries get the type of complex metrics from StorageAdapter's `getColumnTypeName`. On IncrementalIndex, that uses the AggregatorFactory's `getTypeName`. On QueryableIndex, it uses the ComplexColumn object's `getTypeName` (which in turn comes from the ComplexMetricSerde's `getTypeName`).

This works fine for hyperUnique and approximateHistogram, but not for theta sketches. They report "thetaSketch" for QueryableIndexes and "thetaSketchBuild" or "thetaSketchMerge" for IncrementalIndexes. This leads to segmentMetadata column responses looking like:

```
"someThetaSketchColumn": {
  "type": "STRING",
  "hasMultipleValues": false,
  "size": -1,
  "cardinality": null,
  "minValue": null,
  "maxValue": null,
  "errorMessage": "error:cannot_merge_diff_types"
}
```

Not sure what the best solution is, but this situation is not ideal. Probably ideally theta sketches should always be reported as type "thetaSketch".

Fixing this could potentially involve changing the implementation of StorageAdapter's `getColumnTypeName`, since it's not used for anything other than segmentMetadata queries.

**Comment by himanshug** [comment]
@gianm
I'm more inclined to change IncrementalIndex.getMetricType() to return type from ComplexMetricsSerde as serde is the one responsible for storing data and its type information.

AggregatorFactory.getTypeName() is more of transient information required to read the input data correctly.

what do you think?

**Comment by gianm** [comment]
@himanshug that sounds good to me.

**Comment by himanshug** [comment]
@gianm ok, will make the update... need to ensure that doesn't break something else.
