### ISSUE TITLE
Exception is created but not thrown

### ISSUE THREAD

**Issue by AppChecker** [druid-io/druid#3348]
In method [FileTaskLogsTest.testPushTaskLogDirCreationFails](https://github.com/druid-io/druid/blob/890e3bdd3f0deecd80565a20b0192f213516a8fb/indexing-service/src/test/java/io/druid/indexing/common/tasklogs/FileTaskLogsTest.java#L80)  :
RuntimeException is created but not thrown.
Is "throw" keyword  missing?

This possible defect found by [AppChecker](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by gianm** [comment]
Haha, yes! Thanks robots!

PR: #3352
