### ISSUE TITLE
Kafka Supervisor bloats zk discovery path

### ISSUE THREAD

**Issue by sixtus** [druid-io/druid#3358]
After testing kafka supervisor for two days, I got more than 1000 index_kafka_* entries in the zk discovery path and they don't go away (i.e. even stopping the supervisor does not help)

**Comment by gianm** [comment]
@dclim Looks like this is coming from the Kafka index tasks announcing themselves with the chat handler provider – do you know if that's really necessary? IIRC the supervisor finds them without that, using the overlord's builtin task location finding stuff (which doesn't leave "presents" in ZK).

**Comment by gianm** [comment]
@sixtus thanks for the report

**Comment by gianm** [comment]
Answering my own question: yes, registering with the chat handler provider is necessary to expose the servlet. But, the provider should have an option on registration to opt of announcing. Realtime tasks still need to announce (for compat with older tranquillity versions) but Kafka tasks should never need to announce.

**Comment by sixtus** [comment]
Can you hint me what to patch? I'd love to deploy this asap, but zk bloat is a show stopper. 

Thanks!
Hagen

**Comment by gianm** [comment]
@sixtus if you aren't using tranquility (and therefore don't need service discovery to work there) then you should be able to comment out `serviceAnnouncer.announce(node);` and `serviceAnnouncer.unannounce(makeDruidNode(service));` in ServiceAnnouncingChatHandlerProvider.java.

**Comment by dclim** [comment]
@gianm thanks Gian, I'll submit a patch for a SimpleChatHandlerProvider that doesn't do the unnecessary service discovery announcement.

**Comment by gianm** [comment]
@dclim IMO it'd be better to have a flag on `register` about whether or not announcing is needed; it's a little goofy, but it would let us hard-code "false" in Kafka index task and "true" in the Realtime task, meaning legacy tranquility and kafka indexing can co-exist in the same cluster. That'd help people migrate from the former to the latter.

That'd also mean the default behavior is better. we wouldn't want to switch the default chat provider away from the service announcing one, and if we don't do that, we'll have to have another step for Kafka indexing service users (set the chat handler to simple). That'd work but it's better to avoid extra steps if we can.

**Comment by gianm** [comment]
I think this is telling us that the chat handler provider is not a great abstraction. Combining service announcing and servlet registration was a bad idea, and we are needing to work around that now. So I think the goofiness is acceptable since it's really just working around the sins of our forebears.

Which I think is me since I think I made that thing in the first place :P

**Comment by dclim** [comment]
Hah, sounds good.

**Comment by sixtus** [comment]
ruby-druid relies on brokers announcing themselves. The rest, I don't have nor care for, still on standalone rt.

I.e. if this doesn't break broker, I'll try on Monday. 

Thanks for the quick help!
Hagen

**Comment by gianm** [comment]
@sixtus It won't break the broker, this will only affect task announcement.
