### ISSUE TITLE
FIX RealtimePlumber will never exit if push to deep Storage failed 

### ISSUE THREAD

**Issue by du00cs** [druid-io/druid#3389]
Our HDFS namenode failure for some time occasionally, and I found that realtime peon nodes upload to HDFS failed and never exit. Looking into the `RealtimePlumber` code and I found that segment push failure will make the Sink never be removed from list, and the peon will be trapped into endless waiting. So a peon will never exit until you kill it manually. This is true for handoff time limit is not set and it is the default parameter.

This can be solved by tracking the state in Sink object and do re-uploading and re-publish in next retries.

I can work on this, any idea?  @fjy

**Comment by fjy** [comment]
@du00cs Nice find. I think your solution is valid

**Comment by du00cs** [comment]
This is true for earlier production case, but I can not reproduce it. I notice that a commit of Himanshu fix that by dropping the failed segments. I will follow this in later days.

**Comment by gianm** [comment]
@du00cs, ah, yeah, if "emit" throws an exception then that is an issue with the emitter. Druid assumes that emitting will not throw exceptions, and extensions should assure that is the case by whatever means they choose.

It's a community extension (not maintained by core committers) but patches are definitely welcome if you can fix it yourself! Or you could try pinging people who have worked on it, check the commit history of the extension for details there. IIRC @b-slim was the main original author.

**Comment by b-slim** [comment]
will take a look at it.

**Comment by b-slim** [comment]
@du00cs what was the exception ? can you share the logs ?

**Comment by b-slim** [comment]
@du00cs checkout this Fix https://github.com/druid-io/druid/pull/3441 assuming one of those exception was the issue.

**Comment by du00cs** [comment]
@b-slim Thanks for quick fix, happy to see the changes.
