### ISSUE TITLE
IndexMerger performance

### ISSUE THREAD

**Issue by leventov** [druid-io/druid#3423]
I was investigating some problem and I thought (but still not sure) that it could be with IndexMerger (or IndexMergerV9) performance.

I prototyped some optimization (essentially, avoiding `Integer` boxing all way down around here: https://github.com/druid-io/druid/blob/c4e8440c229535d9f6b08128cae4102cbfd30ee9/processing/src/main/java/io/druid/segment/IndexMergerV9.java#L569-L577) with the following results:
```
Benchmark                    (numSegments)  (rollup)  (rowsPerSegment)  (schema)  Mode  Cnt        Score        Error  Units
IndexMergeBenchmark.merge                5      true             75000     basic  avgt   25  5905919.910 ? 192443.727  us/op
IndexMergeBenchmark.merge                5     false             75000     basic  avgt   25  5627947.090 ?  47900.602  us/op
IndexMergeBenchmark.mergeV9              5      true             75000     basic  avgt   25  5190361.959 ? 291485.540  us/op
IndexMergeBenchmark.mergeV9              5     false             75000     basic  avgt   25  4966467.226 ? 292196.632  us/op
IndexMergeBenchmark.mergeV9Optimized     5      true             75000     basic  avgt   25  4338240.159 ? 297783.637  us/op
IndexMergeBenchmark.mergeV9Optimized     5     false             75000     basic  avgt   25  4138934.689 ?  88831.896  us/op
```

Could anyone tell if this part of code and `IndexMergeBenchmark` are relevant to overall performance of Druid's indexing? Does such an improvement worth some increased size and complexity of the codebase?

For optimization, I replaced `Iterator<Integer>` with `IntIterator` from [fastutil](http://fastutil.di.unimi.it/), also used fastutil's `IntArrayList` and `LongHeapPriorityQueue`. fastutil is a very fat library (~ 19 MB), that could be a consideration. Avoiding this dependency means copying some logic into the Druid codebase, that has well known downsides like increased probability of bugs, support costs, compexity, etc.

**Comment by drcrallen** [comment]
@leventov FYI, we have https://github.com/metamx/bytebuffer-collections that has a bunch of the "fast int list" funcitons in it.

**Comment by leventov** [comment]
@drcrallen didn't see anything like IntIterator in this repo. There is also `io.druid.collections.IntList`, but it also doesn't provide IntIterator abstraction.

This change doesn' require half of the `fastutil` library, probably just a couple of hundreds LOCs.

**Comment by leventov** [comment]
To make it clear, the question of this issue is -- is it worth to make a PR improving IndexMergers performance (according to IndexMergeBenchmark, how relevant is this to overall performance is also a part of the question), but also introducing some complexity? If it is, should the PR use fastutil (maybe minimizing/shading?), or copying logic into Druid?

Another concern is changed `IndexedInts` API (`Iterator<Integer> iterator(); -> IntIterator iterator()`, is this interface designed for subclassing in Druid's extensions? Fastutil's `IntIterator` is a subclass of `Iterator<Integer>`, so external usage of `IndexedInts` shouldn't be an issue, only subclassing.

**Comment by fjy** [comment]
@leventov have you looked at buildV9Directly flag? It should substantially improve performance

**Comment by leventov** [comment]
@fjy buildV9Directly is irrelevant to this issue?

**Comment by drcrallen** [comment]
@leventov IndexMerger has two aspects of immediate interest: 1) cpu-time 2) heap pressure

If a PR improves one or the other in a measurable way without sacrificing either, then it is worth bringing in. Ingestion and batch time resource usage are important.

**Comment by drcrallen** [comment]
Can you please post the benchmark times of master on the system you are testing on, and note what kind of system it is (example: laptop vs ec2 instance)

**Comment by leventov** [comment]
@drcrallen I've posted benchmark times in the first message in this thread, compare `V9` (51..., 49...) and `V9Optimized` (43..., 41...). Or you mean something different?

There couldn't be a big difference depending on the system, because this optimization is only about managed, on-heap JVM data structures and operations with them. Only the ratio of time spent in OS/JVM could be different in different systems, but it couldn't completely turn the effect of the change. However, in the PR intruducing this benchmark (https://github.com/druid-io/druid/pull/2875) @jon-wei  posted similar results (52..45 vs 51..49).

The question to Druid committers remain: in what form should be this PR: some code copied from fastutil into the Druid codebase, or introducing a dep?

**Comment by leventov** [comment]
I've also checked that `IndexedInts` and implementations are not even used in extensions, so the change shouldn't create issues with backwards compatibility.

**Comment by drcrallen** [comment]
IMHO dependency is preferred to more code that we need to maintain. 

I miss-read your original benchmark results; I see difference now.

What system did you run these tests on?

**Comment by leventov** [comment]
@drcrallen Windows 10 with SSD, Java 8.

**Comment by drcrallen** [comment]
@leventov laptop, desktop, ec2, other?

**Comment by drcrallen** [comment]
windows, so `-server`?

**Comment by leventov** [comment]
@drcrallen laptop.

JMH takes care of this :)
```
# JMH 1.9.2 (released 488 days ago, please consider updating!)
# VM invoker: C:\Program Files\Java\jdk1.8\jre\bin\java.exe
# VM options: -server
...
```

**Comment by drcrallen** [comment]
@leventov I'm always [super paranoid about laptop benchmark results](https://metamarkets.com/2015/effect-of-frequency-governor-on-java-benchmarking/) but I think this is far enough a split to be a really good improvement.

**Comment by leventov** [comment]
@drcrallen results on some EC2 instance:
```
Benchmark                             (numSegments)  (rollup)  (rowsPerSegment)  (schema)  Mode  Cnt        Score   Error  Units
IndexMergeBenchmark.merge                   5      true             75000     basic  avgt       8579136.165          us/op
IndexMergeBenchmark.merge                   5     false             75000     basic  avgt       8742163.703          us/op
IndexMergeBenchmark.mergeV9                 5      true             75000     basic  avgt       7041228.726          us/op
IndexMergeBenchmark.mergeV9                 5     false             75000     basic  avgt       6719966.901          us/op
IndexMergeBenchmark.mergeV9Optimized        5      true             75000     basic  avgt       6926857.899          us/op
IndexMergeBenchmark.mergeV9Optimized        5     false             75000     basic  avgt       6056248.944          us/op
```

I'll prepare PR then
