### ISSUE TITLE
druid-kafka-indexing-service needs upgrade to kafka v0.10

### ISSUE THREAD

**Issue by sixtus** [druid-io/druid#3426]
Kafka v0.10 is out and it seems prudent to keep the indexer on the newest version (especially since there was a protocol change)

A simple bump in the pom is not enough.

**Comment by dclim** [comment]
Also see: https://groups.google.com/forum/#!topic/druid-user/CmAgH897WiU

**Comment by gianm** [comment]
This was done in #4115.
