### ISSUE TITLE
currSize of StorageLocation does not reflect correct storage usage

### ISSUE THREAD

**Issue by sirpkt** [druid-io/druid#3444]
`currSize` is updated whenever a segment is added to or removed from the given `StorageLocation`
and used to calculate available space of the storage.
However, the value of `currSize` is reset to 0 when historical node restarts
even though there exist cached segments.

I think it `currSize` should be restored or recalculated when historical node starts.

**Comment by drcrallen** [comment]
`io.druid.server.coordination.ZkCoordinator#start` calls `io.druid.server.coordination.ZkCoordinator#loadLocalCache` which does the actual segment loading, including calling `segment.getSize()` on every segment it can find in the local cache. It does this as fast as its little disk can read the data, even more so if `druid.segmentCache.numBootstrapThreads` is set.

From our side, any solution that tries to even more eagerly set `curSize` as seen by the coordinator would need to not interfere with the already long task of `ZkCoordinator#start`. If you're concerned about the coordinator doing things when the cache has not been fully initialized, then there can be steps taken to mitigate that effect.

**Comment by sirpkt** [comment]
@drcrallen You're right. `currSize` is updated during loadLocalCache().  I'd better to close this issue.

However, I'll keep #3445 because `SegmentLoaderLocalCacheManager` still has some impovement points that I think.
- When user specifies multiple paths on the same partition by mistake, it will induces skewed disk usage on that server. Actually I experienced that situation.
- Other applications may share the same disk with historical nodes, so user may not use the amount of disk specified by `maxSize`. It needs to monitor disk usage and update possible maximum size.
