### ISSUE TITLE
Still waiting for Handoff for Segments

### ISSUE THREAD

**Issue by antimion** [druid-io/druid#3466]
Hi, 

i am new in druid, and i have problem with running jobs, they newer finished if i run middlemanager on another host from all other services.

I have setup "distributed" cluster, it means i have run overlord,broker,historical and coordinator on same host, middleManager and tranquility on another. Also as deep storage i have used **local storage** (maybe problem here, i don't know) . 

nothing strange in all logs, but when i open task log i see this message
`2016-09-19T06:38:17,178 INFO [coordinator_handoff_scheduled_0] com.metamx.http.client.pool.ChannelResourceFactory - Generating: http://10.44.70.6:8081
2016-09-19T06:38:17,188 INFO [coordinator_handoff_scheduled_0] io.druid.segment.realtime.plumber.CoordinatorBasedSegmentHandoffNotifier - Still waiting for Handoff for Segments : [[SegmentDescriptor{interval=2016-09-19T04:00:00.000Z/2016-09-19T05:00:00.000Z, version='2016-09-19T06:05:27.854Z', partitionNumber=0}]]`

or this message 
`2016-09-19T06:46:53,090 INFO [topic7-kafka-incremental-persist] io.druid.segment.ReferenceCountingSegment - Closing topic7-kafka_2016-09-19T06:00:00.000Z_2016-09-19T07:00:00.000Z_2016-09-19T06:06:53.047Z
2016-09-19T06:46:53,090 INFO [topic7-kafka-incremental-persist] io.druid.segment.ReferenceCountingSegment - Closing topic7-kafka_2016-09-19T06:00:00.000Z_2016-09-19T07:00:00.000Z_2016-09-19T06:06:53.047Z, numReferences: 0`

strange things start here, i can see written data in caravel
 
`user   count
alice	   91955.0
bob	   91955.0
chist    91955.0`

can somebody explain why my jobs when they running on host with all other services completes with SUCCESS, but when i running two different host they have never finished?

[common.runtime.properties.txt](https://github.com/druid-io/druid/files/479381/common.runtime.properties.txt)
[kafka.json.txt](https://github.com/druid-io/druid/files/479377/kafka.json.txt)
[runtime.properties.broker.txt](https://github.com/druid-io/druid/files/479378/runtime.properties.broker.txt)
[runtime.properties.coordinator.txt](https://github.com/druid-io/druid/files/479379/runtime.properties.coordinator.txt)
[runtime.properties.historical.txt](https://github.com/druid-io/druid/files/479382/runtime.properties.historical.txt)
[runtime.properties.middlemanager.txt](https://github.com/druid-io/druid/files/479380/runtime.properties.middlemanager.txt)
[runtime.properties.overlord.txt](https://github.com/druid-io/druid/files/479383/runtime.properties.overlord.txt)

**Comment by nishantmonu51** [comment]
Fwiw, in clustered mode, deep storage needs to be configured to a distributed file system which is accessible by all the druid nodes. try changing your deep storage to hdfs or s3.

**Comment by antimion** [comment]
nishantmonu51, thank you for explain.

I have create user for druid, user for hdfs, copy all *-site.xml files to _common/, add hdfs storage path to my config files, and starting druid under druid user. Now, i have working "cluster" with two middlemanager and historical nodes.

**Comment by nishantmonu51** [comment]
I believe you need not restart your middlemanagers, It should get picked up for the new tasks since each task is a separate VM. 
To make things more cleaner, You can also use the classpathPrefix property in the task and have versioned configs for your directoryStructure. 
e.g. you can have a directory structure hadoopConfigs/v1 and when you make a change create a new directory hadoopConfigs/v2. and point new tasks to use the new classpath by setting classpathPrefix to hadoopConfigs/v2.

**Comment by antimion** [comment]
nishantmonu51 , thanks.
