### ISSUE TITLE
Use atomic writes for local deep storage

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#3493]
If Druid is configured with local deep storage, concurrent pushes (which replicated tasks do as a matter of course) can lead to data corruption. This can happen if multiple daemons run on the same machine, or if the local deep storage is actually an NFS mount used for a distributed cluster.

Atomic writes in LocalDataSegmentPusher (write to X.uuid -> rename to X; rather than write directly to X) will fix it for true local fses and I _think_ it will fix it for NFS too.

Originally reported in https://groups.google.com/d/topic/druid-user/hv3BvuGdK3w/discussion.

**Comment by drcrallen** [comment]
write and rename seems to be the only reasonable way to do anything these days :)

**Comment by gianm** [comment]
fixed by #3521.
