### ISSUE TITLE
flattenSpec: unified way to access elements of complex data (JSON, Avro, ProtoBuf, Thrift, ...)

### ISSUE THREAD

**Issue by knoguchi** [druid-io/druid#3505]
I would like to be able to ingest ProtoBuf / Avro using `flattenSpec`.
`flattenSpec` uses JSON Path but it's generally applicable to any structured data.

I've read the source of `ProtoBufInputRowParser`, and probably I can add some hack to [buildStringKeyMap](https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/data/input/ProtoBufInputRowParser.java#L85).  But there should be more generic way to implement this feature.

By the way I definitely want to avoid converting the PB to JSON then apply JSON Path.   Any hints?

**Comment by knoguchi** [comment]
I just realized there are PR's already.   All of them try to support complex data but the access to the nested elements are all different.

#2354 Protobuf parser: nested messages and fileds, define any message name to parse
#2414 Support pulling values from complex avro data structures
#3418 [Feature] Thrift support for realtime and batch ingestion

There are some discussions whether to use JSON Path or to use native expression e.g. Avro has its own expression.

**Comment by du00cs** [comment]
Hi, I am from #3418 . All formats above can be converted to json easily, unified way should come with unified intermediate format first. JSON Path may be a good choice.

**Comment by knoguchi** [comment]
Now, I'm working on adding ETL capability to Druid, and considering Jackson JsonNode as the intermediate format.   I would like to introduce two modules.

- [Jacskon  standard binary dataformat backends](https://github.com/FasterXML/jackson-dataformats-binary)
- [Jackson-jq](https://github.com/eiiches/jackson-jq)

I'm thinking of adding flattenSpec type "jq" and accept the jq expression in the "expr". 

One consideration is that we should not use the JSON _string_ as the intermediate format.  It costs serializing the native object, and then deserializing back to the common object.  The Jackson binary backend should help avoiding this problem (needs research).   It supports Avro, Protobuf and two other formats out of the box.  Unfortunately [Thrift support](https://github.com/FasterXML/jackson-dataformat-thrift) is left untouched for 4 years(!) though.

As for the jq, it's a "Swiss Army knife for JSON".  It's widely accepted and proven to be capable for filtering and transforming the JSON.  JSONPath is pretty weak other than extracting values out of the nested structure.

**Comment by knoguchi** [comment]
We can close this issue as the jq support has been merged.
