### ISSUE TITLE
Kill tasks does not delete all segments from S3

### ISSUE THREAD

**Issue by schmee** [druid-io/druid#3525]
I have these segment files on S3:

```
.
└── <HADOOP_DATASOURCE>
    └── 2016-05-01T00:00:00.000Z_2016-06-01T00:00:00.000Z
        └── 2016-05-20T12:11:10.881Z
            └── 0
                ├── descriptor.json
                ├── index.zip
                └── index.zip.0
```

These were created with Hadoop Batch ingestion. I'm not sure exactly how the segment files work, but I assume the `index.zip.0` file is a newer version of the same segment?

I then submit the this kill task to http://druid-overlord:8090/druid/indexer/v1/task

```
{
  "type": "kill",
  "id": "byebye",
  "dataSource": "<HADOOP_DATASOURCE>",
  "interval" : "2016-01-01/2016-09-30"
}
```

The tasks runs successfully without exceptions and nothing funky in the logs.

However, when I look again in S3, the directory looks like this:

```
.
└── <HADOOP_DATASOURCE>
    └── 2016-05-01T00:00:00.000Z_2016-06-01T00:00:00.000Z
        └── 2016-05-20T12:11:10.881Z
            └── 0
                └── index.zip.0
```

It seems like the versioned files are not removed.

**Comment by Einsteinl** [comment]
Have you found out why

**Comment by didip** [comment]
We have the same problem too. Kill removed segments in PostgreSQL and historical nodes but not in S3.

**Comment by linehrr** [comment]
same problem here. we can still find all the segments in hdfs.
looks like kill tasks are not trying to delete deep storage files.
