### ISSUE TITLE
druid-lookups-cached-single extension not present in 0.9.2-rc1

### ISSUE THREAD

**Issue by MdeArcayne** [druid-io/druid#3527]
Seems like the new  druid-lookups-cached-single extension is not bundled in the tarball found [here](http://static.druid.io/artifacts/releases/druid-0.9.2-rc1-bin.tar.gz).

**Comment by drcrallen** [comment]
Looks like its missing near https://github.com/druid-io/druid/blob/druid-0.9.2-rc1/distribution/pom.xml#L91

**Comment by nishantmonu51** [comment]
:+1:
