### ISSUE TITLE
Is it possible in druid to GROUP BY and do count(*) and order by count?

### ISSUE THREAD

**Issue by loganto** [druid-io/druid#3592]
Hi. Im trying to find some db solution for recording page visits to dictionary pages and running some analitycs queries. 

Im hoping to run query like "SELECT word, count(*) as count GROUP BY `word` ORDER BY count;".
  

Does druid supports something like that?

**Comment by gianm** [comment]
Yes, this is possible with either the [groupBy query](http://druid.io/docs/latest/querying/groupbyquery.html) or [topN query](http://druid.io/docs/latest/querying/topnquery.html).

**Comment by loganto** [comment]
Awesome. Thanks so much.
