### ISSUE TITLE
Can't get druid to index anything. plz help

### ISSUE THREAD

**Issue by loganto** [druid-io/druid#3606]
Hi.

Im trying to get druing to work. So I've set up everything locally using docker.
I try to ingest a batch json data like this:  

`curl -X 'POST' -H 'Content-Type:application/json' -d @/tmp/druid_spec.json localhost:8090/druid/indexer/v1/task`
  
But then I look at the indexer console and it looks like tasks just get stuck in pending mode....why?
http://i.imgur.com/edT3TN1.png

What am I doing wrong?

**Comment by dclim** [comment]
@loganto you have no worker nodes, you'll need to run some middle managers and make sure that they are configured properly so they can be discovered through ZK

In the future, please post your questions to the Druid user group here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/druid-user

**Comment by loganto** [comment]
thx. I got that one fixed.
