### ISSUE TITLE
druid remove duplicates 

### ISSUE THREAD

**Issue by misslzyan** [druid-io/druid#3612]
My data events have duplicates.  Data ingestion stream like below:
     log -- >logstash  --> kafka --> tranquility --> druid 

 Can druid supports to remove duplicates?  or tranquility supports to remove duplicates?
or I should do it by myself . Can you give me some suggestions about how to remove duplicates?

**Comment by fjy** [comment]
@misslzyan please read about rollup here: http://druid.io/docs/0.9.1.1/design/index.html

**Comment by dclim** [comment]
@misslzyan there's a Google Group for these types of questions, could you repost your question there? https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/druid-user

If your raw input data has duplicates, you'll need to de-dupe them yourself before sending the data to Druid. If you're getting duplicates as part of the ingestion process, you may want to look into the Kafka indexing service which guarantees exactly-once ingestion: http://druid.io/docs/0.9.1.1/development/extensions-core/kafka-ingestion.html

**Comment by misslzyan** [comment]
thanks for your suggestions . I will repost this question to the URL you give me
