### ISSUE TITLE
KafkaIndexTask never succeeds handoff if time interval for segment is marked as drop in load rules

### ISSUE THREAD

**Issue by dclim** [druid-io/druid#3619]
If the KafkaIndexTask ingests an event with a timestamp in an interval that has been marked as DROP in the load rules, when the segment is published and the task waits for handoff, this segment will never be loaded by a historical and the task will never receive a callback and will wait around until it's killed due to timeout.

Probably would be better if the task could determine that the segment will not be loaded because of the current ruleset and skip waiting for handoff.

**Comment by gianm** [comment]
I think this is also #2696.

**Comment by dclim** [comment]
Yup looks similar to me. I'll add a note to that issue and close this one.
