### ISSUE TITLE
FileSmoosher changes snuck in with java-util merge

### ISSUE THREAD

**Issue by cheddar** [druid-io/druid#3640]
We moved `java-util` over to the druid repository to make it easier to iterate on functionality in there.  This was spawned by a conversation from PR: https://github.com/metamx/java-util/pull/55

Along with that move, we accidentally included the changes in `FileSmoosher` from that PR.  This is an issue to make sure people are aware of what happened and to discuss what should be done to rectify the situation.

@akashdw

**Comment by gianm** [comment]
IMO since it already had one 👍  then a good solution is for someone else to take a look at the code before 0.9.3.

@cheddar could you confirm that the code moved in to druid in #3585 is equivalent to the diff currently in https://github.com/metamx/java-util/pull/55? If so then that's probably the easiest place to review it.

**Comment by akashdw** [comment]
@cheddar @gianm Yes, code moved in to druid in https://github.com/druid-io/druid/pull/3585 is equivalent to the diff currently in https://github.com/metamx/java-util/pull/55  except imports, package name and license.

**Comment by akashdw** [comment]
@gianm @cheddar Sorry for accidentally adding filesmoosher changes along with migration.  I can open a pr to revert filesmoosher changes to make things more aligned with druid-io review process. What do you think?

**Comment by drcrallen** [comment]
I would rather label this a blocker for 0.9.3 and assume the review will be OK or minimal.

**Comment by gianm** [comment]
+1 to @drcrallen's suggestion.

**Comment by akashdw** [comment]
@cheddar @gianm @drcrallen Created a PR https://github.com/druid-io/druid/pull/3673 to address https://github.com/metamx/java-util/pull/55 review comments.

**Comment by fjy** [comment]
Fixed by #3673
