### ISSUE TITLE
Druid - Use case as a monitoring platform

### ISSUE THREAD

**Issue by lanzelot1989** [druid-io/druid#3641]
Is it plausible to use Druid for operations to monitor the execution times and call distributions of various services of the application?

I gather that things like alerting and so on would be harder to do than with Bosun or Prometheus.

Thanks in advance.

**Comment by drcrallen** [comment]
That's exactly how we use it internally. We have a smaller cluster that collects metrics for Kafka samba spark druid and all the other microservices.

**Comment by drcrallen** [comment]
*samza... phone autocorrect is being silly

**Comment by gianm** [comment]
@lanzelot1989 this is a fairly common use case for Druid, usually people do things like:

- route metrics through Kafka and into Druid
- do alerting on thresholds (like avg query time > X) by polling Druid and alerting based on results of queries
- use the approximate histogram feature to compute medians and percentiles

Many Druid users actually use Druid to analyze execution times of Druid queries by feeding Druid metrics into Druid. (say that 10 times fast)

Closing this, but please follow up on the mailing list if you have further questions.

**Comment by lanzelot1989** [comment]
> Many Druid users actually use Druid to analyze execution times of Druid queries by feeding Druid metrics into Druid. (say that 10 times fast)

But who monitors the execution times of the subsequent queries? :-)

Thanks a lot for the information.
