### ISSUE TITLE
Copy Closer to Druid codebase?

### ISSUE THREAD

**Issue by leventov** [druid-io/druid#3652]
Instead of wasting mental resources on thinking when Closer could or could not be used ( https://github.com/druid-io/druid/pull/3649#issuecomment-257963355), maybe it's simper to just copy `Closer` from Guava master to druid commons/utils and use it everywhere? Because this is a very useful class which is hard to replace, when it couldn't be used.

**Comment by gianm** [comment]
lol, I was checking out the code and noticed this. Those Googlers can be funny sometimes.

```java
// close. this word no longer has any meaning to me.
```

Guava is ASL2, so I think it's fine to copy some stuff from there into Druid if it is simple code that saves a lot of headaches. We should just note in comments what version of Guava it came from and add something to NOTICE.

**Comment by gianm** [comment]
Or: alternative: confirm if the stuff in other-hadoop.md is a good workaround. Then we don't need to copy code from Guava, we just need to educate users better.

**Comment by gianm** [comment]
I think some users may not be trying those tips before concluding that something is unfixable.

**Comment by b-slim** [comment]
i think porting it to druid is a good idea! that will minimize the risque of guava conflicts !
