### ISSUE TITLE
"in" filter with many elements is really slow

### ISSUE THREAD

**Issue by erikdubbelboer** [druid-io/druid#3675]
When I have a simple query that filters using `a = 1 AND b IN [1,2,3]` it is quite fast with 700ms on average. But the more elements I add to the IN the slower it gets. At 3000 elements the query takes 13 seconds.

The values of `a` is only present in segments from the last couple of hours. The values from `b` are present segments going back years.

Shouldn't druid be able to use the first `a = 1` to know that it only has to look at those recent segments which have this value?

**Comment by gianm** [comment]
@erikdubbelboer Yes, it should. It sounds like the real problem is that "and" doesn't short-circuit for index lookups. This patch addresses that: #3676

**Comment by drcrallen** [comment]
I'm also curious if you're using Roaring or Concise?

**Comment by erikdubbelboer** [comment]
@drcrallen sorry for the slow reply. No Roaring or Concise.

**Comment by drcrallen** [comment]
Concise is the default bitmap type. You can get significant boolean-operation speed improvements in Roaring with the side effect of it sometimes taking a bit more space on disk.

**Comment by erikdubbelboer** [comment]
Ah yes sorry we use Concise. Trying Roaring now for the new segments we're creating to see if it makes things faster.
