### ISSUE TITLE
metric referred to as dimension

### ISSUE THREAD

**Issue by textractor** [druid-io/druid#368]
In [this tutorial](http://druid.io/content/Tutorial:-A-First-Look-at-Druid.html), in the section Solving a Problem, the metric `edit_count` is referred to as a dimension:

```json
...
  "orderBy": {
     "type": "default", 
     "columns": [ { "dimension": "edit_count", "direction": "DESCENDING" } ], 
     "limit": 10
  }, 
...
```
But this can't be fixed just in the docs, as code in the Wikipedia example is expecting ` "dimension": "edit_count"`. So code needs to be updated first.

**Comment by fjy** [comment]
The tutorials have changed in 0.7.x, I am going to close this.
