### ISSUE TITLE
Could not resolve type id 'in' into a subtype of simple type

### ISSUE THREAD

**Issue by javalivepeng** [druid-io/druid#3712]
performence the following code,and occur exception "Could not resolve type id 'in' into a subtype of [simple type, class io.druid.query.filter.DimFilter]\n at [Source: HttpInputOverHTTP@3fc7ca65",because of my druid version does not support the "in" ?If so, I should upgrade to which version,Thanks

**code:**
"filter":{
        "type":"and",
        "fields":[
            {
                "type":"selector",
                "dimension":"pid",
                "value":"21"
            },
            {
                "type":"in",
                "dimension":"cid",
                "value":[
                    "0Q5018b9f7l_us",
                    "1"
                ]
            }
        ]
    }

**Comment by erikdubbelboer** [comment]
That's because `in` has `values` (not `value`):
```json
"filter":{
  "type":"and",
  "fields":[
    {
      "type":"selector",
      "dimension":"pid",
      "value":"21"
    },
    {
      "type":"in",
      "dimension":"cid",
      "values":[
        "0Q5018b9f7l_us",
        "1"
      ]
    }
  ]
}
```

**Comment by javalivepeng** [comment]
I'm sorry,Copy the wrong yesterday. Change in values is still this mistake, I doubt is my druid version does not support, or grammatical errors ? Please give advice or comments,thanks

**Comment by javalivepeng** [comment]
"filter":{
        "type":"and",
        "fields":[
            {
                "type":"selector",
                "dimension":"pid",
                "value":"21"
            },
            {
                "type":"in",
                "dimension":"cid",
                "values":[
                    "0Q5018b9f7l_us",
                    "1"
                ]
            }
        ]
    }

"error" : "Could not resolve type id 'in' into a subtype of [simple type, class io.druid.query.filter.DimFilter]\n at [Source: HttpInputOverHTTP@42d69137

**Comment by erikdubbelboer** [comment]
Which version of Druid are you using. And can we see your whole query?

**Comment by javalivepeng** [comment]
druid version:    druid-0.8.1-rc2


whole query:
{
    "queryType":"topN",
    "dataSource":"xxxxx",
    "dimension":"cid",
    "threshold":200,
    "metric":"view_count",
    "granularity":"all",
    "intervals":[
        "2016-11-18T02:37:30+00:00/2016-11-18T03:37:30+00:00"
    ],
    "aggregations":[
        {
            "type":"longSum",
            "name":"view_count",
            "fieldName":"view_count"
        },
        {
            "type":"longSum",
            "name":"click_count",
            "fieldName":"click_count"
        }
    ],
    "filter":{
        "type":"and",
        "fields":[
            {
                "type":"selector",
                "dimension":"pid",
                "value":"21"
            },
            {
                "type":"in",
                "dimension":"cid",
                "values":[
                    "0Q5018b9f7l_us",
                    "1"
                ]
            }
        ]
    }
}

**Comment by erikdubbelboer** [comment]
The `in` filter was only introduced in `0.9.0-rc1`: https://github.com/druid-io/druid/commit/c511273efd6cd391609a3db4bfdcd6096503370c

**Comment by javalivepeng** [comment]
I will upgrade to this version.Thanks
