### ISSUE TITLE
different values for groupBy and timeseries

### ISSUE THREAD

**Issue by sixtus** [druid-io/druid#372]
>> time_series.sum(:events)['2014-01-28T17:00+00:00', '2014-01-28T18:00+00:00'].properties
{
      :dataSource => "metrik",
     :granularity => "all",
       :intervals => [
        [0] "2014-01-28T17:00:00+00:00/2014-01-28T18:00:00+00:00"
    ],
       :queryType => :timeseries,
    :aggregations => [
        [0] {
                 :type => "longSum",
                 :name => "events",
            :fieldName => "events"
        }
    ]
}

>> time_series.sum(:events)['2014-01-28T17:00+00:00', '2014-01-28T18:00+00:00']
+----------+
| events   |
+----------+
| 68977516 |
+----------+

>> sum(:events)['2014-01-28T17:00+00:00', '2014-01-28T18:00+00:00'].properties
{
      :dataSource => "metrik",
     :granularity => "all",
       :intervals => [
        [0] "2014-01-28T17:00:00+00:00/2014-01-28T18:00:00+00:00"
    ],
       :queryType => :groupBy,
    :aggregations => [
        [0] {
                 :type => "longSum",
                 :name => "events",
            :fieldName => "events"
        }
    ]
}

>> sum(:events)['2014-01-28T17:00+00:00', '2014-01-28T18:00+00:00']
+----------+
| events   |
+----------+
| 68977520 |
+----------+

**Comment by fjy** [comment]
I am closing this as I believe #676 has fixed it. Please reopen if this is not the case.
