### ISSUE TITLE
JavaScriptAggregator fnCombine didn't work

### ISSUE THREAD

**Issue by linbojin** [druid-io/druid#3794]
I changed the test case inside io.druid.query.aggregation.JavaScriptAggregatorTest 
https://github.com/druid-io/druid/blob/89d9c61894f122b4973ad5d8d325e114b0a7ebf4/processing/src/test/java/io/druid/query/aggregation/JavaScriptAggregatorTest.java#L88

from 
```
  static {
    sumLogATimesBPlusTen.put("fnAggregate", "function aggregate(current, a, b) { return current + (Math.log(a) * b) }");
    sumLogATimesBPlusTen.put("fnReset", "function reset()                  { return 10 }");
    sumLogATimesBPlusTen.put("fnCombine", "function combine(a,b)             { return a + b }");

    scriptDoubleSum.put("fnAggregate", "function aggregate(current, a) { return current + a }");
    scriptDoubleSum.put("fnReset", "function reset()               { return 0 }");
    scriptDoubleSum.put("fnCombine", "function combine(a,b)          { return a + b }");
  }
```
to, just make fnCombine always return 0
```
  static {
    sumLogATimesBPlusTen.put("fnAggregate", "function aggregate(current, a, b) { return current + (Math.log(a) * b) }");
    sumLogATimesBPlusTen.put("fnReset", "function reset()                  { return 10 }");
    sumLogATimesBPlusTen.put("fnCombine", "function combine(a,b)             { return 0 }");

    scriptDoubleSum.put("fnAggregate", "function aggregate(current, a) { return current + a }");
    scriptDoubleSum.put("fnReset", "function reset()               { return 0 }");
    scriptDoubleSum.put("fnCombine", "function combine(a,b)          { return 0 }");
  }
```

But the test cases are still passing, seems fnCombine is not called or fnCombine is always using (a + b):
![image](https://cloud.githubusercontent.com/assets/5894707/21381310/86787ef6-c795-11e6-942a-f53ad11941f4.png)

**Comment by gianm** [comment]
fnCombine gets called on `AggregatorFactory.combine` but the JavaScriptAggregatorTest doesn't test this. It only tests `aggregate`. I think this is just a lack of test coverage.

**Comment by linbojin** [comment]
Actually, i dive deep into the codes, because i tested the aggregator on our server, i found the problem:
```
    {
      "type": "javascript",
      "name": "sum(log(x)*y) + 10",
      "fieldNames": [
        "traffic",
        "throughputEstimate"
      ],
      "fnAggregate": "function(current, a, b)      { return current + (Math.log(a) * b); }",
      "fnCombine": "function combinePartialResults(partialA, partialB) { return partialA + partialB; }",
      "fnReset": "function()                   { return 10; }"
    }
```
![image](https://cloud.githubusercontent.com/assets/5894707/21395466/8b18c5be-c7d7-11e6-8280-c70cab3509af.png)
and i changed to return 0, but two query give me the same result.
![image](https://cloud.githubusercontent.com/assets/5894707/21395483/97f0c9ee-c7d7-11e6-80a0-750b41362a4d.png)

**Comment by linbojin** [comment]
I also changed this line inside QueryRunnerTestHelper: https://github.com/druid-io/druid/blob/master/processing/src/test/java/io/druid/query/QueryRunnerTestHelper.java#L134
```
public static final String JS_COMBINE_A_PLUS_B = "function combine(a, b) { return a + b; }";
```
to
```
public static final String JS_COMBINE_A_PLUS_B = "function combine(a, b) { return 0; }";
```
and run TimeseriesQueryRunnerTest tests, again, all passed:
![image](https://cloud.githubusercontent.com/assets/5894707/21395735/988276c2-c7d8-11e6-8bba-50f3c3741ccf.png)

**Comment by gianm** [comment]
Do you have more than one segment being queried? If you are only querying one segment, then `combine` won't get called. Your intervals in that query only cover 15 minutes so it may only be hitting one segment.

**Comment by linbojin** [comment]
Thx, I will test more late.

**Comment by linbojin** [comment]
@gianm You are right, if i query on multiple segments, fnCombine works well. So it is just a lack of test coverage. Thx, i will close this issue.
