### ISSUE TITLE
Faster TopN historical processing and more metrics

### ISSUE THREAD

**Issue by leventov** [druid-io/druid#3798]
The purpose of this issue is to label a series of PRs (10-15), they

 1. Add more dimensions to "query/time", "query/segment/time" and "query/cpu/time" metrics, that allows to identify the slowest queries and then the most problematic parts of the Druid codebase.
 2. Make processing of TopN queries with 1 or 2 aggregators on historical nodes 2-4 times faster

Averages:
![image](https://cloud.githubusercontent.com/assets/609240/21442284/9149d104-c862-11e6-95fb-d0f41167a16a.png)

Distribution by nodes:
![image](https://cloud.githubusercontent.com/assets/609240/21442307/c53c423a-c862-11e6-915a-465cc8c662ad.png)

Later similar optimizations could be applied to
 - processing of topN queries with any number of aggregators
 - processing of topN queries on realtime nodes
 - timeseries and probably other types of queries

I expect that the performance increase will be smaller than 50-75%, but still significant.

**Comment by leventov** [comment]
Outline of "Faster topN query processing" part:
 1. Add `QueryProcessingHotLoopCallee` marker interface with `inspectRuntimeShape()` method. `inspectRuntimeShape()` is similar to `toString()`, but it focuses on exact classes of the fields for monomorphism and selected aspects for branch predictability, i. e. the fraction of set bits in bitmaps we iterate over. `DimensionSelector`, `ValueMatcher`, `BufferAggregator`, `Float/Long/ObjectColumnSelector`, `IndexedInts`, `Offset` and probably some other interfaces extend `QueryProcessingHotLoopCallee`.
 2. Before making a query, getting the *runtime shape* of the relevant parts e. g. for topN it's offset and aggregators. Make copies of query processing class (e. g. stateless `TopNProcessor`) and cache instances of those copied classes in `ConcurrentMap<RuntimeShape, TopNProcessor> shapeProcessors`. Then query like `shapeProcessors.get(aggregator.inspectRuntimeShape()).process(aggregator, offset, resultsBuffer, ...)`.
 3. Specialize single-value `DimensionSelector`s with method `int getRowValue()`.
 4. Specialize historical-side and common `Dimension/Long/FloatSelector`s with methods which allows to provide `rowNum` externally: `DimensionSelector.getRow[Value](int rowNum)`, `FloatColumnSelector.get(int rowNum)`, etc.

**Comment by gianm** [comment]
Is the idea that TopNProcessors will be code-generated when Druid is built? Or would they be hand-written?

**Comment by leventov** [comment]
@gianm "TopNProcessor" is a normal class: https://github.com/metamx/druid/blob/753848c38789e3b7558988d81f17c771ac4da8fc/processing/src/main/java/io/druid/query/topn/GenericPooledTopNScannerPrototype.java

In runtime, bytecode of this class is copied to a new class with minor modifications using ASM library: https://github.com/metamx/druid/blob/753848c38789e3b7558988d81f17c771ac4da8fc/processing/src/main/java/io/druid/query/topn/PooledTopNAlgorithm.java#L102-L144

Don't pay attention to the details of the referenced code, it is "dirty".

**Comment by gianm** [comment]
Got it, sounds like a nice approach.

**Comment by himanshug** [comment]
50+% improvement sounds great to me

**Comment by leventov** [comment]
TopN queries on indexing nodes are 8 times faster:
![image](https://cloud.githubusercontent.com/assets/609240/22227683/1207356e-e192-11e6-9ec3-2d67e96d6a75.png)
