### ISSUE TITLE
Jackson version conflict with avatica

### ISSUE THREAD

**Issue by praveev** [druid-io/druid#3800]
There is a conflict with jackson-databind 2.6.3 (from transitive dependencies of calcite-core and avatica-core) and druid's explicit jackson-databind 2.4.6 dependency. I see issues during batch ingestion. Realtime using tranquility is fine. Here is a gist containing the stack trace

Druid has direct dependency on `calcite-core`, `avatica-core` and `avatica-server` from https://github.com/druid-io/druid/pull/3682.

`avatica-core` is the non-shaded artifact which only contains client classes without any bundled dependencies except jackson. as per this: https://github.com/apache/calcite/commit/e5a42f1ca80eca0bb6f0c8f6677f106fadb2e652#diff-eb4d33b91f63eeaaea2ffd36688b61f8R49

`calcite-core` depends on shaded avatica.
`avatica-server` depends on non-shaded avatica
`avatica-core` is the non-shaded avatica.

cc: @gianm

**Comment by glycerine** [comment]
I'm not able to build tip, is this the same issue as #3800 or different?  seems that `calcite-core` is mentioned....

I'm osx 10.11.6 with java 1.8.0_66

~~~
...
[INFO] druid-time-min-max ................................. SKIPPED
[INFO] druid-google-extensions ............................ SKIPPED
[INFO] druid-virtual-columns .............................. SKIPPED
[INFO] druid-thrift-extensions ............................ SKIPPED
[INFO] ambari-metrics-emitter ............................. SKIPPED
[INFO] druid-caffeine-cache ............................... SKIPPED
[INFO] distribution ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:17 min
[INFO] Finished at: 2016-12-23T19:21:36-06:00
[INFO] Final Memory: 31M/437M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project druid-sql: Could not resolve dependencies for project io.druid:druid-sql:jar:0.9.3-SNAPSHOT: Failed to collect dependencies at org.apache.calcite:calcite-core:jar:1.10.0 -> org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde: Failed to read artifact descriptor for org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde: Could not transfer artifact org.pentaho:pentaho-aggdesigner-algorithm:pom:5.1.5-jhyde from/to conjars (http://conjars.org/repo): Connect to conjars.org:80 [conjars.org/107.22.169.25] failed: Operation timed out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
j ~/go/src/github.com/druid-io/druid (master) $ 
~~~

**Comment by gianm** [comment]
@glycerine that looks like a different issue.

**Comment by glycerine** [comment]
@gianm: yes, sorry. deleted.

**Comment by gianm** [comment]
See discussion in #3805, we will attempt to fix this by upgrading to Calcite 1.11.0 when it comes out (release expected soon: https://issues.apache.org/jira/browse/CALCITE-1547).

**Comment by joshelser** [comment]
Can anyone take the 1.11.0-rc0 release candidate for a spin to let us know if it solves the issues you were seeing, please?

https://dist.apache.org/repos/dist/dev/calcite/apache-calcite-1.11.0-rc0/

Should be able to do something like.. `curl https://dist.apache.org/repos/dist/dev/calcite/apache-calcite-1.11.0-rc0/apache-calcite-1.11.0-src.tar.gz | tar x && cd apache-calcite-1.11.0-src && mvn install -DskipTests`

Then, switch your calcite dependency version to 1.11.0 and do whatever tests from Druid-land to see if the Jackson conflict issue has been resolved.

Thanks!

**Comment by gianm** [comment]
thanks @joshelser, I'll try that out.

**Comment by gianm** [comment]
@joshelser - that build looks good to me. Druid tests pass, it starts up fine, the Avatica server works, and the deps in the built Druid tarball are clean (only avatica-core, avatica-metrics, and avatica-server are present).

**Comment by joshelser** [comment]
Wonderful! Thanks for the quick turnaround, @gianm. I'll report back on the Apache Calcite mailing list :)
