### ISSUE TITLE
groupBy v2: Results not fully merged when caching is enabled on the broker

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#3820]
groupBy bySegment results are not sorted by the grouping dimensions, which means that when caching is enabled on the broker, they get stored in the cache in potentially unsorted order. When they get pulled back out on the broker, CachingClusteredClient attempts to merge the resulting sequences as if they were sorted (using a MergeSequence based on query.getResultOrdering), which leads to a not fully sorted sequence.

groupBy v1's `mergeResults` does not assume the sequence from CachingClusteredClient is sorted (it re-sorts it using an IncrementalIndex) so it works fine.

But groupBy v2's `mergeResults` assumes that the sequence it's combining is already sorted, which is true if caching is disabled (because the broker is merging sequences from data nodes, and they sort their results) but is not true in this case when caching is enabled.

We could fix this by sorting by-segment results in the cache or by somehow teaching groupBy v2 that in this particular case, it shouldn't assume the sequence it's combining is already sorted. But both of those would incur a performance penalty when caching is enabled, which is counterproductive to the purpose of caching… so I'm not sure what's best.

See https://groups.google.com/d/topic/druid-user/4gmKSw33EiM/discussion for the original report.

**Comment by nishantmonu51** [comment]
Out of the above two approaches, i think storing the sorted results in the cache might be better otherwise we would have to resort the results every time even if we hit the cache. 
Agreed, there will be a performance penalty, but since we disable caching of groupBy queries by default, probably its ok. 
Whatever strategy we choose we should also mention this in the groupBy docs that uncached queries are expected to become slower after caching.

**Comment by gianm** [comment]
Fwiw I haven't tested this, but I think things should work fine even now if caching is enabled on the historicals. They always re-sort their by-segment results whether or not they come from the cache (this happens in mergeRunners).

So this problem is really a broker cache thing -- and it would be a shame to pay the sorting penalty when caching is enabled on historicals.

**Comment by gianm** [comment]
I'd like to avoid having a performance impact on historicals, where sorting is not necessary, and doing it would be wasteful.

I would be fine with fixing this by just forcing cache to be disabled for groupBy v2 on brokers. If it works fine for historicals, then moving cache to historicals is a viable option for users to get groupBy caching. If we go this way, it'd be good to log a warning on broker startup if the user tried to enable groupBy caching.

I would also be fine with fixing this by sorting results when pulling from cache, but only on brokers. (It has to be when pulling, not when inserting, because it's possible the brokers and historicals share a memcache and a historical wrote in some unsorted results)

Both of those approaches mean that the query tool chest needs to know whether it's on a broker or not. I'm not sure of the best way to expose that (isBroker is probably wrong). Maybe "willMergeRunners"? (groupBy v2 does sorting & merging in mergeRunners, so that'd be enough info)

**Comment by jihoonson** [comment]
I'm working on this issue.

**Comment by jihoonson** [comment]
@gianm, what do you think about simply adding a flag to represent the cached bySegment result is sorted or not?

**Comment by gianm** [comment]
That could be part of a solution, but what behavior would be changed when the flag is set?

**Comment by jihoonson** [comment]
Oh, I mean adding the flat to the cache key of groupBys.

**Comment by gianm** [comment]
Is your idea that the broker would sort results before putting them in the cache, and would include "is sorted" as part of the cache key? And historicals would keep behaving as they do now -- results in cache are unsorted?

**Comment by jihoonson** [comment]
I realized that the behavior of ```GroupByMergingQueryRunnerV2``` is different according to the cache is enabled or not. So please forget about my above comments.

So far, @gianm's first idea, disabling cache for groupBy v2 on brokers, seems good to me. I'll go with this way.

**Comment by l15k4** [comment]
Hey, I'm just pointing to a discussion about a possible GroupBy performance degradation (5-6 times decrease) possibly caused by this : 
https://groups.google.com/d/msg/druid-user/hf8SOEaP_jg/VWpob50jBwAJ

After upgrading from 0.9.2 to 0.10.1.

**Comment by mlubavin-vg** [comment]
Hey guys, just wanted to let you know, that I went through enabling segment cache on brokers only to bang my head for a day why my groupByV2 queries weren't being cached at all before I found this.  It should really be mentioned in the caching documentation: https://druid.apache.org/docs/0.17.0/querying/caching.html#using-and-populating-cache

Would you like a PR for the doc change in caching.md?

**Comment by himanshug** [comment]
updating the doc sounds good to me.
