### ISSUE TITLE
does druid has an plan to support someway to read batch data from druid?

### ISSUE THREAD

**Issue by kingnj** [druid-io/druid#3854]
hi, we need to treat druid not just as a realtime query server, we want to read batch data from druid with any interval,such as 5 minute, What is the way?

thank you!

**Comment by himanshug** [comment]
not sure if I understood that correctly... you can send queries to druid broker to get data for 5 min intervals.

**Comment by kingnj** [comment]
@himanshug thanks

but our data is very big (12million/minute), if i use http rest query, it will very slow to get results

**Comment by himanshug** [comment]
that is the only supported/built-in way to read data from druid.

we sometimes use https://github.com/himanshug/druid-hadoop-utils to read druid data from pig/MR (and will probably add HiveStorageHandler at some point too). you can use  it if you wanted to read things via hadoop and know that it does not have full support for handling complex aggregators.

**Comment by kingnj** [comment]
@himanshug thank you very much
 i am very expect HiveStorageHandler feature:)

**Comment by nishantmonu51** [comment]
@himanshug @kingnj: there is some work done by @b-slim on the storage handler part - https://github.com/apache/hive/pull/120
you might be interested in that, i am not sure how much helpful it ll be in your case since.

**Comment by kingnj** [comment]
@nishantmonu51 thanks ,i will try
