### ISSUE TITLE
Ability to ingest pre-computed hyperUnique value

### ISSUE THREAD

**Issue by DaimonPl** [druid-io/druid#3864]
We've got druid data ingestion use case in which pre-computed HLL indexes can be stored in approximately 6*10^4 rows but preparing same data in raw format and ingesting it in druid requires preparation of 10^12 rows.

Because of this we've switched to thetaSketch aggregator which allows loading of pre-computer theta sketch.

However in our use case we only need count distinct feature so theta sketch itself adds too much overhead (it's much more space consuming than hyperUnique).

It would be great if:
- druid would allow ingesting of pre-computed hyperUnique (like thetaSketch does)
- druid would expose public API which allows to compute and merge hyperUnique values so it can be precomputed in other systems (for example in Hive using UDF)

**Comment by gianm** [comment]
Wow, you have 16 million unique values per row? That's some good rollup :)

This seems like a useful feature, would you be willing to contribute code for it? I think what's needed is a new ComplexMetricsSerde for hyperUnique that treats strings as base64 encoded collectors, rather than as plain strings, and a flag on the aggregator factory that changes the return value of `getTypeName` to trigger that alternate serde. Sort of like how theta sketches work.

Then, breaking out the HLL algorithm into a druid-hll module with minimal dependencies would make it easy to include in other projects.

**Comment by DaimonPl** [comment]
Original dataset is not that big but it must be self-joined (on quite 'explosive' condition) with hyperUnique values on both sides. So if those hyperUnique values can be pre-computed before that join, then resulting dataset to ingest is small. Unfortunately because of way current hyperUnique ingestion is done we'd need to do that 'explosive' join (it's not as bad as cartesian, but still bad ;) ) first and put result to druid to ingest - and that result dataset would be simply too big.

I haven't dived into druid internal code yet (at all) so I'm not sure how long would it take to understand changes you are talking about but I can try :)

**Comment by DaimonPl** [comment]
I'll be working on this. Is there some way to contact you in case i have some doubts?

**Comment by gianm** [comment]
Sure, just post here!

**Comment by DaimonPl** [comment]
First PR available (extraction of HLL code to separate module)

**Comment by DaimonPl** [comment]
One more question.

As I understand those changes will be available in druid 0.10.0. currently we are using 0.9.2 - is there any way to get it included in older branch (other than our own custom fork with merge) ?

**Comment by DaimonPl** [comment]
@gianm could you help about this last question?

**Comment by gianm** [comment]
Yep your patch will be in 0.10.0. That's the next planned release, there won't be an 0.9.3 barring unforeseen circumstances.

**Comment by DaimonPl** [comment]
Ok, closing issue itself

**Comment by amitme10** [comment]
Hey ,
I hope it's related :

I'm trying to use this aggregator : 
{
  "type" : "hyperUnique",
  "name" : <output_name>,
  "fieldName" : <metric_name>,
  "isInputHyperUnique" : **true,**
  "round" : false
}

on my precomputed sketch, which was built with swoop's spark-alchemy hll functions.

However I'm struggling with an "illegal base64 character 3c" error there .

I wonder what's the problem ... maybe the format is not correct there or something with my loading data process is wrong?

**Comment by DaimonPl** [comment]
You need to use druid-hll for that and encode it with base 64

**Comment by amitme10** [comment]
Thanks @DaimonPl  , I added the druid-hll dependency to my pom . 

you mean I should use a specific function from there on my sketch , and then encode it to base64 (in the end of course add it to the DF)?

If so, could you kindly tell me which function?

**Comment by DaimonPl** [comment]
You said you used spark-alchemy for HLL calculation. This most likely won't work as it's binary format is not compatible with druid HLL. You need to use druid-hll to ensure binary sketch compatibility.

Once you use druid-hll API to calculate and/or aggregate your HLLs, you then need to base64 encode it before passing data to druid

**Comment by amitme10** [comment]
Got it , so for this purpose I can't use spark-alchemy at all. 
Is there any documentation for the druid-hll ? or an example for use? (spark-alchemy's function I use now are just init+merge for buiding the binary sketch and cardinality to calculate )

thanks.

**Comment by DaimonPl** [comment]
druid-hll is also more or less init+merge, have you checked source code?

For spark you need to call druid-hll from custom spark udf or create hive udf

**Comment by amitme10** [comment]
yea I looked at it , I believe that those function are at HyperLogLogCollector class

**Comment by amitme10** [comment]
Is there any option to tune the cardinality estimation (accuracy) ?

As I see in DataSketches HLL Sketch module
`
{
  "type" : "HLLSketchBuild",
  "name" : <output name>,
  "fieldName" : <metric name>,
  "**lgK**" : <size and accuracy parameter>,
  "tgtHllType" : <target HLL type>,
  "round": <false | true>
 }

{
  "type" : "HLLSketchMerge",
  "name" : <output name>,
  "fieldName" : <metric name>,
  "**lgK**" : <size and accuracy parameter>,
  "tgtHllType" : <target HLL type>,
  "round": <false | true>
 }
`

of course I'm using this:
`
{
  "type" : "hyperUnique",
  "name" : <output_name>,
  "fieldName" : <metric_name>,
  "isInputHyperUnique" : false,
  "round" : false
}
`
