### ISSUE TITLE
Use official AWS SDK for Java instead of jets3t library

### ISSUE THREAD

**Issue by leventov** [druid-io/druid#3886]
jets3t library seems to be unsupported.

https://github.com/aws/aws-sdk-java

**Comment by gianm** [comment]
+1

Would also be nice to upgrade our hadoop version to one that supports s3a, which uses aws-java-sdk instead of jets3t.

**Comment by webratz** [comment]
Actually not using the SDK raises many issues. Especially It is a best practice to not use credentials whenever possible and using roles / instance profiles instead.
This is impossible with the current implementation.

**Comment by drcrallen** [comment]
You can use instance profiles. The credential chain is here https://github.com/druid-io/druid/blob/master/aws-common/src/main/java/io/druid/common/aws/AWSCredentialsUtils.java

**Comment by webratz** [comment]
thank you. that wasn't quite clear from the docs

**Comment by leventov** [comment]
Closing in favor of #4289
