### ISSUE TITLE
i want to set granularity like 5min or 10 min

### ISSUE THREAD

**Issue by zhxiaom5** [druid-io/druid#3947]
i want to set granularity like 5min or 10 min,is that possible ?

**Comment by kaijianding** [comment]
https://github.com/druid-io/druid/pull/3850 and https://github.com/druid-io/druid/pull/3766 are what you need

**Comment by kaijianding** [comment]
for granularity in query, you can use PeriodGranularity or DurationGranularity

**Comment by zhxiaom5** [comment]
thanks,i will try it

**Comment by zhxiaom5** [comment]
Thats resolved
