### ISSUE TITLE
can druid support sub aggregation ？

### ISSUE THREAD

**Issue by zhxiaom5** [druid-io/druid#3948]
can druid support sub aggregation ？
like elastic sub aggregation？

**Comment by gianm** [comment]
Are you talking about the kind of sub aggregations described here? https://www.elastic.co/blog/intro-to-aggregations-pt-2-sub-aggregations

Some of those could be done with multi-dimension groupBy queries, some of them would probably require you to make multiple Druid queries (like one topN for the first level and then multiple subsequent topNs for the second level).

**Comment by zhxiaom5** [comment]
yes,thanks for you answer
