### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by maxd** [druid-io/druid#397]
Hello,

Sometimes [my query](https://gist.github.com/maxd/deda8ab84e0d2cc25286) cause [exception](https://gist.github.com/maxd/f5ced4eec8db48cdf3d5).

Let me know if required additional information about this problem.

Thanks

**Comment by fjy** [comment]
I am going to close this issue as there has been no update for awhile. Please feel free to reopen if this this still an issue.
