### ISSUE TITLE
BUG: quantile (approxHistogram) not produce correct result

### ISSUE THREAD

**Issue by hamlet-lee** [druid-io/druid#3972]
In my product system, the quantile=0.5 result is very far from real value. (even if I set the resolution to a relative high value) for e.g.:

ingest:
```
                        {
                            "type": "approxHistogramFold",
                            "name": "hist_fold_api_duration",
                            "fieldName": "api_duration",
                            "resolution": 10000,
                            "lowerLimit": 0,
                            "upperLimit": 60000
                        } 
```

query
```
{
    "queryType": "timeseries",
    "dataSource": "xxx",
    "granularity": "all",
    "intervals": [
        "2017-02-06T00:00:00+08:00/2017-02-07T00:00:00+08:00"
    ],
    "aggregations": [
        {
            "type": "approxHistogramFold",
            "name": "hist_fold",
            "fieldName": "hist_fold_api_duration",
            "resolution": 10000,
            "numBuckets": 100
        }
    ],
    "postAggregations": [
        {
            "type": "quantile",
            "name": "myResult",
            "fieldName": "hist_fold",
            "probability": 0.5
        }
    ],
    "context": {}
}
```

expected real value: 190
druid result: 1167.81 (I tried multiple resolution in ingest time, druid result is near this value)

I attach the api_duration dataset, in case someone can reproduce or fix the bug.
[api_duration.txt](https://github.com/druid-io/druid/files/798656/api_duration.txt)

**Comment by ginoledesma** [comment]
I see this behavior as well in both druid 0.10.0 and 0.10.1. In my dataset, I get 0.95/0.98 quantile values exceeding that of max (whether from doubleMax or max on the approxHistogramField).

In my particular case, the mem fields were returning odd quantile values (but cpu and disk were fine).

[sample-dataset.csv.txt](https://github.com/druid-io/druid/files/1261947/sample-dataset.csv.txt)
[sample-index.json.txt](https://github.com/druid-io/druid/files/1261948/sample-index.json.txt)
