### ISSUE TITLE
QueryGranularity `testDeadlock` test timeouts 

### ISSUE THREAD

**Issue by praveev** [druid-io/druid#3978]
@kaijianding reports in #3850 that the `testDeadlock` test timeouts after that PR merge and that it may need more time.

I'm not sure how i feel about a test that takes > 60seconds.

**Comment by kaijianding** [comment]
It doesn't pass in my local IDE. Though it can pass with less loop, like 100 times.
I found two CI failure due to this test from 2 different PR.
https://travis-ci.org/druid-io/druid/builds/205857310 and https://travis-ci.org/druid-io/druid/builds/205833322

**Comment by drcrallen** [comment]
@kaijianding if you up the timeout does it pass?

If it does not pass it might be encountering a deadlock.

**Comment by praveev** [comment]
@drcrallen i was just looking at the context in which you wrote this test - https://github.com/druid-io/druid/issues/2979.

**Comment by fjy** [comment]
@praveev @drcrallen tests that take 60 seconds are a giant nono in Druid. Unit tests should take at most 1 second.

**Comment by drcrallen** [comment]
Yes, but if its failing because of a deadlock the deadlock needs fixed.

If it is failing because it just takes longer then it can be fixed to take less time.

**Comment by praveev** [comment]
agree. that test initially had a timeout of 10 secs and then @nishantmonu51 upped to 60secs with https://github.com/druid-io/druid/pull/3224

**Comment by praveev** [comment]
I believe this is b/c of a change that was introduced after the CR feedback. I'm putting in a fix for this now.

**Comment by praveev** [comment]
@kaijianding the test doesn't fail for me locally. tried executing on IDE as well as via mvn.

**Comment by praveev** [comment]
ok. i can confirm that the something with #3850 has slowed loading of the class significantly.
This test took 5secs for 1000 iterations before the merge. Now its taking over 5secs for 10 iterations

**Comment by praveev** [comment]
@drcrallen the issue has been fixed. please review the pr. 

The reason it took so long was b/c all the predefined granularities were also being initialized each time. So i followed the same trick as before, moved the static fields to a separate `Granularities` file and moved the check for `PREDEFINED_GRANULARITIES` inline instead of maintaining a separate list.
