### ISSUE TITLE
Duration Granularity `toDateTime` throws UnsupportedOperationException

### ISSUE THREAD

**Issue by praveev** [druid-io/druid#3994]
Duration Granularity throws an UnsupportedException when its `toDateTime` [method](https://github.com/druid-io/druid/blob/0.10.0/java-util/src/main/java/io/druid/java/util/common/granularity/DurationGranularity.java#L117) is called.
This is incorrect. It should let the call through to base class Granularity to retain the pre-refactor behavior.

This bug was introduced with #3850 refactor. We noticed this issue during 0.10.0 RC deployment, when we updated the historicals and nothing else. The queries to the broker where failing b/c granularity "day" was  being represented by DurationGranularity and its `toDateTime` invocation from `QueryableIndexStorageAdapter` threw an UnsupportedException.

**Comment by gianm** [comment]
@praveev, are you working on a patch for this?

It also looks like we don't have many tests for DurationGranularity -- just a serde test, no query tests. It'd be good to add some usages of DurationGranularity to the query tests, like GroupByQueryRunnerTest et al.

**Comment by gianm** [comment]
As well as tests for its basic methods like truncate, toDateTime, and so on.

**Comment by praveev** [comment]
yup. we're deploying other stuff as well. so i want to see if there are any other issues, i should have a patch tomorrow.

**Comment by gianm** [comment]
great!
