### ISSUE TITLE
HdfsDataSegmentPusher bug.

### ISSUE THREAD

**Issue by akashdw** [druid-io/druid#3997]
Hdfs namespace optimization changes https://github.com/druid-io/druid/pull/3877 introduced a bug in HdfsDataSegmentPusher causing exceptions during segment push (if an interval has more than one shard.)

Current code tries to rename `version`(parent directory of index.zip) directory instead of copying index/descriptor files to the right location. Renaming `shard` directory was valid but that directory is now removed.
Couldn't catch this b/c our staging environment creates only 1 shard per interval.

I'm working on the fix and adding tests for multiple segments push instead of just 1.

**Comment by gianm** [comment]
Thanks @akashdw for the report, I added this to 0.10.0.
