### ISSUE TITLE
topN query returns error while groupBy works fine

### ISSUE THREAD

**Issue by tdingus** [druid-io/druid#4037]
Hi,

I have the following query that returns error: "Instantiation of [simple type, class io.druid.query.topn.TopNQuery] value failed: dimensionSpec can't be null"

{
  "queryType": "topN",
  "dataSource": "fruits",
  "descending": "false",
  "dimensions":"apple",
  "metrics":["color"],
  "threshold": 5,
  "granularity": "all",
  "intervals": [
    "2017-03-12T14:03:00.000Z/2017-03-12T14:04:00.000Z"
  ],
  "aggregations": [
    { "type": "longSum", "name": "color", "fieldName": "color" }
  ],
  "pagingSpec":{"pagingIdentifiers": {}, "threshold":50}
}

However, if I change topN to groupBy, it returns results fine.

Thanks,

 - tdingus

**Comment by yashdeeph709** [comment]
Hi tdingus,
The groupby query mandatory requirement of  dimensionSpec which you didn't provided.
You can provide a dimension spec of various types: default,extraction,regexFiletered,listFiltered,lookup.
While topn don't need a dimensionSpec.

**Comment by tdingus** [comment]
Hi yashdeeph709,

Thanks for replying. However, I did have "dimensions":"apple", which is according to http://druid.io/docs/latest/querying/topnquery.html.

It would be helpful if you could correct my example, and post it here.

 - tdingus

**Comment by gianm** [comment]
@tdingus, topN only supports one dimension at a time, so it's "dimension" not "dimensions".
