### ISSUE TITLE
consult about how druid query data in the version of 0.9.1

### ISSUE THREAD

**Issue by mjaow** [druid-io/druid#4090]
realtime node was the role to query realtime data.Now there is no realtime node,which node will get the realtime search done?Is it peon of middle-manager?it seems no doc mention about this

**Comment by gianm** [comment]
Yes, you have it right. There are some docs at http://druid.io/docs/latest/design/indexing-service.html although I guess they could be more explicit about the fact that tasks handle queries too. A patch would be welcome 😄

**Comment by mjaow** [comment]
@gianm thx for reply.You solve my problems ^^
