### ISSUE TITLE
not using historical node

### ISSUE THREAD

**Issue by zhxiaom5** [druid-io/druid#4117]
maybe historical node is useless to me，and i just want search result in 1 hour。
so，how to configure to not use  historical node ？
ps：i use tranquilty kafka to ingest msg
thanks

**Comment by kaijianding** [comment]
FlushingPlumber exactly fits your need, it doesn't do handoff and periodically drop old data, thus historical node is not needed.
You can start a realtime node using FlushingPlumber @zhxiaom5

**Comment by zhxiaom5** [comment]
In the end, I stil use a historical node, and I use kafka index service to replace tranquilty. But I set "taskDuration" long enough,so It wont genereate segment so off,Then I can set segment genereate timeout short to make it fail.
