### ISSUE TITLE
Druid return random timezones when using a non-UTC timezone

### ISSUE THREAD

**Issue by erikdubbelboer** [druid-io/druid#4126]
After updating to `druid-0.10.0-rc2` we are seeing druid return random timezones. This only seems to happen when we use a different timezone than UTC.

Which rows have these random timezones changes every time the report is re-run.

In theory the time is not wrong as the hour changes accordingly but seeing that this happens randomly I'm pretty sure this is undesired behavior.

The query we run is:
```json
{
  "aggregations": [
    { 
      "fieldName": "requests",
      "name": "impressions",
      "type": "longSum"
    }
  ],
  "context": {
    "queryId": "0fac7c63-3450-4d75-a160-ea0b99a37751"
  },
  "dataSource": "requests",
  "granularity": {
    "period": "P1D",
    "timeZone": "CET",
    "type": "period"
  },
  "intervals": "2017-03-14T23:00:00+00:00/2017-03-28T22:00:00+00:00",
  "queryType": "groupBy"
}
```

Most of the rows in the result have a normal `Z` (UTC) timezone:
```json
...
}, {
  "version" : "v1",
  "timestamp" : "2017-03-16T23:00:00.000Z",
  "event" : {
    "impressions" : 1042682811
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-17T23:00:00.000Z",
  "event" : {
    "impressions" : 1130282706
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-18T23:00:00.000Z",
  "event" : {
    "impressions" : 1141155536
  }
}, {
```

But sometimes random rows have a `+01:00` offset:
```json
...
}, {
  "version" : "v1",
  "timestamp" : "2017-03-22T23:00:00.000Z",
  "event" : {
    "impressions" : 856029534
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-24T00:00:00.000+01:00",
  "event" : {
    "impressions" : 835172754
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-24T23:00:00.000Z",
  "event" : {
    "impressions" : 833168201
  }
}, {
```

And even less times but still randomly some rows will even get a `+02:00` timezone **which them seems to use an incorrect hour**:
```json
...
}, {
  "version" : "v1",
  "timestamp" : "2017-03-25T23:00:00.000Z",
  "event" : {
    "impressions" : 733111118
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-27T00:00:00.000+02:00",
  "event" : {
    "impressions" : 772247551
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-27T22:00:00.000Z",
  "event" : {
    "impressions" : 834563685
  }
} ]
```
Or
```json
}, {
  "version" : "v1",
  "timestamp" : "2017-03-24T23:00:00.000Z",
  "event" : {
    "impressions" : 833168201
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-26T00:00:00.000+01:00",
  "event" : {
    "impressions" : 733111118
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-27T00:00:00.000+02:00",
  "event" : {
    "impressions" : 772247551
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-28T00:00:00.000+02:00",
  "event" : {
    "impressions" : 834563685
  }
} ]
```

**Comment by drcrallen** [comment]
By "use a different time zone" do you mean the machine system is on a different time zones, or that the query is in a non-UTC timezone?

**Comment by erikdubbelboer** [comment]
@drcrallen No all our machines are in UTC. I mean `granularity.timeZone` in the query JSON.

**Comment by jihoonson** [comment]
Maybe due to the summer time. Would you try with ```CEST```?

**Comment by erikdubbelboer** [comment]
@jihoonson `CEST` always returns `Z` so it seems to have something to do with summer time. But with `CET` it's completely random which days in the result have a different timezone each time I run the exact same report. My guess is some time instance (I have no idea how that code works) is being reused somewhere without resetting the timezone properly.

**Comment by jihoonson** [comment]
Looks weird.. When I test using almost same query on my local cluster, I god the following result which looks valid (https://github.com/JodaOrg/joda-time/blob/master/src/main/java/org/joda/time/DateTimeZone.java#L62).
```json
...
}, {
  "version" : "v1",
  "timestamp" : "1998-03-27T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2484
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-28T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2517
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-29T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2527
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-30T00:00:00.000+02:00",
  "event" : {
    "countSum" : 2578
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-31T00:00:00.000+02:00",
  "event" : {
    "countSum" : 2409
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-04-01T00:00:00.000+02:00",
  "event" : {
    "countSum" : 2454
  }
},
...
```

**Comment by erikdubbelboer** [comment]
@jihoonson maybe try it on the exact same dates as my query?

I uploaded 10 runs of the exact same query here so you can see the randomness: https://gist.github.com/erikdubbelboer/43b18dbe84d128609c3c1eb11ffdc066

Somewhat related: isn't it weird that when I run a query in `CET` I get result dates in `UTC`? Doesn't it make more sense to return the timestamps in `CET` then as well?

**Comment by jihoonson** [comment]
@erikdubbelboer yeah, it's also weird. 
The only difference of my query was the interval. I'll try with the exactly same one.

**Comment by jihoonson** [comment]
@erikdubbelboer I've tested with the same interval, but the result was correct as shown below. Here are my [ingestionSpec](https://gist.github.com/jihoonson/a5ef400e3e2e502d5e5de9ebfc7c56f9) and [query](https://gist.github.com/jihoonson/f1f2d26df406e681f019ebe3e61c0c3c).
```json
[ {
  "version" : "v1",
  "timestamp" : "1998-03-15T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2463
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-16T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2490
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-17T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2513
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-18T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2511
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-19T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2449
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-20T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2486
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-21T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2493
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-22T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2487
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-23T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2631
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-24T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2518
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-25T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2511
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-26T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2437
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-27T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2484
  }
}, {
  "version" : "v1",
  "timestamp" : "1998-03-28T00:00:00.000+01:00",
  "event" : {
    "countSum" : 2517
  }
} ]
```

**Comment by erikdubbelboer** [comment]
We create segments per day with a hourly granularity: [ingestion.json](https://gist.github.com/erikdubbelboer/7652a3238c01609332902d56a18a7f5c)
Also maybe the year matters as your data is still in 1998.

How can I help to find this bug using our cluster?

**Comment by jihoonson** [comment]
@erikdubbelboer I've tested after adjusting the timestamp of my data and changing the ingestionSpec accordingly, but got the correct result like below. 
```json
[ {
...
}, {
  "version" : "v1",
  "timestamp" : "2017-03-22T00:00:00.000+01:00",
  "event" : {
    "quantitySum" : 62781,
    "countSum" : 2465
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-23T00:00:00.000+01:00",
  "event" : {
    "quantitySum" : 65568,
    "countSum" : 2579
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-24T00:00:00.000+01:00",
  "event" : {
    "quantitySum" : 63920,
    "countSum" : 2474
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-25T00:00:00.000+01:00",
  "event" : {
    "quantitySum" : 64564,
    "countSum" : 2536
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-26T00:00:00.000+01:00",
  "event" : {
    "quantitySum" : 63360,
    "countSum" : 2490
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-27T00:00:00.000+02:00",
  "event" : {
    "quantitySum" : 62833,
    "countSum" : 2439
  }
}, {
  "version" : "v1",
  "timestamp" : "2017-03-28T00:00:00.000+02:00",
  "event" : {
    "quantitySum" : 62084,
    "countSum" : 2434
  }
} ]
```

Maybe there are some problems with your configurations or data. 
If you can, please share your configurations here. Also, if possible, please share any small snippet of your data.
It will be more helpful because other people can also have a chance to help you.

**Comment by erikdubbelboer** [comment]
@jihoonson that is strange. Did you run the query multiple times?

Here is part of our config, the ingestion spec, and some example data: https://gist.github.com/erikdubbelboer/7652a3238c01609332902d56a18a7f5c

**Comment by vihag** [comment]
@erikdubbelboer Did you find a resolution to this issue ? We are running into the same issue, our entire pipeline is in UTC and we are querying in the Asia/Singapore timezone. 
Segment Granularity : PT4H, Query Granularity : Hour.

**Comment by erikdubbelboer** [comment]
@vihag no we did not. The issue only seems to happen for us at summer/winter time change. Normally querying in other timezones works fine for us.

**Comment by erikdubbelboer** [comment]
@vihag Scratch that, it's still happening for us when we run queries in a timezone that adjusts with summer time, so CST6CDT or EST5EDT for example.

I guess Metamarkets, Imply and other companies that mostly commit to Druid don't allow their customers to run queries in these timezones.

The way we are fixing it now is to parse all the dates returned by druid and convert them back into the same timezone we want.

**Comment by gianm** [comment]
@erikdubbelboer, do you think you'd be able to write a unit test that shows the problem? If so, we can certainly fix it. It looks like so far the main thing stopping a fix is an inability to repro what you're seeing. I can't speak for everyone else, but at Imply we are definitely interested in having robust ability to query using non-UTC timezones.

**Comment by vihag** [comment]
@erikdubbelboer thank you for the confirmation, we are currently storing in UTC and querying at Asia/Singapore(+0800) time.

**Comment by erikdubbelboer** [comment]
@vihag  That is strange since Singapore doesn't have summer/winter time.

@gianm Do you have an example unit test that runs a query so I have something as a starting point?

**Comment by vihag** [comment]
It is strange indeed, we combed through our data if there were inconsistencies in out data / cluster etc. We couldn't find any.
^^ if possible, we would like to try and reproduce our issue via a unit test as well, we will need some guidelines though .

**Comment by jihoonson** [comment]
@erikdubbelboer hey, sorry for late response. I think ```GroupByQueryRunnerTest``` or ```ITIndexerTest``` might be a good example. I'll also run a test with your configurations and data set.

**Comment by jihoonson** [comment]
@erikdubbelboer I tried to reproduce the bug, but your data set contains the rows of the same timestamp which makes difficult to reproduce. I think the best for us is a unit test which can reproduce the bug as @gianm said.

**Comment by erikdubbelboer** [comment]
@jihoonson I'm trying to write a test now but the issue is that all tests just compare the DateTime instances ([like here](https://github.com/druid-io/druid/blob/ae900a493479bf0be2cef5ce598a6822caa3def1/api/src/main/java/io/druid/data/input/MapBasedRow.java#L186)) of the rows, which compares the unix timestamps which are correct. The issue is that the result JSON contains different timezones for different rows.

In our cluster I can reproduce this 100% of the time by just running a query in CET for any day with a hourly granularity. Each time I run the exact same query different rows will randomly have different timezones.

So it doesn't even have anything to do with summer time since CET is always winter time.

I suspect the bug is in the way the rows are serialized to JSON which I have no idea where in the code it is done yet or if there are tests for this.

So when I run a query for yesterday in CET for example I get rows back with a timezone of `2017-06-28T19:00:00.000+02:00` and other rows with a timezone of `2017-06-28T18:00:00.000Z`. If you convert them back to the same timezone the result is correct. It's only the JSON representation that is **weird** (not even strictly wrong).

**Comment by gianm** [comment]
@erikdubbelboer IIRC, DateTime equality includes timezone as well so you should be ok there. Although you're right. There are some serialization related code paths that aren't exercised in the query-runner unit tests.

Your description of the problem sounds possibly related to #4343… have you tried applying that patch? (It's available in 0.10.1-rc1, which you can get at http://druid.io/downloads.html)

**Comment by erikdubbelboer** [comment]
@gianm next week I'll upgrade our cluster to `0.10.1-rc1`. I'll let you know if it still happens after this.

**Comment by erikdubbelboer** [comment]
@gianm @jihoonson The issue seems to be fixed with `0.10.1-rc1`! Thanks.

**Comment by jihoonson** [comment]
@erikdubbelboer nice!

**Comment by gianm** [comment]
Thanks for confirming, @erikdubbelboer!
