### ISSUE TITLE
Tranquility Kafka Single DataSource From Multiple Topics?

### ISSUE THREAD

**Issue by Gowtham95india** [druid-io/druid#4144]
Is it possible to have single datasource from multiple Kafka topics ?

Like: 

```JSON
{
  "dataSources" : [
    {
      "spec" : {
        "dataSchema" : {
          "dataSource" : "vnk-clst",
          "parser" : {
            "type" : "string",
            "parseSpec" : {
              "format" : "json",
              "flattenSpec": {
                "useFieldDiscovery": true,
                "fields": []
              },
              "timestampSpec" : {
                "column" : "timestamp",
                "format" : "auto"
              },
              "dimensionsSpec" : {
                "dimensions" : [],
                "dimensionExclusions" : [
                  "timestamp",
                  "value"
                ]
              }
            }
          },
          "granularitySpec" : {
            "type" : "uniform",
            "segmentGranularity" : "hour",
            "queryGranularity" : "none"
          },
          "metricsSpec" : []
        },
        "ioConfig" : {
          "type" : "realtime"
        },
        "tuningConfig" : {
          "type" : "realtime",
          "maxRowsInMemory" : "100000",
          "intermediatePersistPeriod" : "PT10M",
          "windowPeriod" : "PT10M"
        }
      },
      "properties" : {
        "task.partitions" : "1",
        "task.replicants" : "1",
        "topicPattern" : "vtap_clickstream_1"
      }
    },
    {
      "spec" : {
        "dataSchema" : {
          "dataSource" : "vnk-clst",
          "parser" : {
            "type" : "string",
            "parseSpec" : {
              "format" : "json",
              "flattenSpec": {
                "useFieldDiscovery": true,
                "fields": []
              },
              "timestampSpec" : {
                "column" : "timestamp",
                "format" : "auto"
              },
              "dimensionsSpec" : {
                "dimensions" : [],
                "dimensionExclusions" : [
                  "timestamp",
                  "value"
                ]
              }
            }
          },
          "granularitySpec" : {
            "type" : "uniform",
            "segmentGranularity" : "hour",
            "queryGranularity" : "none"
          },
          "metricsSpec" : []
        },
        "ioConfig" : {
          "type" : "realtime"
        },
        "tuningConfig" : {
          "type" : "realtime",
          "maxRowsInMemory" : "100000",
          "intermediatePersistPeriod" : "PT10M",
          "windowPeriod" : "PT10M"
        }
      },
      "properties" : {
        "task.partitions" : "1",
        "task.replicants" : "1",
        "topicPattern" : "vtap_clickstream_2"
      }
    }
  ],
  "properties" : {
    "zookeeper.connect" : "10.2.1.239",
    "druid.discovery.curator.path" : "/druid/discovery",
    "druid.selectors.indexing.serviceName" : "druid/overlord",
    "commit.periodMillis" : "15000",
    "consumer.numThreads" : "2",
    "kafka.zookeeper.connect" : "10.2.40.48",
    "kafka.group.id" : "tranquility-kafka",
    "serialization.format" : "smile",
    "druidBeam.taskLocator": "overlord"
  }
}
```

We have multi-tenancy architecture,  where each tenancy will be producing to their individual topics. So can we have something like the above mentioned in which all the details will be stored to single datasource at the end?

**Comment by dclim** [comment]
@Gowtham95india Tranquility Kafka allows you to specify a topicPattern, so you should be able to use "topicPattern": "vtap_clickstream_*" to accomplish what you want. Does this work for you?

For reference: https://github.com/druid-io/tranquility/blob/master/docs/kafka.md#matching-topics-to-data-sources

**Comment by Gowtham95india** [comment]
@dclim Hey thanks for the suggestion. 

But the above one I shared as example. On high level, we have around 15 services running. As of now, among those 15 services, 3 services will produce messages to different topics like 

discovery_engine_stats_1, vigeon_notifs_1, shopping_cart_orders_1,
discovery_engine_stats_2, vigeon_notifs_2, shopping_cart_orders_2,

So, here is the doubt I have: 

If my topics names are like the one I mentioned above, then I can simply use *_1 for vnk-clst datasource, and *_2 for mrv-clst ? Correct me if I'm wrong! 

Thanks in advance!

**Comment by dclim** [comment]
@Gowtham95india sorry I gave you a bad example - the topicPattern is actually a regex, so you can craft a regex that matches the topics you want to read into a datasource. In my example, it should actually have been something like `vtap_clickstream_.*` And yes, in your case you can do `.*_1`, or if you want to be explicit you can use something like topicPattern `discovery_engine_stats_1|vigeon_notifs_1|shopping_cart_orders_1`

**Comment by Gowtham95india** [comment]
@dclim 

Yea, thanks for the hint. I'll try and let you know. If required will reopen the issue. Closing  it now. Thanks :) 👍

**Comment by SpotXPeterCunningham** [comment]
HI Guys,

So my question is the similar except I want to have a slightly different ingestion spec for both topics but ultimately pointing at the same datasource in Druid.

I would like to be able to map multiple topics to a single data source, however I would like to ignore several of the metrics when consuming events from one of the topics. I would like to use it as a way to delta ingest delayed events and update one of the metrics against the existing record.

I.e a message arrives on topic 1 with a set of dimensions and 5 metrics. A few minutes later a message arrives on topic 2 with all the same dimensions and 5 metrics repeated plus an additional metric. I would like to update the aggregated records in Druid that matches the dimensions with the additional metric. I.e only take into consideration one of the metrics in the ingestion spec from the 2nd topic.

Is this possible ?

Thanks
Pete
