### ISSUE TITLE
a problem of 99% availability

### ISSUE THREAD

**Issue by mjaow** [druid-io/druid#4172]
in my coordinator page,i found the available percent of one of my server is >99%.Other is full available.I realize there is 2 segment left to load when I check the api /druid/coordinator/v1/loadstatus?full. Then I check the code of api.I found that the number 2 is result of`entry.getValue()-segmentReplicantLookup.getTotalReplicants(segment.getIdentifier(), entry.getKey()`.I guess the entry.getValue() is the number of  tier replication which is 2.It means the result of 
`segmentReplicantLookup.getTotalReplicants(segment.getIdentifier(), entry.getKey()` is 0.How did it happen,maybe just lose some segment ? I was puzzled

**Comment by knoguchi** [comment]
I think you lost some segments (for whatever the reasons).   I believe the problem would go away If you re-compute the lost segments for the time range by batch process.

**Comment by mjaow** [comment]
@knoguchi yeah,i think you are right.Thx
