### ISSUE TITLE
Kafka Index Task should remember end offsets set by supervisor

### ISSUE THREAD

**Issue by pjain1** [druid-io/druid#4177]
Kafka Index Task cannot restore end offsets set by supervisor if the middleManager restarts after end offsets have been set and the task is not complete yet. Thus, it can keep on consuming records that it should not after restore.

**Comment by gianm** [comment]
Will likely be part of #4178.

**Comment by pjain1** [comment]
Fixed in https://github.com/druid-io/druid/pull/4815
