### ISSUE TITLE
query timeouts not honored if broker takes extra time

### ISSUE THREAD

**Issue by himanshug** [druid-io/druid#4181]
if all historicals (and peon) respond within the query timeout specified and it is broker spending time doing the merge (usually in the case of merging lots of sketches) then timeout wouldn't be honored irrespective of however long broker takes to merge things.

on the client side, clients typically use the same timeout to close the connection... so broker doing all the work is eventually wasted.

one possibly simple (maybe crude) fix is that broker puts query processing `startTime` in query context and all things taking time to process the query continuously watch the time spent and fail if it exceeds. I'm imagining probably in QueryToolChest.mergeResults(..) impl and may be in the QueryResource where it is streaming the results to response.

another alternative to `startTime` would be to do query processing in a thread pool and cancel the future on query timeout .... druid code that takes time in processing the query would continuously check if the thread is interrupted.

**Comment by drcrallen** [comment]
Related to https://github.com/druid-io/druid/issues/1415

**Comment by himanshug** [comment]
duplicate of #1415
