### ISSUE TITLE
dump segment tool

### ISSUE THREAD

**Issue by mjaow** [druid-io/druid#4192]
>The DumpSegment tool can be used to dump the metadata or contents of a segment for debugging purposes. Note that the dump is not necessarily a full-fidelity translation of the segment. In particular, not all metadata is included, and complex metric values may not be complete

i need the use the tool to dump my segment in product environment.It describe that some complex metric value is not complete.Which are they?I need to ensure all of my dimension and metrics will be dump out.Thx for reply

**Comment by gianm** [comment]
I think hyperUnique and approxHistogram should be okay, maybe others too. I'm not totally sure though, you should double check if it matters to you.

**Comment by mjaow** [comment]
@gianm yeah,hyperUnique is ok.I need to check it indeed.thx
