### ISSUE TITLE
SQL: IN filters do not work with >= 20 elements

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#4203]
This is because Calcite's SqlToRelConverter converts INs of <20 elements to ORs (which then convert back into a Druid InDimFilter) and INs of >= 20 elements to a join on an inline table (which we can't plan).

**Comment by gianm** [comment]
This should be solvable when Calcite 1.14 is released, by using the functionality from https://issues.apache.org/jira/browse/CALCITE-1874 to disable the inline table conversion.

**Comment by chiragbhalodia** [comment]
I want to set config having withInSubQueryThreshold set to some bigger value than default.
For example:
Config config = SqlToRelConverter.configBuilder().withInSubQueryThreshold(1000).build();

How do I set this config so that it will be picked up by calcite for any query execution?
