### ISSUE TITLE
Remove ability to build v8 segment format

### ISSUE THREAD

**Issue by leventov** [druid-io/druid#4235]
It's possible to make segment merging more in-memory and reduce the time needed for segment merging by 50%, but it doesn't work (failing with OOM errors) when v8 segment format is build first, and then converted to v9.

I don't see a way to keep the ability to merge segments in v8 format and make the improvement without massive code duplication (because v8 and v9 use the same classes on certain level).

If we remove ability to build v8, on the contrary, some code could be removed. But not all v8-related, because segments in this format should be still readable.

**Comment by gianm** [comment]
Out of curiosity, what kind of changes would be possible if we removed the ability to write v8?

**Comment by leventov** [comment]
It is explained in the issue body: in-memory merge

**Comment by gianm** [comment]
I meant to ask about some specific classes and methods.

**Comment by leventov** [comment]
@gianm all classes implementing Serializer interface, *Writers, see https://github.com/metamx/druid/commit/f1eb2c8e7dc97e5e9554231fdaf90c486b2ecb81
