### ISSUE TITLE
Query Data w/ Windows cURL?

### ISSUE THREAD

**Issue by minoobeyzavi** [druid-io/druid#4242]
Hello,

I ssh into a linux virtual machine where my Druid services are running and cURL/.json queries return .json responses. I'm trying to use the same query system with cURL on Windows command line to receive data from my linux host's IP address and so far haven't been able to receive a .json response.

I know that Druid does not support Windows installation but is there a reason I shouldn't be able to query data from the command line?

Any tips or suggestions would be much appreciated!

**Comment by drcrallen** [comment]
As long as the http transport is functional and to spec (aka, no weird firewall rules on the druid side or the windows side) you should be able to use almost anything from any OS, including postman extensions for browsers.

**Comment by minoobeyzavi** [comment]
Thanks, I just succeeded with Postman!

*Minoo Beyzavi*

Data Science Fellow
minoo.beyzavi@gmail.com <maryann.barge@galvanize.com>
612-978-9693 <925-878-5828> (mobile)

44 Tehama Street | SF, CA 94105
