### ISSUE TITLE
SQL: Spurious 'table not found'

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#4258]
Some users have reported `Table 'xxx' not found` errors that (sometimes) resolve when restarting brokers. Seems like something off with the metadata caching.

See https://groups.google.com/d/topic/druid-user/A_C9pKWzc0M/discussion for context.

**Comment by gianm** [comment]
I got a report recently that someone got this error consistently when using non-sticky load balancing. The Avatica server doesn't share connection state between brokers so it is totally believable that something would go wrong. Although, the error message is a weird one to get in that case.

**Comment by richiesgr** [comment]
Hi
I'm using imply 2.4.0 version and the problem still exists
after restarting the broker the SQL server lose the metadata of the data source.
After some time it come back but not always 
Is there any workaround ?
Thanks
