### ISSUE TITLE
SQL Having clause isn't working with field created via division

### ISSUE THREAD

**Issue by benvogan** [druid-io/druid#4264]
The following query results in a "Cannot build plan for query" error:

SELECT FLOOR(__time TO DAY), location_id, product_family_id, CAST(COUNT(*) FILTER(WHERE event_status <> 'success') AS FLOAT)/COUNT(*) AS scan_error_rate FROM sor_business_events_all WHERE event_type='product_scan' and __time > TIMESTAMP '2017-05-07 00:00:00' AND __time < TIMESTAMP '2017-05-10 00:00:00' GROUP BY FLOOR(__time TO DAY), location_id, product_family_id HAVING CAST(COUNT(*) FILTER(WHERE event_status <> 'success') AS FLOAT)/COUNT(*) = 1

**Comment by gianm** [comment]
Would be fixed by #4360.

**Comment by gianm** [comment]
Fixed by #4360.
