### ISSUE TITLE
The behaviour of period granularity in query is different from what is described  in doc in 0.10.0

### ISSUE THREAD

**Issue by elloooooo** [druid-io/druid#4276]
In doc Period Granularities are described as:
1. They support specifying a time zone which determines where period boundaries start
2. as well as the timezone of the returned timestamps

I run druid in UTC time. In my timeseries query,  
This is intervals `"intervals":["2017-05-14T00:00:00.000+08:00/2017-05-16T00:00:00.000+08:00"]`, this is granularity `"granularity":{"period":"P1D","timeZone":"Asia/Shanghai","type":"period"}`,
And this is what I got

> [
     {
       "timestamp": "2017-05-13T16:00:00.000Z",
       "result": {
       "error_count": 6154866,
       "sum_count": 353336733
    }
  },
  {
    "timestamp": "2017-05-14T16:00:00.000Z",
    "result": {
      "error_count": 6115738,
      "sum_count": 357000114
    }
  }
]

The result is correct according to the first description as it start the time bucket from UTC 16:00:00, but according to second description, the timestamp in result are supposed to `2017-05-14T00:00:00.000+08:00` and `2017-05-15T00:00:00.000+08:00` and they are in 0.9.2.

So, is it a bug to fix?

**Comment by gianm** [comment]
Thanks for the report @elloooooo. I marked this 0.10.1 to remind us to check it out before the release.

**Comment by himanshug** [comment]
@praveev can you take a look at this one ?

**Comment by praveev** [comment]
ya. able to reproduce this issue for "Asia/Shanghai"

**Comment by jon-wei** [comment]
@praveev Did you have a chance to investigate further/make a fix for this issue?

**Comment by praveev** [comment]
Yes. still investigating.

Thought this was a data issue when i first read the description. but that's not the case. its just that the timestamp is not represented in offset.

**Comment by jon-wei** [comment]
Fixed by https://github.com/druid-io/druid/issues/4343
