### ISSUE TITLE
Possible bug with concurrent modification of QueryMetrics

### ISSUE THREAD

**Issue by leventov** [druid-io/druid#4279]
Reported here: https://github.com/druid-io/druid/pull/3954#issuecomment-301583481

Possible fix: https://github.com/druid-io/druid/files/1002579/queryPlus.txt

Similar to #3803

@pjain1

**Comment by pjain1** [comment]
can you please do it in branch, that would be easier to test ?

**Comment by leventov** [comment]
@pjain1 https://github.com/druid-io/druid/tree/queryMetrics-concurrency-fix

**Comment by pjain1** [comment]
@leventov thanks

**Comment by himanshug** [comment]
@leventov its passing our integration testing env. please do the pr.

**Comment by pjain1** [comment]
@leventov I tried this and integration tests seems to be passing

**Comment by leventov** [comment]
@himanshug @pjain1 please check #4288
