### ISSUE TITLE
Rest call with timezone is malformed

### ISSUE THREAD

**Issue by BerryOsterlund** [druid-io/druid#4322]
When calling the Broker Rest interface to get a list of candidates with the /druid/v2/datasources/<DATASOURCE>/candidates?intervals= call, you get a response saying it's an invalid format when the timediff is included. Problem is that the Hive connection is sending that, so for some queries, you just get errors in Hive.

This works correctly
curl <HOSTNAME>:8082/druid/v2/datasources/<DATASOURCE>/candidates?intervals=1900-01-01T00:00:00.000/3000-01-01T00:00:00.000

This call failes
curl <HOSTNAME>:8082/druid/v2/datasources/<DATASOURCE>/candidates?intervals=1900-01-01T00:00:00.000+01:00/3000-01-01T00:00:00.000+01:00

HTTP ERROR: 500
Problem accessing /druid/v2/datasources/druid_sqoop_import_02/candidates. Reason: java.lang.IllegalArgumentException: Invalid format: "1900-01-01T00:00:00.000 01:00" is malformed at " 01:00"

Environment is Hortonworks HDP 2.6 together with the supplied Druid version 0.9.2

**Comment by gianm** [comment]
I think you need to escape the `+` as `%2B`. It's getting treated as a space.

**Comment by BerryOsterlund** [comment]
I 100% agree with you. Problem is that this is not me writing these intervals in the Hive SQL statement. Thats something that Hive is adding automaticly.  Just to be sure. Is this the correct place to repost these kind of  issues about the Hive-Druid connection, or should I do that somewhere else?

**Comment by gianm** [comment]
Ah, if this is being generated by Hive then please file a bug with the Hive project. The Druid-Hive code lives over there.

**Comment by nishantmonu51** [comment]
related HIVE issue which fixes this - https://issues.apache.org/jira/browse/HIVE-16576
