### ISSUE TITLE
how can i dump pre-computed HLL to origin value 

### ISSUE THREAD

**Issue by mjaow** [druid-io/druid#4329]
i found the metric tagged by HyperUnique is display as pre-computed HLL (base64 encoded string).How can i deserialize the base64 string to origin value

**Comment by gianm** [comment]
Do you mean the original value from your input data? It's not preserved (HLL is lossy) so you can't decode that. But you can load it into a Druid HyperLogLogCollector object if you want to look at it -- check out HyperUniqueSerde for an example.
