### ISSUE TITLE
Guice PolyBind - must fail with error if specified value not found, instead of binding the default

### ISSUE THREAD

**Issue by leventov** [druid-io/druid#4369]
When there is a polyBind:
```java
PolyBind.createChoice(binder, "key", Key.get(Foo.class), Key.get(DefaultFooImpl.class));
```

And the value in config `key=nonFound` couldn't be found in classpath, dependency injection must fail with error instead of using `DefaultFooImpl`.

**Comment by jihoonson** [comment]
Is it for avoiding ```class not found error``` when DefaultFooImpl class is also not in classpath?

**Comment by leventov** [comment]
No, DefaultFooImpl could not be out of classpath since it is directly referenced in code. The motivation for this issue was the situation when we configured `someConfig=someCustomOptionFromOurExtension`, but forgot to bundle that extension, and then `someConfig` was initalized with the default option and was working normal, despite that we expected that `someCustomOptionFromOurExtension` should work.

**Comment by gianm** [comment]
It's possible that some config in the integration tests is broken in that same way, and it's actually a bug with the integration tests.
