### ISSUE TITLE
special char && can not parser for sql 

### ISSUE THREAD

**Issue by shilicqupt** [druid-io/druid#4378]
For a datasource,  I have a special field name &&name, I use the following sql to get result

- example1
{"query":"SELECT host from opentsdb_20s where __time > TIMESTAMP '2017-06-06 16:30:00' and `&&name`='flume.sink.swift.sendwaittime' limit 10"}

- result
{
  "error": "Unknown exception",
  "errorMessage": "Lexical error at line 1, column 82.  Encountered: \"`\" (96), after : \"\"",
  "errorClass": "org.apache.calcite.sql.parser.SqlParseException",
  "host": null
}

- example2
{"query":"SELECT host from opentsdb_20s where __time > TIMESTAMP '2017-06-06 16:30:00' and \\&\\&name='flume.sink.swift.sendwaittime' limit 10"}

- result
{
  "error": "Unknown exception",
  "errorMessage": "Lexical error at line 1, column 82.  Encountered: \"`\" (96), after : \"\"",
  "errorClass": "org.apache.calcite.sql.parser.SqlParseException",
  "host": null
}

- example3
{"query":"SELECT host from opentsdb_20s where __time > TIMESTAMP '2017-06-06 16:30:00' and \&\&name='flume.sink.swift.sendwaittime' limit 10"}

- result
Error 500

so is it a bug for the sql feature

**Comment by gianm** [comment]
You should be able to escape it with double quotes, like:

```
{"query":"SELECT host from opentsdb_20s where __time > TIMESTAMP '2017-06-06 16:30:00' and \"&&name\"='flume.sink.swift.sendwaittime' limit 10"}
```

**Comment by shilicqupt** [comment]
I got it, thanks @gianm
