### ISSUE TITLE
Druid 0.10.1 release notes

### ISSUE THREAD

**Issue by jon-wei** [druid-io/druid#4384]
# DRAFT

Druid 0.10.1 contains hundreds of performance improvements, stability improvements, and bug fixes from over 40 contributors. Major new features include:
- Large performance improvements and additional query metrics for TopN queries
- The ability to push down limit clauses for GroupBy queries
- More accurate query timeout handling
- Hadoop indexing support for the Amazon S3A filesystem
- Support for ingesting Protobuf data
- A new Firehose that can read input via HTTP
- Improved disk space management when indexing from cloud stores
- Various improvements to coordinator lookups management
- A new Kafka metrics emitter
- A new dimension comparison filter
- Various improvements to Druid SQL

If you are upgrading from a previous version of Druid, please see "Updating from 0.10.0 and earlier" below for upgrade notes, including some backwards incompatible changes.

The full list of changes is here: https://github.com/druid-io/druid/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20milestone%3A0.10.1

Documentation for this release is at: http://druid.io/docs/0.10.1/

### TopN performance improvements
Processing for TopN queries with 1-2 aggregators on historical nodes is now 2-4 times faster. This is accomplished with new runtime inspection logic that generates monomorphic implementations of query processing classes, reducing polymorphism in the TopN query execution path.

Added in a series of PRs described here by @leventov: https://github.com/druid-io/druid/issues/3798.

### Limit clause push down for GroupBy
Druid can now optimize limit clauses in GroupBy queries by distributing the limit application to historical/realtime nodes, applying the limit to partial result sets before they are sent to the broker for merging. This reduces network traffic within the cluster and reduces the merging workload on broker nodes. Please refer to http://druid.io/docs/0.10.1/querying/groupbyquery.html#query-context for more information.

Added in https://github.com/druid-io/druid/pull/3873 by @jon-wei.

### Hadoop indexing support for Amazon S3A
Amazon's S3A filesystem is now supported for deep storage and as an input source for batch ingestion tasks. Please refer to <> for documentation.

Added in https://github.com/druid-io/druid/pull/4116 by @b-slim.

### Protobuf 3.0 support and other enhancements
Support for ingesting Protobuf 3.0 data has been added, along with other enhancements such as reading Protobuf descriptors from a URL. Protobuf-supporting code has been moved into its own core extension as well. See http://druid.io/docs/0.10.1/development/extensions-core/protobuf.html for documentation.

Added in https://github.com/druid-io/druid/pull/4039 by @knoguchi.

### HTTP Firehose
A new Firehose for realtime ingestion that reads data from a list of URLs via HTTP has been added. Please see http://druid.io/docs/latest/ingestion/firehose.html#httpfirehose for documentation.

Added in https://github.com/druid-io/druid/pull/4297 by @jihoonson.

### Improved disk space management for realtime indexing from cloud stores
The Firehose implementations for Microsoft Azure, Rackspace Cloud Files, Google Cloud Storage, and Amazon S3 now support caching and prefetching of data. These firehoses can now operate on portions of the input data and pull new data as needed, instead of having to fully read the firehose's input to disk.

Please refer to the following links for documentation:
http://druid.io/docs/0.10.1/development/extensions-contrib/azure.html
http://druid.io/docs/0.10.1/development/extensions-contrib/cloudfiles.html
http://druid.io/docs/0.10.1/development/extensions-contrib/google.html
http://druid.io/docs/0.10.1/development/extensions-core/s3.html

Added in https://github.com/druid-io/druid/pull/4193 by @jihoonson.

### Improvements to coordinator lookups management
Several enhancements have been made to the state management/synchronization logic for query-time lookups, including versioning of lookup specs. Please see http://druid.io/docs/0.10.1/querying/lookups.html for documentation.

Added in https://github.com/druid-io/druid/pull/3855 by @himanshug.

### Kafka metrics emitter
A new metrics emitter that sends metrics data to Kafka in JSON format has been added. See http://druid.io/docs/0.10.1/development/extensions-contrib/kafka-emitter.html

Added in https://github.com/druid-io/druid/pull/3860 by @dkhwangbo.

### Column comparison filter
A new column comparison filter has been added. This filter allows the user to compare values across columns within a row, like a "WHERE columnA = columnB" clause in SQL. See http://druid.io/docs/0.10.1/querying/filters.html#column-comparison-filter for documentation.

Added in https://github.com/druid-io/druid/pull/3928 by @erikdubbelboer.

### Druid SQL improvements
Druid 0.10.1 has a number of enhancements to Druid SQL, such as support for lookups (PRs by @gianm):

https://github.com/druid-io/druid/pull/4368 - More forgiving Avatica server
https://github.com/druid-io/druid/pull/4109 - Support for another form of filtered aggregator
https://github.com/druid-io/druid/pull/4085 - Rule to collapse sort chains
https://github.com/druid-io/druid/pull/4055 - Add SQL REGEXP_EXTRACT function
https://github.com/druid-io/druid/pull/3991 - Make row extractions extensible and add one for lookups
https://github.com/druid-io/druid/pull/4028 - Support for coercing to DECIMAL
https://github.com/druid-io/druid/pull/3999 - Ability to generate exact distinct count queries

### Other performance improvements
Druid 0.10.1 has a number of other performance improvements, including:

https://github.com/druid-io/druid/pull/4364 - Uncompress streams without having to download to tmp first, by @niketh
https://github.com/druid-io/druid/pull/4315 - Server selector improvement, by @dgolitsyn
https://github.com/druid-io/druid/pull/4110 - Remove "granularity" from IngestSegmentFirehose, by @gianm
https://github.com/druid-io/druid/pull/4038 - serialize DateTime As Long to improve json serde performance, by @kaijianding

### And much more!
The full list of changes is here: https://github.com/druid-io/druid/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20milestone%3A0.10.1

## Updating from 0.10.0 and earlier
Please see below for changes between 0.10.0 and 0.10.1 that you should be aware of before upgrading. If you're updating from an earlier version than 0.10.0, please see release notes of the relevant intermediate versions for additional notes.

### Deprecation of support for Hadoop versions < 2.6.0
To add support for Amazon's S3A filesystem, Druid is now built against Hadoop 2.7.3 libraries, and we are deprecating support for Hadoop versions older than 2.6.0.

For users running a Hadoop version older than 2.6.0, it is possible to continue running Druid 0.10.1 with the older Hadoop version using a workaround.

The user would need to downgrade `hadoop.compile.version` in the main Druid pom.xml, remove the `hadoop-aws` dependency from pom.xml in the `druid-hdfs-storage` core extension, and then rebuild Druid.

Users are strongly encouraged to upgrade their Hadoop clusters to a 2.6.0+ version as of this release, as support for Hadoop <2.6.0 may be dropped completely in future releases.

Users should also update any existing `druid.indexer.task.defaultHadoopCoordinates` configurations to 2.7.3 versions.

### Kafka Broker Changes
Due to changes from https://github.com/druid-io/druid/pull/4115, the Kafka indexing service is no longer compatible with version 0.9.x Kafka brokers. Users will need to upgrade their Kafka brokers to an 0.10.x version.

### Coordinator Lookup Management Changes
https://github.com/druid-io/druid/pull/3855 introduces various improvements to coordinator lookup propagation behavior. Please see http://druid.io/docs/0.10.1/querying/lookups.html for details. Note the changes to coordinator HTTP API regarding lookups management.

If Lookups are being used in prior deployment, then as part of upgrade to 0.10.1, All coordinators should be stopped, upgraded, and then started with version 0.10.1 at one time rather than upgrading them one at a time. There should never be a situation where one coordinator is running 0.10.0 while other coordinator is running 0.10.1 at the same time.

During the course of the cluster upgrade, lookup query nodes will report an error starting with `got notice to load lookup [LookupExtractorFactoryContainer{version='null'`. This is not actually an error and is a side effect of the update. See https://github.com/druid-io/druid/issues/4603 for details.

### Off-heap query-time lookup cache
Please note that the off-heap query-time lookup cache is broken at this time because of an excessive memory use issue, and must not be used:
https://github.com/druid-io/druid/issues/3663

### Rolling updates
The standard Druid update process described by http://druid.io/docs/0.10.1/operations/rolling-updates.html should be followed for rolling updates.

## Credits

Thanks to everyone who contributed to this release!

@akashdw
@amarjayr
@asdf2014
@asrayousuf
@b-slim
@cesure
@cxmcc
@dclim
@dgolitsyn
@dkhwangbo
@drcrallen
@elloooooo
@erikdubbelboer
@fanjieqi
@Fokko
@freakyzoidberg
@fuji-151a
@gianm
@gkc2104
@himanshug
@hzy001
@JackyWoo
@Jdban
@jeffhartley
@jerchung
@jihoonson
@jon-wei
@kaijianding
@KenjiTakahashi
@knoguchi
@leventov
@licl2014
@logarithm
@niketh
@nishantmonu51
@pjain1
@praveev
@ramiyer
@sascha-coenen
@satishbhor
@sixtus
@sjvs
@skyler-tao
@xanec
@zhihuij
@zwang180

**Comment by gianm** [comment]
@himanshug Do we need to resolve https://github.com/druid-io/druid/pull/4281 before releasing 0.10.1?

**Comment by gianm** [comment]
Also, @himanshug, is this bit from the draft release notes correct (with regard to QTL)

> The standard Druid update process described by http://druid.io/docs/0.10.1/operations/rolling-updates.html should be followed for rolling updates.

**Comment by Fokko** [comment]
Awesome work guys! Would it be possible to also add [Parquet Date-column support into 0.10.1](https://github.com/druid-io/druid/pull/4423)?

**Comment by gianm** [comment]
Thanks @Fokko and thanks also for your contributions to this release. 0.10.1 is code-frozen at this point (other than blocker bug fixes) so #4423 will be included in the next release, 0.11.0. Even though 0.10.1 hasn't been released yet, 0.11.0 is already well underway, with 19 new patches (including yours): https://github.com/druid-io/druid/milestone/23?closed=1

**Comment by Fokko** [comment]
Thanks for the explanation. Lets wait for 0.11.0 then. Thanks!

**Comment by himanshug** [comment]
@gianm i think 0.10.1 fulfills the updated rolling upgrade contract in #4281 , so 0.10.1 is alright.

**Comment by john-bodley** [comment]
@jon-wei under the **Updating from 0.10.0 and earlier** section, should the following, 
> Users should also update any existing druid.indexer.task.defaultHadoopCoordinates configurations to 2.7.3 versions. 

read

> Users should also update any existing druid.indexer.task.defaultHadoopCoordinates configurations to _non_-2.7.3 versions.

**Comment by jon-wei** [comment]
@john-bodley I clarified that part a bit, this was the intended meaning:

>If users wish to use Hadoop 2.7.3 as default for ingestion tasks, users should double check any existing `druid.indexer.task.defaultHadoopCoordinates` configurations.

**Comment by vdnhat** [comment]
I hope in the nearest version . Druid will released Window Functions features .
