### ISSUE TITLE
PROPOSAL: refactor mysql storage code to injectable interfaces

### ISSUE THREAD

**Issue by realfun** [druid-io/druid#453]
Proposal
-----------

In general Druid architecture is really good, I learnt a lot reading druid code, but there are 2 places where I feel that could be improved:

 * DbConnectorModule should be extracted as something like CoordinationStorage interface, which wraps all the current DB operations as methods(currently there are sql queries in many places), like listSegments, dropSegment, etc.

 * io.druid.initialization.Initialization should only load interfaces or register configs. Stuff like DbConnectorModule should be injectable

With these, one can easily replace mysql module to S3 or any online storage that has SLA guaranteed.

Background
----------------

Our team started exploring Druid in an internal system, after reading the design documents of Druid, I found mysql is the only thing that worries me, there are plenty of storage options that is more stable and instantly available both internally and externally.

I wrote my main function and copy over all the functions in io.druid.cli.Main by only replacing CliCoordinator and CliRealtime, where we register DatabaseSegmentManager and DatabaseRuleManager to our own class using internal storage. In the runtime.properties for database configs I put a random config that points to localhost(which does not exist).

This works fine for a few days because we replaced DatabaseSegmentManager and DatabaseRuleManager, no real DB connection was made.

It fails today when I tried to upgrade to 0.6.73(was on 0.6.61.1), where druid tries to connect to mysql database to detect whether it is postgresql or not(https://github.com/metamx/druid/commit/d089f05127899c76ece7599adc4dfaacc4842d04). To fix it I either have to fake a sql server or make custom druid build. I feel there is a better way to solve this so writing this proposal.

--
Frank

**Comment by fjy** [comment]
I am closing this as the metadata store is now pluggable.
