### ISSUE TITLE
Ambari Metrics Emitter extension build is failing

### ISSUE THREAD

**Issue by pjain1** [druid-io/druid#4537]
While building the project using maven, it is failing with following error -

```
[ERROR] Failed to execute goal on project ambari-metrics-emitter: Could not resolve dependencies for project io.druid.extensions.contrib:ambari-metrics-emitter:jar:0.11.0-SNAPSHOT: Failed to collect dependencies at org.apache.ambari:ambari-metrics-common:jar:2.4.1.0.22: Failed to read artifact descriptor for org.apache.ambari:ambari-metrics-common:jar:2.4.1.0.22: Could not transfer artifact org.apache.ambari:ambari-metrics-common:pom:2.4.1.0.22 from/to hortonworks (http://repo.hortonworks.com/content/repositories/releases): Failed to transfer file: http://repo.hortonworks.com/content/repositories/releases/org/apache/ambari/ambari-metrics-common/2.4.1.0.22/ambari-metrics-common-2.4.1.0.22.pom. Return code is: 500 , ReasonPhrase:Server Error. -> [Help 1]
```
Looks like the hortonworks artifactory is returning 500.

The build started failing in our build machines, but supposedly was working fine locally. However, after deleting the cached jars from local maven repo, it started failing locally as well. I am not sure why travis is not failing, probably it also caches the jars ? Is anyone able to reproduce after deleting the cached jars ? 

@nishantmonu51 or @b-slim can you have a look ?

**Comment by b-slim** [comment]
ok let me look

**Comment by b-slim** [comment]
@pjain1 i run `mvn -U dependency:copy-dependencies` from my local machine and it is working fine. Which cache did you deleted ?

**Comment by pjain1** [comment]
I did this - `rm -r ~/.m2/repository/org/apache/ambari` and ran the build locally and the build failed.

**Comment by akashdw** [comment]
@b-slim Should it come from mvn central or hortonworks repo b/c mvn cnetral has this artifact, looks like hortonworks repo is returning 500.

referring to https://github.com/druid-io/druid/blob/ae900a493479bf0be2cef5ce598a6822caa3def1/extensions-contrib/ambari-metrics-emitter/pom.xml#L88

**Comment by b-slim** [comment]
i guess you are right the public one (was using private) is empty repo `http://repo.hortonworks.com/content/repositories/releases/org/apache/ambari/ambari-metrics-common/2.4.1.0.22/`
let me see why the jars is not there.

**Comment by b-slim** [comment]
@pjain1 try now, should be fixed, thanks for reporting.

**Comment by pjain1** [comment]
It worked, thanks for the quick fix. Are you guys considering publishing to central maven, might be useful.

**Comment by rae89** [comment]
I am having this same issue when trying to build druid from the dockerfile thats currently in master.
