### ISSUE TITLE
What is the syntax for adding a sort order?

### ISSUE THREAD

**Issue by donpinkus** [druid-io/druid#4545]
I've searched the docs (http://druid.io/docs/latest/querying/sorting-orders.html) and issues in this github repo - and I can't find the syntax to add a sort order to a query.

So, what is the syntax for adding sort order? 

Here is a basic groupBy query meant to illustrate the issue. How would you add a numeric sort order to it on the column 'purchase_size'?

```
{
  "queryType": "groupBy",
  "dataSource": "purchases",
  "granularity": "all",
  "dimensions": ["person", "item"],
  "aggregations": [
	  {
	    "type": "longMax",
	    "name": "purchase_size",
	    "fieldName": "purchase_amount"
	  }
  ],
  "intervals": [
    "2017-01-01T00:00:00.000Z/2017-07-30T00:00:00.000Z"
  ]
}
```

**Comment by akashdw** [comment]
donpinkus, you can specify sort order using GroupByQuery's LimitSpec. 

``` 
"limitSpec":{"type":"default","columns":
[{"dimension":"purchase_amount","direction":"descending","dimensionOrder":
{"type":"lexicographic"}}],"limit":2147483647}
```

More details here http://druid.io/docs/latest/querying/limitspec.html

**Comment by donpinkus** [comment]
Thanks @akashdw - which queries in Druid are sortable?

**Comment by donpinkus** [comment]
# Which queries in Druid are sortable, and what is the syntax?

Someone wrote a docs page, without actually documenting the API / syntax. 
http://druid.io/docs/latest/querying/sorting-orders.html

**Comment by jon-wei** [comment]
those sorting orders are just string names for comparators, they're not an object that you attach to a query, this part of the doc you linked to points to the syntax in the contexts where these comparator names are used:

>These sorting orders are used by the TopNMetricSpec, SearchQuery, GroupByQuery's LimitSpec, and BoundFilter.

**Comment by donpinkus** [comment]
@jon-wei thanks for the quick answer. 

So I want to sort by a column in a "select" query. 

Is that possible? (not sure how I find this out)
If so, what is the syntax? Is there an example of a select query that uses a sort order?

**Comment by jon-wei** [comment]
@donpinkus 

The docs could certainly be improved; I would say the current "rule" for whether the query supports sorting is "if there's nothing in the query specific docs that mention user configurable sorting, it's not supported."

Select will only order by time, the most you can configure there is whether you want ascending or descending ordering by time.

**Comment by donpinkus** [comment]
@jon-wei got it. 

So in SQL:

```
SELECT *
FROM my_table
ORDER BY col_a DESC
LIMIT 10
```

Is that possible in Druid? 

Should I be writing some awkward GroupBy query, where I try not to actually GroupBy anything?

**Comment by gianm** [comment]
@donpinkus that query is not possible (in fact you could run it with Druid SQL and it will complain that it's not plannable).

In general, I guess, Druid is really best for aggregation workloads and the "select" functionality (such as it is) is not as well developed as the aggregation functionality.

**Comment by donpinkus** [comment]
Thanks @gianm! Appreciate the answer. I'll close this issue.

**Comment by donpinkus** [comment]
Actually - @gianm is there some way to hack it?

Query 1. TopN query, using col_a as the metric.
Query 2. Create a "filter" clause using the results from Query 1, and do a Select query with it?

**Comment by gianm** [comment]
@donpinkus That isn't quite the same query but maybe it would be close enough for government work. You'd need to pick some dimension `col_b` to group on when looking for the topN `col_a` values. In SQL it would be:

```
SELECT *
FROM my_table
WHERE col_b IN (
  SELECT col_b
  FROM my_table
  GROUP BY col_b
  ORDER BY col_a DESC
  LIMIT 10)
LIMIT 10
```

And actually, the above query should run fine in Druid SQL.
