### ISSUE TITLE
Does Druid 0.10.0 support version compare Sorting Order ?

### ISSUE THREAD

**Issue by darkbluever** [druid-io/druid#4580]
Hi, all

I am using druid 0.10.0 with Built-in SQL enabled and I have a dimension which contains version numbers such as "9.0.0.1" and "10.1.5.0".

I find there are only 4 sorting orders for bound filter ("lexicographic", "alphanumeric", "numeric", "strlen"), and no one of them is suitable for version numbers (numbers with decimal points).

Is there any way to compare this dimension as version number using SQL?
or can I use a js func for version comparison in SQL?

**Comment by gianm** [comment]
Hmm, in SQL the supported orderings are "as string" and "as number". You can switch which one you get by using the CAST operator. But there isn't one that works well for version numbers.

You could probably write a SqlOperatorConversion that creates a new function that transforms version numbers into something that sorts properly as a string or a number, and then do order by that. Something like `SELECT DISTINCT version FROM tbl ORDER BY VERSION_SORTABLE(version)` where `VERSION_SORTABLE` is an operator you add in an extension. Maybe it transforms "9.0.0.1" to "0009.0000.0000.0001".

Alternatively you could teach the SQL dialect about a new kind of ordering, but that can't be done through an extension, it would have to be done by a patch to druid-sql module itself.

**Comment by darkbluever** [comment]
Additionally, in my situation, I need to use version comparison with bound filters, such as `SELECT DISTINCT version FROM tbl WHERE version >= '9.0.0.1' and version <= '10.1.0.0'`. 

Maybe I could write a SqlOperatorConversion and use the custom function like  `SELECT DISTINCT version FROM tbl WHERE VERSION_SORTABLE(version) >= VERSION_SORTABLE('9.0.0.1') and VERSION_SORTABLE(version) <= VERSION_SORTABLE('10.1.0.0')`?

If I do things like this,  what impact will be on performance?

**Comment by gianm** [comment]
That'd work. The impact on performance for the filtering would be that the VERSION_SORTABLE function will be applied to each distinct version number at query time (since this would likely get planned be an index based filter). If it's fast enough that should be ok.

**Comment by darkbluever** [comment]
got it.
Thanks for reply : )
