### ISSUE TITLE
Can you filter on aggregate & post-aggregate columns?

### ISSUE THREAD

**Issue by donpinkus** [druid-io/druid#4587]
It seems you can only filter on a dimension. 

Is it possible to filter on a value created by an aggregation or a post-aggregation?

**Comment by gianm** [comment]
Do you mean like a SQL HAVING? This is supported, but only by groupBy. See havingSpec here: http://druid.io/docs/latest/querying/groupbyquery.html

**Comment by donpinkus** [comment]
Great, thanks @gianm!
