### ISSUE TITLE
"earlyMessageRejectionPeriod" setting for kafka indexing ?

### ISSUE THREAD

**Issue by wywlds** [druid-io/druid#4599]
I read the doc and tracked the use of "lateMessageRejectionPeriod" in kafka indexing service. It is a very useful param for our use case to limit the time period of backtracking. I am very grateful for this feature.
On the other hand, how about adding a "earlyMessageRejectionPeriod" to throw the messages that come from the "future"? Our use case is to track user behaviors, user behaviors having "future" timestamps are surely expected to be filtered out.
It could be extremely useful for our user case!

@dclim , is such a feature meaningful for druid.

**Comment by gianm** [comment]
Such a feature makes sense to me, at least. A patch is welcome :)

It's important to make sure that all tasks use the same time, since replicas need to perform exactly the same logic and so their local clocks cannot be used. If you implement this in a similar way to lateMessageRejectionPeriod then it should work.

**Comment by dclim** [comment]
makes sense to me too :)

**Comment by wywlds** [comment]
Thank you for your advice. I am already working on it.

**Comment by wywlds** [comment]
Hi, David & Gian, I created a pr for this issue, #4607 .

**Comment by wywlds** [comment]
@dclim @gianm 
This pr was implemented in exactly the same way as "lateMessageRejectionPeriod" (as I reviewed the original pr). I literally copied most of the codes(had to replace "late" with "early"), and did minor necessary changes. However, as many lines were changed, it could be a little bit boring to review them.
Do you have some time to review it?

**Comment by dclim** [comment]
Implemented in #4607
