### ISSUE TITLE
kafka indexing service  OffsetOutOfRangeException

### ISSUE THREAD

**Issue by remizyaka** [druid-io/druid#4632]
After some failure my kafka topic was re-created, so offset  got reset to 0. 
Getting such exception in my indexing tasks 
`WARN [task-runner-0-priority-0] io.druid.indexing.kafka.KafkaIndexTask - OffsetOutOfRangeException with message [Offsets out of range with no configured reset policy for partitions: {mytopic-0=16302}]`
it seems that my config options for auto offset reset are ignored
` },
  "tuningConfig": {
    "type": "kafka",
    "maxRowsInMemory": 50000,
    "resetOffsetAutomatically": true
  },
  "ioConfig": {
    "topic": "mytopic",
    "consumerProperties": {
      "bootstrap.servers": "localhost:9092",
      "auto.offset.reset": "earliest"
    },
    "taskDuration": "PT5M",
    "useEarliestOffset": true
  }`

**Comment by pjain1** [comment]
`resetOffsetAutomatically` only works if the next available offset in Kafka is greater than what the task is trying to fetch. In this case it seems like the next available offset would actually be less than what is being fetched. So you will need to reset the Supervisor manually, see "Reset Supervisor" here - http://druid.io/docs/latest/development/extensions-core/kafka-ingestion.html

**Comment by remizyaka** [comment]
yes, I used manual reset but don't think that it is good approach to do things manually on each topic reset

**Comment by gianm** [comment]
It's because the current offset being bigger than the next available offset probably means the kafka cluster totally disappeared, or the topic was deleted and re-created, both of which are "abnormal" and so Druid waits for a manual reset before continuing.
