### ISSUE TITLE
Can I add a User-Defined Function to SQL?

### ISSUE THREAD

**Issue by JingJunShen** [druid-io/druid#4636]
I want to add a User-Defined Function to SQL.How to develop in Druid?

**Comment by gianm** [comment]
Hi @JingJunShen, you can do it by writing an extension, subclassing SqlOperatorConversion and calling SqlBindings.addOperatorConversion to register it.

Please be aware these are still evolving APIs and are not guaranteed to be stable from release to release. So your extension may need to be recompiled for each version of Druid that you want to use it with. As Druid SQL matures more the APIs will become stable.

**Comment by JingJunShen** [comment]
got it.
Thanks for reply
