### ISSUE TITLE
Wrong time report in DruidRequest log

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#4655]
https://github.com/druid-io/druid/pull/3954/files#diff-0df117b4522295642fb19e7684e38a67R354  introduced a change in the timing mechanism of druid request results fixed in https://github.com/druid-io/druid/pull/4561#issuecomment-320686484 . The result is that the reported time is nanoseconds since `<<arbitrary time point>>` applied as nanoseconds since epoch.

For most systems this makes a query report that it was issued sometime in the 1970's.

**Comment by jon-wei** [comment]
Fixed by #4656
