### ISSUE TITLE
Possible unhandled null value in `ExpressionSelectors`

### ISSUE THREAD

**Issue by xanec** [druid-io/druid#4666]
https://github.com/druid-io/druid/blob/f18cc5df97e5826c2dd8ffafba9fcb69d10a4d44/processing/src/main/java/io/druid/segment/virtual/ExpressionSelectors.java#L108-L112

The above call `baseSelector.get().asDouble()` in `ExpressionSelectors.makeDoubleColumnSelector` may result in `NullPointerException` if the returned `ExprEval` contains `null` value.

Note that in comparison, a similar call in `ExpressionSelectors.makeFloatColumnSelector` is handled as follows:

https://github.com/druid-io/druid/blob/f18cc5df97e5826c2dd8ffafba9fcb69d10a4d44/processing/src/main/java/io/druid/segment/virtual/ExpressionSelectors.java#L83-L87

I believe this is introduced in #4491 (@b-slim)

**Comment by gianm** [comment]
Yes, this code is wrong. It should be more like what makeFloatColumnSelector does.

**Comment by gianm** [comment]
Thanks for the catch @xanec ! Would you be interested in doing a patch to fix it?

**Comment by xanec** [comment]
Sure! 
Note: #4669
