### ISSUE TITLE
FloatSumAggregatorFactory, FloatMinAggregatorFactory and FloatMaxAggregatorFactory have identical equals() that could be moved to SimpleFloatAggregatorFactory

### ISSUE THREAD

**Issue by leventov** [druid-io/druid#4671]
Since #4491. FYI @b-slim

**Comment by b-slim** [comment]
@leventov why it need to override hashCode ? it is implemented at `SimpleFloatAggregatorFactory` can you please explain the bug ?

**Comment by leventov** [comment]
@b-slim indeed, it's a false-positive IntelliJ warning. However it highlights the fact that `FloatSumAggregatorFactory.equals()`, `FloatMinAggregatorFactory.equals()` and `FloatMaxAggregatorFactory.equals()` are identical, and it could move moved to method SimpleFloatAggregatorFactory.equals().
