### ISSUE TITLE
SQL: Router is not SQL aware

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#4683]
The router redirects `/druid/v2/sql/` to `/druid/v2/` and so JSON-over-HTTP SQL queries do not work. I bet something similar applies to the Avatica route at `/druid/v2/sql/avatica/`.

The router should become aware of SQL. I'm not sure how this will fit in with the router's query-aware routing capabilities, since lacks the SQL metadata infrastructure that the broker uses to plan and understand SQL queries. Maybe the query-aware routing won't apply to SQL at first?

**Comment by randerzander** [comment]
The calcite-druid JDBC driver hasn't worked for me, so I'm hoping Druid's native SQL HTTP API gives my app a path forward.

Is there a workaround for this, perhaps a temporary patch to the query router? If you can point to a starting point, I could try to contribute a fix.

**Comment by gianm** [comment]
@randerzander, I take it you're using the Druid Router? (Druid SQL does work fine against the Broker)

The changes would need to start in AsyncQueryForwardingServlet. There's a part that assumes any request like `POST /druid/v2*` is a Druid native query. It's not a good assumption though, since `/druid/v2/sql/` would be a Druid SQL query, not a Druid native query.

**Comment by randerzander** [comment]
Hi @gianm, are the docs [here](http://druid.io/docs/0.10.1/querying/sql.html) out of date? I tried the curl example query but get 405s:

curl -XPOST -H'Content-Type: application/json' http://localhost:8082/druid/v2/sql/ -d '{"query":"SELECT COUNT(*) FROM data_source"}'

* About to connect() to localhost port 8082 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8082 (#0)
> POST /druid/v2/sql/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8082
> Accept: */*
> Content-Type: application/json
> Content-Length: 44
> 
* upload completely sent off: 44 out of 44 bytes
< HTTP/1.1 405 Method Not Allowed
< Date: Wed, 20 Sep 2017 12:14:55 GMT
< Allow: DELETE,OPTIONS
< Content-Length: 0
< Server: Jetty(9.3.19.v20170502)
< 
* Connection #0 to host localhost left intact

**Comment by gianm** [comment]
@randerzander You might need to set `druid.sql.enable = true` to get SQL up and running. See http://druid.io/docs/latest/querying/sql.html for details on that.

**Comment by randerzander** [comment]
@gianm , thanks for the suggestion!

For future reference for others, I followed the docs and configured the druid.sql.* properties in $DRUID_HOME/conf/druid/runtime.properties, but my environment was running using the settings in $DRUID_HOME/conf-quickstart instead which confused things for awhile.

**Comment by gianm** [comment]
@randerzander great to hear!

**Comment by gianm** [comment]
Fixed by #4851.
