### ISSUE TITLE
Remove "com.metamx.metrics.SysMonitor" and "com.metamx.metrics.JvmCpuMonitor" monitors from the default configurations ?

### ISSUE THREAD

**Issue by akashdw** [druid-io/druid#4690]
Druid master build with default conf-quickstart runtime properties fails to start druid service on Rhel7 (Haven't tested in other distributions) 

<pre>Exception in thread "main" java.lang.NoClassDefFoundError: org/hyperic/sigar/SigarException
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.fasterxml.jackson.databind.util.ClassUtil.findClass(ClassUtil.java:225)
        at com.fasterxml.jackson.databind.DeserializationContext.findClass(DeserializationContext.java:475)
</pre>

This is b/c `"com.metamx.metrics.SysMonitor"` and `"com.metamx.metrics.JvmCpuMonitor"`  recently got added by default in `conf-quickstart/druid/_common/common.runtime.properties` and `/examples/conf/druid/_common/common.runtime.properties`.

Can we remove above monitors from the default configurations? This will be helpful for new users trying out druid with default configurations. 

@gianm @himanshug @leventov what do you think ?

**Comment by gianm** [comment]
Yeah, let's remove those if they don't work out of the box. I guess it's because sigar is optional now.

**Comment by himanshug** [comment]
agree, quick start should work :)
