### ISSUE TITLE
GraphiteEmitter: add option to use non-pickled protocol?

### ISSUE THREAD

**Issue by LoicAG** [druid-io/druid#4712]
Hello, we are using the GraphiteEmitter (from the `graphite-emitter` extension) to send Druid metrics to Graphite. For internal reasons, we can not use the pickled protocol.

I was able to swap the `PickledGraphite` client for the standard `Graphite` client, simply by changing the constructor call; however, would it be possible to provide an option to decide on the protocol?

**Comment by blugowski** [comment]
Hello,

Already done, check this PR: https://github.com/druid-io/druid/pull/4265 :)

**Comment by LoicAG** [comment]
Amazing, thanks :)
