### ISSUE TITLE
Different points of method "isReady" in HadoopIndexTask

### ISSUE THREAD

**Issue by zhangxinyu1** [druid-io/druid#4713]
Current code of method "isReady" in HaddopIndexTask use JodaUtils.umbrellaInterval to produce a wider interval to lock task. 

That means if there is a task with interval["2015-09-10/2015-09-11","2015-09-14/2015-09-15"] running, the interval of task lock will be ["2015-09-10/2015-09-15"]. 

Then, if a new task with interval["2015-09-12/2015-09-13"] is submitted, it will be in waiting list instead of running directly.

Why not let the new task with interval["2015-09-12/2015-09-13"] running directly by set the lock interval["2015-09-10/2015-09-11","2015-09-14/2015-09-15"].

**Comment by jihoonson** [comment]
Hi @zhangxinyu1, this is because we assume that intervals for batch indexing are usually contiguous and there is no hole in the whole interval. But, you're correct. It is possible and should be able to be run if intervals are not overlapped. This issue will be fixed in #4479.

**Comment by zhangxinyu1** [comment]
@jihoonson oh I see. Thank you.
