### ISSUE TITLE
timestampSpec and optional milliseconds

### ISSUE THREAD

**Issue by htch** [druid-io/druid#4724]
Stumbled upon this problem trying to load data from BigQuery into Druid via batch indexer.

BigQuery dumps most timestamps in this format: `yyyy-MM-dd HH:mm:ss.SSS 'UTC'`, however some timestamps that BigQuery creates don't have milliseconds part (i.e. they effectively have this format: `yyyy-MM-dd HH:mm:ss 'UTC'`). I guess BigQuery developers chose to do this because it makes timestamps that never had precision down to milliseconds in the first place look prettier in spreadsheets. Maybe this works great for most people, but not for me because I can't load data from BigQuery into Druid: there is no way to tell batch indexer to parse a timestamp with optional milliseconds.

Possible solution: make timestampSpec accept an array of possible timestamp formats.

**Comment by niketh** [comment]
@htch optional milliseconds is already supported by using format "auto". However, time zone wasn't supported. I added a fix https://github.com/druid-io/druid/pull/4727, after which strings like "2009-02-13 23:31:30 PST" will also be supported.

**Comment by htch** [comment]
@niketh That's great news, thanks for your fix!
