### ISSUE TITLE
document various os/jvm gotchas and flags that should be set on Druid processes

### ISSUE THREAD

**Issue by himanshug** [druid-io/druid#4792]
it would be a nice document covering standard things that are specially important to Druid.

**Comment by drcrallen** [comment]
A lot of things under https://github.com/druid-io/druid/tree/0.10.1/docs/content/configuration have such docs. Are you wanting more things there?

**Comment by himanshug** [comment]
so, I generally recommend following jvm options to my users...

```
               -XX:MaxDirectMemorySize=10240g
               -Duser.timezone=UTC
               -Dfile.encoding=UTF-8
               -XX:+PrintGCDetails
               -XX:+PrintGCDateStamps
               -XX:+PrintGCTimeStamps
               -XX:+PrintGCApplicationStoppedTime
               -XX:+PrintGCApplicationConcurrentTime
               -Xloggc:/home/y/logs/druid/${NODE_CONF_SUBDIR}.gc.log
               -XX:+UseGCLogFileRotation
               -XX:NumberOfGCLogFiles=50
               -XX:GCLogFileSize=10m
               -XX:+ExitOnOutOfMemoryError
               -XX:+HeapDumpOnOutOfMemoryError
               -XX:HeapDumpPath=/var/logs/druid/${NODE_CONF_SUBDIR}.hprof
```

setting MaxDirectMemorySize to 10TB might look funny but it works and I haven't seen any sideeffects. also, I recommend G1GC unless user is willing to heavily tune their GC.


Also, on OS tuning side , we generally recommend users to 
1) disable THP
2) mount /tmp to tmpfs
3) try to have separate disk for writing gc and potentially druid logs


and probably some more things that I can't recall right now. I'm not sure if above stuff is covered somewhere in druid docs.

**Comment by himanshug** [comment]
another thing.. using JBOD instead of RAID on historicals.

**Comment by drcrallen** [comment]
@himanshug do you have any fs or OS recommendations you want in there as well?

**Comment by drcrallen** [comment]
As a counter-example, we run containerized so we set the target `MaxDirectMemorySize` + `xmx` + `"max page cache"` to a very specific memory footprint.

**Comment by drcrallen** [comment]
Would putting these in the jvm configurations in the quickstart suffice? Is it pretty common for people to use the quickstart configs as a rudimentary template?

**Comment by himanshug** [comment]
I haven't thought through where to put this information , but we'll probably put somewhere ( most likely in http://druid.io/docs/0.10.1/operations/recommendations.html )

other recommendations probably wouldn't be general enough to be recommendations but we can add any other tunings we can think of and what use cases they would be appropriate for.

**Comment by himanshug** [comment]
@drcrallen yeah, in our case we don't want to artificially restrict jvm off heap allocation but rather let it be restricted by OS if necessary.
in your case too, I think your jvm can have `-XX:MaxDirectMemorySize=10240g` but set your container target memory size to (xmx + "max page cache" + expected-off-heap-jvm-allocation). In most cases restricting jvm doesn't gain much.
