### ISSUE TITLE
ServerConfig dependency needs to be removed from DruidNode

### ISSUE THREAD

**Issue by himanshug** [druid-io/druid#4850]
or else things like tls or plainText enable/disable are not present in serialized form of DruidNode and following kind of scenarios break....

(1)  tls is not enabled on historical, it serializes its DruidNode object and puts in to zk for discovery.
(2) tls is enabled on broker, when broker discovers historical and tries to deserialize with the broker local ServerConfig object (which has tls enabled), then deserialization fails because serialized DruidNode object from historical doesn't have tls port set.

**Comment by pjain1** [comment]
Started happening because https://github.com/druid-io/druid/pull/4634 started depending on DruidNode deserialization.
Anyways, in general its good to not depend on it.
