### ISSUE TITLE
How to get Druid response named by parameter for 'timeseries' query?

### ISSUE THREAD

**Issue by chinseone** [druid-io/druid#4887]
I'm new to Druid but I already love it! I have a question on timeseries query to Druid(/druid/v2?pretty) which will generate default response something like this:
```
[
  {
    "timestamp": "time1",
    "result": { "name1": value1_1, "name2": value2_1} 
  },
  {
    "timestamp": "time2",
    "result": { "name1": value1_2, "name2": value2_2}
  }
]
```
What I'm expecting is(in this case) is an array of response named by parameter:
```
{
  [
    "name":"name1",
    "datapoints":[
      "time1":"value1_1",
      "time2":"value1_2"
    ]
  ],
  [
    "name":"name2",
    "datapoints":[
      "time1":"value2_1",
      "time2":"value2_2"
    ]
  ]
}
```
Is there a way to get above response without manually manipulating json? I see some other time series DB(e.g. OpenTSDB, Graphite etc.) already equipped with this functionality.

**Comment by gianm** [comment]
@chinseone, result manipulations like this are currently not supported. You would have to do it on the client end.

Marking closed but feel free to reopen if you have additional questions.
