### ISSUE TITLE
SQL: Incorrect filter simplification

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#4945]
The filter in `SELECT COUNT(*) FROM druid.foo WHERE 1 < m2 AND m2 < 4` is incorrectly simplified to just `m2 < 4`. The root cause is https://issues.apache.org/jira/browse/CALCITE-2007 so this will require a Calcite fix and upgrade.

**Comment by gianm** [comment]
Added to 0.11.1 since it is a regression from 0.11.0 (it came in with the Calcite upgrade of #4889).

**Comment by gianm** [comment]
Patched upstream, fix should be in Calcite 1.15.0.

**Comment by jon-wei** [comment]
Just checked this against Calcite 1.15.0, this filter simplifies correctly. (There's a new regression with Calcite 1.15.0 though, see #4635)
