### ISSUE TITLE
Historicals should only write to remote cache

### ISSUE THREAD

**Issue by leventov** [druid-io/druid#4947]
Remote (i. e. memcached) cache on historicals according to @drcrallen has two points:
 - Sharing cache with brokers
 - When segment is moved, cache makes the transition "smoother"

If brokers see cached results, they won't query historicals. So on historicals, it's pointless to try to query remote cache again. So memcached use on historicals should be write-only - put query results to the cache, for brokers, but don't try to get results from memcached.

**Comment by drcrallen** [comment]
@leventov but for local cache (caffeine) it should still read and write?

**Comment by gianm** [comment]
If historicals are configured to use a remote cache, and broker caching is disabled, then I would think that we still want historicals to read from remote cache. (Otherwise it would be pointless)

Disabling broker caching is somewhat common, since _enabling_ the broker cache prevents historicals from fully merging their results (they need to send them by-segment to the broker).

**Comment by leventov** [comment]
> but for local cache (caffeine) it should still read and write?

Yes

> If historicals are configured to use a remote cache, and broker caching is disabled, then I would think that we still want historicals to read from remote cache. (Otherwise it would be pointless)

Remote caching on historicals, while there is no caching on brokers, meet only one point ("smooth transition") and it feels like to little for me, to justify using remote cache at all.

**Comment by drcrallen** [comment]
@gianm another cache methodology is to disable populate cache on brokers but enable use cache on brokers.

**Comment by drcrallen** [comment]
@leventov even though the brokers can read the cache, they do (optionally) limit the number of segment cache results they ask for to prevent overwhelming the cache system with a huge get request that would never finish fetching in the timeout.

**Comment by leventov** [comment]
BTW yes - symmetric idea is to only *read* from remote cache on brokers, but not write (because historicals are "responsible" for that) -- if it is not done already

**Comment by drcrallen** [comment]
I think this can be accomplished with a customization of the hybrid cache in an extension, and shouldn't need any core changes.

**Comment by himanshug** [comment]
> Remote caching on historicals, while there is no caching on brokers, meets only one point ("smooth transition") and it feels like to little for me, to justify using remote cache at all.
It is also used when you have same segment replicated on multiple historicals, second query for that segment might land on either historicals and they would be able to utilize the cache.

wondering whether you are facing a specific problem and trying to fix that ? if historical received a query and result for the segment in the cache then it should get it from cache. broker shouldn't have sent the query to historical if it did not need that.

**Comment by leventov** [comment]
@himanshug yes, we have a lot of memcached timeouts on historicals, and then query timeouts as well. Despite memcached connection library is configured to wait for no more than 500ms, I suspect that it doesn't actually follow this restriction, i. e. queries may wait for response from memcached for longer. It doesn't make sense, given 99% of the time the answer from memcached is going to be "not found"

**Comment by himanshug** [comment]
i see so you have cache enabled on broker as well and it only sends query to historical if they were not in cache and historical is consequently not going to find those in cache.

have you tried setting `druid.historical.cache.useCache=false` on historicals and `druid.realtime.cache.useCache=false` on realtime processes?

**Comment by leventov** [comment]
@himanshug I didn't know about those configs. BTW there is hybrid cache and local L1 level is still used for get.

Also, why `druid.realtime.cache` exist? does it cache anything?

**Comment by himanshug** [comment]
can't remember but `druid.realtime.cache` is possibly used for caching final segments which have not been handed off .

> BTW there is hybrid cache and local L1 level is still used for get.
so you don't want to avoid get on cache altogether and in case of hybrid cache still wanna check in L1 .  given that 99% of time you have cache miss, I'm not sure how much benefit is there. 

but if you still want to be that granular, then I think you probably should add more config to `HybridCache` rather than `MemCache` so that it can be made to only do gets on L1 and not on L2.... users can use non memcache things also as remote cache so this option would be more general.

**Comment by leventov** [comment]
@himanshug ok, I agree. I closed #4972 and will prepare a PR that alters hybrid cache config, rather than memcached

**Comment by leventov** [comment]
> Disabling broker caching is somewhat common, since enabling the broker cache prevents historicals from fully merging their results (they need to send them by-segment to the broker).

@gianm why retrieving cached results on brokers prevents historicals from sending merged results?

**Comment by leventov** [comment]
> so you don't want to avoid get on cache altogether and in case of hybrid cache still wanna check in L1 . given that 99% of time you have cache miss, I'm not sure how much benefit is there.

@himanshug the cache key could be evicted from memcached, but stay in local cache on a historical. Broker gives you "survival bias" only about the first.

**Comment by gianm** [comment]
> @gianm why retrieving cached results on brokers prevents historicals from sending merged results?

It doesn't, but populating the cache does. If the broker is only reading the cache, but not populating it, then historicals can send merged results. But of course that means it has to be reading the populated cache from somewhere else -- presumably memcached populated by historicals.

**Comment by leventov** [comment]
@gianm yes, that is what I meant in https://github.com/druid-io/druid/issues/4947#issuecomment-336007722

**Comment by gianm** [comment]
Understood, that makes sense

**Comment by sascha-coenen** [comment]
>> given 99% of the time the answer from memcached is going to be "not found"
seeing how this is the case, wouldn't it make sense to implement a local negative-cache to prevent the frequent calls to a remote cache?
https://en.wikipedia.org/wiki/Negative_cache
One could reuse the existing local cache functionality to keep track of remote cache misses too.
To my understanding the current hybrid cache uses L1 only for positive caching.

**Comment by leventov** [comment]
@sascha-coenen when hybrid cache doesn't try to get a value from remote cache, when it's not found in the local cache, it already looks like "negative cache".

**Comment by sascha-coenen** [comment]
@leventov yes, what you described would indeed be a negative cache, but currently the hybrid cache only does positive caching. It will cache L2 hits in L1, but it will not cache L2 misses in L1, so if I kept querying the hybrid cache for the same NamedKey which is neither in L1 nor L2 over and over again, then the hybrid cache would keep punching out to L2 over and over again.

I can see how one of the use-cases for the hybrid cache is that one historical can pick up entries cached by another historical (in context in-tier replication) and that a naive negative cache would conflict with that but perhaps there is a way to have both.

**Comment by peferron** [comment]
> the cache key could be evicted from memcached, but stay in local cache on a historical.

@leventov in this situation, this cache key will not get populated again into memcached as long as it's still present in the historicals local cache, right? So a query for this cache key will always result in a broker remote cache miss followed by a historical local cache hit.

This seems undesirable if queries for this cache key keep coming frequently, but might work well in practice if the ultimate goal is to cut the number of segment scans without caring where the cache hit comes from.

**Comment by leventov** [comment]
@peferron I don't see why a local cache is needed on historicals in this setting, apart from the short period of time between the end of the execution on the historical and the moment of the population in memcached. But it seems to me that this should properly be handled by a [small "admission" cache](https://github.com/apache/incubator-druid/issues/7186), which is write-through by design, so there is no problem that you've described.

**Comment by peferron** [comment]
One of your previous comments indicated that you were using local cache in this setting:

>  BTW there is hybrid cache and local L1 level is still used for get.

Have you moved away from this configuration since then?

I think the local cache could help if the remote cache is churning too much. Since the local cache only stores results for segments located on that historical, it may keep results longer than a remote cache that stores results for all segments in the cluster. Of course it's possible to simply give more memory to the remote cache instead.

The admission cache that you linked is also interesting to reduce churn in the remote cache. But even in this situation, you can imagine a local cache being useful to keep results that haven't been deemed worth caching remotely yet. If another query for these results come in, then historicals could get results from the local cache instead of re-scanning the segments, and then potentially write these results to the remote cache if they are now considered worthy.

**Comment by leventov** [comment]
> I think the local cache could help if the remote cache is churning too much. Since the local cache only stores results for segments located on that historical, it may keep results longer than a remote cache that stores results for all segments in the cluster. Of course it's possible to simply give more memory to the remote cache instead.

Yes, you are right, the local cache is not needed (apart from the admission window) only if the remote cache is large enough.

> But even in this situation, you can imagine a local cache being useful to keep results that haven't been deemed worth caching remotely yet. If another query for these results come in, then historicals could get results from the local cache instead of re-scanning the segments, and then potentially write these results to the remote cache if they are now considered worthy.

It looks to me precisely like the description of the admission window.

**Comment by peferron** [comment]
> It looks to me precisely like the description of the admission window.

Right. I had misunderstood how the admission window would work. It completely makes sense now. Thanks!
