### ISSUE TITLE
sql time filter error

### ISSUE THREAD

**Issue by qinzl1** [druid-io/druid#4959]
[root@BJ-HOST-140 ~]# curl -XPOST -H'Content-Type: application/json' http://xxxx:8082/druid/v2/sql/ -d '{"query":"SELECT COUNT(*) FROM data_source WHERE __time >= TIMESTAMP '2001-01-01 00:00:00'"}'
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /druid/v2/sql/. Reason:
<pre>    javax.servlet.ServletException: com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input in VALUE_STRING
 at [Source: HttpInputOverHTTP@71686ce3[c=79,q=0,[0]=null,s=EOF]; line: 1, column: 159]</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.19.v20170502</a><hr/>
</body>
</html>

**Comment by gianm** [comment]
@qinzl1, this is really the shell that is foiling you (same problem as #4938). You can see it if you use echo to look at what the shell is doing to your input (try `echo '{"query":"SELECT COUNT(*) FROM data_source WHERE __time >= TIMESTAMP '2001-01-01 00:00:00'"}'`).

You can work around it by using shell escapes or by using curl's feature to read from a file with `-d @filename`.
