### ISSUE TITLE
Callback race on start in cachingCost balancer

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#4984]
CachingCostBalancerStrategyFactory registers callbacks in its `start()` method, which is problematic since any callbacks that happen between start of ServerInventoryView and BalancerStrategyFactory will be missed. Inventory view callbacks should generally be registered in constructors, not in start methods.

I discovered this when trying to test the cachingCost balancer on a cluster that has a small number of segments, and found that it missed the initialization callback (happened too fast) so it refused to create itself.

cc: @dgolitsyn @leventov

**Comment by leventov** [comment]
Thanks for trying it out and catching the bug

**Comment by himanshug** [comment]
it would be nice to add something to ServerInventoryView implementations to throw exception if any of the "registerXXX(..)" calls are made after they have been started. that would've caught this issue immediately.

Sidenote: I'm gonna soon send a PR to deprecate Single/BatchServerInventoryView. there is code duplication between Http and Batch ServerInventoryView for now so both would need same update.
