### ISSUE TITLE
Issue with 0.11 router - it doesn't see brokers

### ISSUE THREAD

**Issue by leventov** [druid-io/druid#4992]
After updating Router from 0.10.1 to 0.11 it stops to see brokers.

Might be related to recent changes in `TieredBrokerHostSelector`, e. g. https://github.com/druid-io/druid/commit/74538c32887aea0d7180857ef7edfad46e17d105#diff-09401bb9b0565d15079a30fd8683695e

cc @clintropolis 

FYI @himanshug

**Comment by himanshug** [comment]
@leventov what version of code are brokers running ?

**Comment by leventov** [comment]
@himanshug 0.11.0

**Comment by himanshug** [comment]
ok, that is unexpected. ...  I think it tested it but I'll check it again and see if I'm able to repro it.

but can you check 
`http://coord-host:port/druid/coordinator/v1/cluster` and `http://router-host:port/druid/router/v1` to see if brokers are showing up anywhere.

if not, then can you see in broker log if they printed https://github.com/druid-io/druid/blob/0.11.0/server/src/main/java/io/druid/curator/discovery/CuratorDruidNodeAnnouncer.java#L71

**Comment by himanshug** [comment]
updated `http://router-host:port/druid/router/v1/brokers` in above comment

**Comment by leventov** [comment]
@himanshug brokers are visible, for sure. It's from router 0.11 logs:
```
INFO [NodeTypeWatcher[broker]] i.d.c.d.CuratorDruidNodeDiscoveryProvider$NodeTypeWatcher - Received event [CHILD_ADDED] for Node[broker:DiscoveryDruidNode{druidNode=Druid
Node{serviceName='druid/metrics/bard', host='someHost', port=-1, plaintextPort=somePort, enablePlaintextPort=true, tlsPort=-1, enableTlsPort=false}, nodeType='broker', services={lookupNodeServi
ce=LookupNodeService{lookupTier='historical'}}}]. - []
```

but later:
```
ERROR [id] i.d.s.r.QueryHostFinder - WTF?! No server found for serviceName[druid:metrics:bard]. Using backup - []
```

Could it be `druid/metrics/bard` vs. `druid:metrics:bard` problem somehow?

**Comment by himanshug** [comment]
it looks like `druid.service=druid/metrics/bard` on brokers. and, on router config, you have `druid:metrics:bard` . From the code, it looks like there is magic replacement of '/' to ':' while announcement and discovery in the older code.
I think it would work fine if in the router config you used same service name as provider to broker in its properties i.e. `druid/metrics/bard`. please see if that works.

if that is indeed the problem, then we'll probably mention it in release notes. this magic is unnecessary and confusing. it was probably needed in older code because serviceName was used in zk path.

**Comment by drcrallen** [comment]
If that is the case, its a pretty big breaking change

**Comment by himanshug** [comment]
yes, it would be incompatible but still allows rolling upgrade. there wouldn't be much value in keeping the magic happening. To remove it, at some point we would need to be incompatible. This is a major release, so we can hopefully afford that.

**Comment by gianm** [comment]
Would `druid/metrics/bard` work in the router config in older versions (0.10) too? If so then I would say it makes sense to note that you may have transformed `/` to `:` in your configs before, but it's not necessary, and will not continue to work. So you should switch them to `/` which will work with both the old and new versions.

**Comment by himanshug** [comment]
Yes, `druid/metricss/bard` would work in router config in older versions ( 0.10.x ) too. old external-discovery code does a translation from '/' to ':' on discoverer side ( https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/curator/discovery/ServerDiscoveryFactory.java#L52 ) via ( https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/curator/discovery/CuratorServiceUtils.java#L41 )

so technically, serviceName could have '/' in it earlier but it was always translated to ':' on both sides.

**Comment by himanshug** [comment]
@leventov did `druid/metrics/bard` change in router config work ?

**Comment by leventov** [comment]
Not yet 100% sure but at the moment it seems that it works. Also it seems that `druid.router.coordinatorServiceName` needs to be changed. Despite release notes, it seems to me it is so easy to forget this that I think we need to convert colons to slashes in Druid

**Comment by himanshug** [comment]
I thought about it a bit more and things wouldn't work if we put an auto replacement of ':' to '/' .

Let us you have two brokers with service names "druid:broker-tier1" and "druid/broker-tier2". and on router side you refer to them by "druid:broker-tier1" and "druid:broker-tier2".

If auto replacement from ':' to '/' is done on discovery side(i.e. at router) only then new router wouldn't be able to see first broker.
And if we did auto replacement on announcement side as well (i.e. at broker) then both brokers would announce "druid/broker-tier1" and "druid/broker-tier2" and old router code wouldn't be able to find them.

Pretty much all releases have a "Upgrading from release X-1" and contain information about actions need to be take by users before upgrade. This would be documented there and may be in bold to emphasize.

I understand that config change would happen for all service discovery properties such as `druid.router.coordinatorServiceName` too in other node configs as well.

**Comment by himanshug** [comment]
concluded on dev-sync today to update release-notes to mention this incompatibility.

**Comment by jon-wei** [comment]
@himanshug I added a section "Service name changes" to the 0.11.0 release notes, can you take a look and let me know if I missed anything there?

**Comment by himanshug** [comment]
@jon-wei I was going to update, thanks :) . I will update it as needed.
