### ISSUE TITLE
Delete all segments

### ISSUE THREAD

**Issue by erankor** [druid-io/druid#4994]
Hi all,

I'm planning to reindex all the data in my Druid cluster (following some mistake that was found in the data preparation...), and I'm thinking about using this opportunity to delete all the data. I've seen a few mentions of the `kill` task, but my question is - is the procedure below expected to work as well -
1. Stop all Druid nodes
2. Truncate table druid_segments
3. aws s3 rm path/to/druid/segments --recursive
4. rm -rf /opt/druid-0.10.0/var/druid/segment-cache/* on all historicals
5. Start all Druid nodes

Main reason I prefer this method is that at some point in the life of the cluster I moved to a separate MySQL instance, and didn't bother to migrate the data. Therefore, I currently have segments in deep storage that are not referenced in MySQL. The kill task won't delete them, but this procedure will...

Any feedback is appreciated

Thanks!

Eran

**Comment by gianm** [comment]
@erankor that should do it. And if you really want to clear all the state of the cluster, you might as well drop and re-create the whole MySQL database, rather than just truncate druid_segments.

Closing this but feel free to reopen if you want.

**Comment by erankor** [comment]
Great, thanks @gianm !
