### ISSUE TITLE
GroupBy returns null result after upgrading from 0.9.2 to 0.10.1

### ISSUE THREAD

**Issue by l15k4** [druid-io/druid#4995]
Hey,

caching is enabled on both historical and broker nodes. `druid.broker.cache.unCacheable=["groupBy", "select"]`

And this `plyql 0.11.2`query: 
```
http -v  http://host/plyql ""sql""="SELECT COUNT(DISTINCT diid) as gwid FROM gwiq-daily-p WHERE (('2017-10-01T00:00:00' <= __time AND __time <= '2017-10-10T00:00:00')) AND (cid = 'c0248') GROUP BY d_site"
```
returns : 
```
{
    "result": {
        "attributes": [
            {
                "name": "split0", 
                "type": "STRING"
            }, 
            {
                "name": "gwid", 
                "type": "NUMBER"
            }
        ], 
        "data": [
            {
                "gwid": 23652840.734643567, 
                "split0": null
            }
        ], 
        "keys": [
            "split0"
        ]
    }
}
```
However it is not fully deterministic, one time it returned correct `split0` result, but after I tried it a couple of times more, it returned only `null`.

**Comment by l15k4** [comment]
Not sure if the GroupBy querying changed too in 0.10.1, for instance this native `broker/druid/v2/sql/` groupBy query doesn't return the split values : 
```
 $ http http://broker/druid/v2/sql/ ""query""="SELECT COUNT(*) FROM \"gwiq-daily-p\" WHERE cid = 'c0248' GROUP BY 'd_site'"
[
    {
        "EXPR$0": 25450854
    }
]
```
How can  I get the split results ??

**Comment by gianm** [comment]
@l15k4 for the time filter in Druid SQL, it should be `TIMESTAMP '2017-07-01 00:00:00' >= __time`. The filter you have provided, `'2017-07-01T00:00:00' >= '__time'`, is always false so no rows would be returned.

If you run plyql from the command line in verbose mode (`bin/plyql -h 127.0.0.1 -q "your query" -v`) then it will show the Druid queries that get made -- this will help debug.

**Comment by l15k4** [comment]
In that case it must be a `plyql` problem, this works in druid-native-sql 
```
SELECT \"d_site\", COUNT(*) FROM \"gwiq-daily-p\" WHERE TIMESTAMP '2017-07-01 00:00:00' >= __time AND cid = 'c0248' GROUP BY \"d_site\"
```
but corresponding plyql sql query (which we use in production) returns null : 
```
SELECT d_site, COUNT(*) FROM gwiq-daily-p WHERE '2017-07-01T00:00:00' >= __time AND cid = 'c0248' GROUP BY d_site
```
we use plyql-server, I cannot use plyql-client for security reasons, so I cannot check the resulting native query json.

**Comment by gianm** [comment]
Interesting, not sure what is going on with plyql, but good to know that druid sql seems to be working OK.

Maybe running the plyql server with `-v` would get it to log its Druid queries to its log file.

**Comment by l15k4** [comment]
`-v` on plyql-server only logs incoming SQL queries ....
`-v` on plyql-client only logs plywood expressions ...

**Comment by l15k4** [comment]
It only happens for `d_site` dimension, so there is a problem with plyql metadata resolution, closing...
