### ISSUE TITLE
Coordinator to Overlord proxied requests always fail with "403 Forbidden"

### ISSUE THREAD

**Issue by himanshug** [druid-io/druid#5038]
Coordinator accepts `/druid/indexer/v1/*` requests and forwards them to overlord leader via `OverlordProxyServlet`. However, at coordinator, `PreResponseAuthorizationCheckFilter` fails the request because it does not have authorization attributes set.

**Comment by himanshug** [comment]
@jon-wei  does that sound correct ?

**Comment by jon-wei** [comment]
@himanshug Thanks for reporting, I added a fix here: https://github.com/druid-io/druid/pull/5039
