### ISSUE TITLE
Potential deadlock condition in Appenderator

### ISSUE THREAD

**Issue by pjain1** [druid-io/druid#5046]
-  `persistExecutor` submits mergeAndPush job to `pushExecutor` [here](https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/segment/realtime/appenderator/AppenderatorImpl.java#L482) after completing the persist. 
- `pushExecutor` submits abandon segment job to `persistExecutor` [here](https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/segment/realtime/appenderator/AppenderatorImpl.java#L908) 

`pushExecutor` uses a blocking queue with 1 capacity and if `persistExecutor` either uses Synchronous Queue (which it does in case of KafkaIndexTask) or queue with capacity 1 then deadlock can happen. This would be more common in the new KafkaIndexingService which will support incremental handoff as handoffs (which leads to abandoning of segments) for a sequence can interleave with pushing of segments for another sequence.

This can probably be fixed by not using [pushBarrier](https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/segment/realtime/appenderator/AppenderatorImpl.java#L909) instead using some form of Atomic counter to keep track of existing pushes before abandoning segments. Any thoughts ?

**Comment by jihoonson** [comment]
I think it's a good idea. Maybe a new thread like abandonExecutor is needed to avoid interleaving?

**Comment by pjain1** [comment]
May be a new executor can be used as you suggested or just use a counter to keep track of pushes that is happening currently. Submit task to drop the segments to persistExecutor only when the counter is zero, thus not relying on pushBarrier job submitted to pushExecutor to avoid interleaving.
Probably, new executor approach seems cleaner. I don't have preference of one over another.

**Comment by pjain1** [comment]
Added fix in https://github.com/druid-io/druid/pull/4815

**Comment by pjain1** [comment]
Fixed in https://github.com/druid-io/druid/pull/4815
