### ISSUE TITLE
Docs: Stream-pull.md sentence explanation

### ISSUE THREAD

**Issue by dyanarose** [druid-io/druid#5072]
I'm in the middle of reading and fixing some language oddities in the docs.

However I can't make heads or tails of this sentence in the first paragraph
https://github.com/druid-io/druid/blame/master/docs/content/ingestion/stream-pull.md#L15

`Please note that Realtime nodes have very properties than the indexing service.`

Can someone explain what this is supposed to be saying please.

**Comment by b-slim** [comment]
I think the author wanted to say different properties than the indexing services. 
Historically Druid has _standalone real-time_ nodes to pull data from Kafka, this type of node is not used anymore.

**Comment by dyanarose** [comment]
that makes sense.

This doc continues on to talk about stream-pull as standalone real-time nodes. Is this page then totally obsolete and should be removed or at least marked as obsolete, or is it still relevant, just the implementation has changed?

**Comment by b-slim** [comment]
@dyanarose totally agree with you druid docs need a massive revamp/restructure especially the real-time ingestion section.

**Comment by dyanarose** [comment]
hah, brilliant. Until someone else comes along, I'll see about starting that particularly hairy conversation.

Ta @b-slim, I'll close this out now
