### ISSUE TITLE
Druid Parquet ingestion fails when null

### ISSUE THREAD

**Issue by Fokko** [druid-io/druid#5103]
Hi All,

I have a question regarding the handling of null values. Right now, when one of my dimension columns is null, the parquet ingestion fails. How does Druid handle null values, are dimension columns allowed to be null? I dug into the documentation, but I could not find a clear answer. If this is a bug, I'm happy to fix this.

Please let me know,

Cheers, Fokko

**Comment by b-slim** [comment]
I can not speak for parquet extension, but using regular csv nulls will be ingested and replaced by empty strings. This will change soon after we merge this PR #4754

**Comment by Fokko** [comment]
Thanks @b-slim. That was exactly the answer I was looking for. I've subscribed to the PR and update the Parquet code once it is merged.
