### ISSUE TITLE
Second task fail - out of memory error

### ISSUE THREAD

**Issue by carlez** [druid-io/druid#5117]
Hi, I use tranquillity to load data from kafka to druid.
My segment granularity is 5 minutes.
The first task runs fine, while the second task fails with this error:
```

CliPeon - Error when starting up.  Failing.
com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) Error in custom provider, java.lang.OutOfMemoryError
```

What is the problem? How can I fix it?
In attachment the complete log.
Thank you!!!
[log.txt](https://github.com/druid-io/druid/files/1499841/log.txt)

**Comment by gianm** [comment]
@carlez you probably need to increase `-XX:MaxDirectMemorySize`.

**Comment by diliptechno** [comment]
how did you fix this problem?
