### ISSUE TITLE
broker routes queries before inventory initialized

### ISSUE THREAD

**Issue by skyler-tao** [druid-io/druid#5120]
My druid cluster is 0.9.2, when I restart broker node, but right now there is a timeseries query to broker when inventory is not ready to be initialized, so I get the partial result. detail logs see below.

it may be not right or a consistency bug ? Or in higher version it's solved ?

![broker log](https://user-images.githubusercontent.com/8034498/33273177-788c0de6-d3c7-11e7-839c-69e09d19ce66.png)

**Comment by gianm** [comment]
@skyler-tao I believe the http inventory view introduced in master recently deals with this better. It waits some time for the view to be initialized. I'm not sure if the ZK based one has been improved since 0.9.2.
