### ISSUE TITLE
Http broker filters probably do not work as expected.

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#5121]
https://github.com/druid-io/druid/blob/druid-0.11.0-rc2/server/src/main/java/io/druid/client/FilteredHttpServerInventoryViewProvider.java#L63 sets an alwaysTrue whereas https://github.com/druid-io/druid/blob/druid-0.11.0-rc2/server/src/main/java/io/druid/client/FilteredBatchServerInventoryViewProvider.java#L55 sets an alwaysFalse.

This comes into play in the OR statement creation at https://github.com/druid-io/druid/blob/druid-0.11.0-rc2/server/src/main/java/io/druid/client/HttpServerInventoryView.java#L269-L272 and https://github.com/druid-io/druid/blob/druid-0.11.0-rc2/server/src/main/java/io/druid/client/BatchServerInventoryView.java#L97-L100 respectively

**Comment by himanshug** [comment]
yes, you are right .. thanks. I'll fix it.

**Comment by himanshug** [comment]
good to know that someone is trying out the http based segment management :)
