### ISSUE TITLE
Some topN specializations clone offsets, which can fail

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#5132]
HistoricalSingleValueDimSelector1SimpleDoubleAggPooledTopNScannerPrototype and Historical1SimpleDoubleAggPooledTopNScannerPrototype both call `TopNUtils.copyOffset(cursor)`. It looks like the intent is to try to get the jvm to allocate the object on the stack. (see https://github.com/druid-io/druid/pull/4710#discussion_r154273264 and [comment in the code](https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/query/topn/TopNUtils.java))

However, FilteredOffset, which is used when there is a "postFilter" (scan-based rather than index-based) cannot be cloned. This means queries will throw exceptions if they are topNs, filtering on non-string columns, with 1 simple double aggregator.

Based on the uncertainty expressed in https://github.com/druid-io/druid/pull/4710#discussion_r154273264 that the cloning is actually useful, I suggest fixing this by removing the cloning step.

@leventov what do you think?

**Comment by leventov** [comment]
It's proven that this object couldn't be scalarized: https://twitter.com/iwan0www/status/936641774554148864, but I vaguely remember that I left this clone for some other reason, maybe it doesn't help with scalarization but does help with method inlining on the offset object. So when removing clone, regression benchmarks should be run.

**Comment by gianm** [comment]
Is one of the benchmarking classes already in the codebase a good way to test it?

**Comment by leventov** [comment]
I'm sure, as far as I remember `TopNBenchmark` was not really representative. Instead of removing cloning, I suggest to skip HistoricalXxxPrototypes specializations when encountering FilteredOffset. It wouldn't make such queries not specialized at all, because it would fall back to GenericXxxPrototypes.

If you are OK with this I can make a patch.

**Comment by gianm** [comment]
I'm ok with that approach too, go for it.
