### ISSUE TITLE
Queryable intervals

### ISSUE THREAD

**Issue by tarekrached** [druid-io/druid#522]
please create a new route, /v1/intervals that returns all intervals for all datasources.  Basically, just a list of distinct intervals with total size and count.

also, please add /v1/intervals/ISOINTERVAL, which returns the aggregate size and count of all segments that intersect ISOINTERVAL

/v1/intervals/ISOINTERVAL?simple can return size and count for each distinct interval within ISOINTERVAL

/v1/intervals/ISOINTERVAL?full can return size and count for each datasource for each distinct interval within ISOINTERVAL

**Comment by noddi** [comment]
We can close this issue because PR is merged.

**Comment by gianm** [comment]
@noddi closing.
