### ISSUE TITLE
Realtime Node is it necessary for realtime ingestion???

### ISSUE THREAD

**Issue by amoussoubaruch** [druid-io/druid#5220]
Hi, 

Realtime node is it necessary for realtime ingestion? 
In druid documentation, it explain that we have 2 ways for realtime ingestion. First is use raeltime node and second is  indexing service and tranquility. 
What's best way? 
Can you Explain me please with your experience what's is the best solution? 

Thanks

**Comment by jihoonson** [comment]
Hi @amoussoubaruch, the realtime node is not supposed to be used for production.
If you're using Kakfa, the Kafka indexing service is the best way for streaming ingestion. Otherwise, you should try with Tranquility.

**Comment by amoussoubaruch** [comment]
hi @jihoonson 
It's Ok .
Many thanks
