### ISSUE TITLE
Retain/drop periods with shift

### ISSUE THREAD

**Issue by kaytrance** [druid-io/druid#5227]
Is there a way to define retain/drop periods for historical so that, for example, one node could have last month data, other one last 6 month data excluding last month without defining strict datetime intervals like 01072017-30112017.

For example if today is 01st january 2018, then one historical have P1M data  rule (whole december) but other should then have data from july till november (something like P6M-without-P1M).

**Comment by himanshug** [comment]
it is possible to define per-tier load/drop rules... so you can configure two different `druid.tier` setting on  different historicals..then you can configure two different rules for those two tiers.

**Comment by kaytrance** [comment]
yes, that is clear, but my question was more related on what do I have to write exactly to achieve this.

Period definition uses ISO 8601 standart, right? So if I want to define a rule that states "retain last month data" I can set it to `period: "P1M"`, right? So when it comes to another tier what I have to write to say that on that tier I want to have "last 6 month data without last month data"?

The idea is to put P1M tier on very high specs machines while "P6M without P1M" should have much lower specs.

**Comment by jihoonson** [comment]
You can configure two rules for the lower spec tier: one for loading last 6 month data and one for dropping last 1 month data. Please note that the ordering of rules is important.

**Comment by himanshug** [comment]
I agree with @jihoonson suggestion on what rules to use.

technically you can implement your own custom LoadRule in a Druid extension to do exactly what you need but that would be the option for more complicated use cases.

**Comment by kaytrance** [comment]
Ok, thank you!
