### ISSUE TITLE
TopN docs are incorrect

### ISSUE THREAD

**Issue by donpinkus** [druid-io/druid#5233]
In the [TopN](http://druid.io/docs/latest/querying/topnquery.html) docs, it says that "aggregations" and "postAggregations" are **not** required.

This is incorrect.

A TopN query will fail if you don't provide an aggregation:

`{"error":"Instantiation of [simple type, class io.druid.query.topn.TopNQuery] value failed: Must have at least one AggregatorFactory"}`

**Comment by jihoonson** [comment]
Hi @donpinkus, where did you see that TopN doesn't require aggregations and postAggregations? I can't find it.

**Comment by donpinkus** [comment]
@jihoonson - what TopN docs are you looking at?

If you go to the main [TopN doc page](http://druid.io/docs/latest/querying/topnquery.html), and look at the required properties for the query, it has "aggregations" and "postAggregations" marked as "no".

Btw if you end up making a change, include me on the PR! Would love to see how to update the docs code.

**Comment by jihoonson** [comment]
Ah yeah, actually it is partially correct. The requirement of aggregations depends on the [metric type](http://druid.io/docs/latest/querying/topnmetricspec.html). ```Numeric TopNMetricSpec``` requires to specify aggregators. 
Raised https://github.com/druid-io/druid/pull/5240.
