### ISSUE TITLE
Create new data sources with another specs based on existing (historical) data

### ISSUE THREAD

**Issue by kaytrance** [druid-io/druid#5235]
Our cluster takes data from `kafka` and puts them into one data source with 5 minute granularity.

We now want to create couple more data sources that should be based on the same data, but having bigger granularities, like `30m`, `6h` and `1d`.

When it comes to new incoming data we can (at least that's the way we see it) just put our data onto some different `kafka` topics as well and each ingestion specs for each data source we like to have will read from that topic and roll-up data according to specs.

But how can we go through our existing `5m` granularity data so to fill historical periods for introduced data sources?

P.S. same question I have posted in [google groups](https://groups.google.com/forum/#!topic/druid-user/4I9lUreb60k) as well

**Comment by himanshug** [comment]
replied on the mailing list.

**Comment by kaytrance** [comment]
Maybe @himanshug you can help me with [my latest comment](https://groups.google.com/d/msg/druid-user/4I9lUreb60k/JdWIyE1xAAAJ) as well. The thing there is that after `kafka_index` job aggregation metrics are always 0. I cannot figure out why, the syntax seems to be correct.
