### ISSUE TITLE
Typo in configuration/index.md

### ISSUE THREAD

**Issue by dragonls** [druid-io/druid#5249]
1. Missing a backquote after druid.emitter.http.flushTimeOut.
Location: [docs/content/configuration/index.md#L223](https://github.com/druid-io/druid/blob/master/docs/content/configuration/index.md#L223)

2. Typo of `io.druid.server.emitter.HttpEmitterMonitor`, which should be `io.druid.server.emitter.HttpEmittingMonitor` reffering to [`HttpEmittingMonitor`](https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/server/emitter/HttpEmittingMonitor.java)
Location: [docs/content/configuration/index.md#L199](https://github.com/druid-io/druid/blob/master/docs/content/configuration/index.md#L199)

**Comment by jihoonson** [comment]
Fixed in #5250.
