### ISSUE TITLE
Hadoop reindex job produces metrics equal to 0

### ISSUE THREAD

**Issue by kaytrance** [druid-io/druid#5277]
Maybe a bug or some things are not clear in documentation.

I have a hadoop reindex task to create new data source from existing one:
```
{
   "type": "index_hadoop",
   "spec": {
      "dataSchema": {
         "dataSource": "reindex-1h",
         "parser": {
            "type": "hadoopyString",
            "parseSpec": {
               "format": "json",
               "timestampSpec": {
                  "column": "__time",
                  "format": "auto"
               },
               "dimensionsSpec": {
                  "dimensions"          : ["aaa", "bbb", "ccc", "ddd", "eee"],
                  "dimensionExclusions" : ["xxx", "yyy"],
                  "spatialDimensions"   : []
               }
            }
         },
         "metricsSpec": [
            { "name": "just_count",  "type": "count" },
            { "name": "event_qty",   "type": "longSum",   "fieldName": "count" },
            { "name": "sum_value",   "type": "longSum",   "fieldName": "val"},
            { "name": "min_value",   "type": "longMin",   "fieldName": "val"},
            { "name": "max_value",   "type": "longMax",   "fieldName": "val"}
         ],
         "granularitySpec": {
            "type"               : "uniform",
            "segmentGranularity" : {"type": "duration", "duration": 21600000},
            "queryGranularity"   : "hour",
            "rollup"             : true,
            "intervals"          : ["2017-12-05T00:00:00.000/2017-12-05T02:00:00.000"]
         }
      },
      "ioConfig": {
         "type": "hadoop",
         "inputSpec": {
            "type": "dataSource",
            "ingestionSpec": {
               "dataSource" : "old_datasource",
               "intervals"  : ["2017-12-05T00:00:00.000/2017-12-05T02:00:00.000"],
               "metrics"    : ["count","val"]
            }
         }
      },
      "tuningConfig": {
         "type"                        : "hadoop",
         "maxRowsInMemory"             : 500000,
         "numBackgroundPersistThreads" : 1,
         "jobProperties" : {
            "mapreduce.job.classloader": "true",

            "mapreduce.map.memory.mb": 3069,
            "mapreduce.map.java.opts": "-server -Xmx2g -Duser.timezone=UTC -Dfile.encoding=UTF-8",
            "mapreduce.reduce.memory.mb": 8096,
            "mapreduce.reduce.java.opts":"-server -Xmx4g -Duser.timezone=UTC -Dfile.encoding=UTF-8",
      
            "mapreduce.job.reduces": 21,
            "mapreduce.job.jvm.numtasks": 20,
            "mapreduce.reduce.shuffle.parallelcopies": 50,
            "mapreduce.reduce.shuffle.input.buffer.percent": 0.5,
            "mapreduce.task.io.sort.mb" : 500
         }
      }
   }
}
```
Original `old_datasource` datasource have 5 minute granularity, dimensions `xxx` and `yyy` are unique to `5m` granularity so they must be excluded when making `reindex-1h` data source (which I did in `dimensionExclusions`).

Task log shows no errors and task completes after about 30 minutes with `SUCCESS` status. But for some unknown reason in `reindex-1h` data source all metrics are equal to 0. What is more strange that even `just_count` metric is also equal to 0, but at least this one should become greater than zero since it's just a counter.

Here are some rows from `old_datasource` to confirm that metrics are non-zero values and I have specified dimensions correctly:
```
{
   "__time" : 1512432900000,
   "aaa"    : "aaa-value",
   "bbb"    : "bbb-value",
   "ccc"    : "ccc-value",
   "ddd"    : "ddd-value",
   "eee"    : null,
   "xxx"    : "1512432900",
   "yyy"    : "Counter",
   "val"    : 4681652,
   "count"  : 1
},
{
   "__time" : 1512433500000,
   "aaa"    : "aaa-value",
   "bbb"    : "bbb-value",
   "ccc"    : "ccc-value",
   "ddd"    : "ddd-value",
   "eee"    : null,
   "xxx"    : "1512433500",
   "yyy"    : "Counter",
   "val"    : 657321,
   "count"  : 1
}
```

And here are the same dimensions from the same time period, but from `reindex-1h` data source:
```
{
   "__time": 1512432000000,
   "aaa"    : "aaa-value",
   "bbb"    : "bbb-value",
   "ccc"    : "ccc-value",
   "ddd"    : "ddd-value",
   "eee"    : null,
   "just_count": 0,
   "min_value": 0,
   "event_qty": 0,
   "sum_value": 0,
   "max_value": 0
}
```

Task definition seems to be 100% according to documentation. Any clues why this happens and how to solve this?

**Comment by nishantmonu51** [comment]
havn't looked into it or reproduced myself,
It looks like a bug indeed from the description. 

Can you also try adding your metrics to the dimension list in the ingestion spec as below -  

```
"ingestionSpec": {
               "dataSource" : "old_datasource",
               "intervals"  : ["2017-12-05T00:00:00.000/2017-12-05T02:00:00.000"],
               "dimensions"    : ["aaa", "bbb", "ccc", "ddd", "eee","count","val"]
            }
```

**Comment by himanshug** [comment]
@kaytrance can you try to use the same "metricSpec" as is used by original ingestion spec and see if that produces sensible metrics.

reindexing code is expected to work with exact same metricSpec that is used for original ingestion to support the "delta ingestion" use case.

we'll update the docs if that fixes the issue for you and indeed the cause here.

**Comment by kaytrance** [comment]
hmmm.. we kind of want to reindex data so that new data source could have another granularity, and in the same time it should have couple more aggregation metrics, like min and max. So, do I understand correctly that it is not possible to make a new data source if you want to have more aggregation metrics in that new data source?

**Comment by himanshug** [comment]
yes, that is a limit ... for now, you can't change the metric spec.

reason for that limit is related to "delta ingestion" support where user could be reading partially from Druid segments and partially late arriving data on hdfs. In that case, same set of aggregators must be used to read and process both datasets.
unfortunately, this restriction isn't really necessary for pure re-indexing use case but sneaking in from above use case.

https://github.com/druid-io/druid/blob/master/indexing-hadoop/src/main/java/io/druid/indexer/IndexGeneratorJob.java#L301 is the relvant code piece. we can probably add a hack config to forcefully not use combiningAggs even with SegmentInputRow and user could enable same for re-indexing only use cases. Unfortunately there is no clean-n-simple way to auto detect reindexing vs delta-ingestion.

**Comment by kaytrance** [comment]
maybe we can add come kind of flag somewhere (probably in `ingestionSpec`) so to state to ignore original specs?

I can see that this usecase could be pretty common in case you want to introduce new dataset (with higher granularity probably) and with some different metrics, but based on ones that are already in the datasource.

My usecase can be as example. We store realtime metrics, each having 5 dimensions. We poll them every 5 minutes and store values of that metrics in druid (with `queryGranularity` = 5 minutes), ending up with 25Gb of data per day. Then someone come in and say that "I want to be able to look at metrics for one month". Well the problem in that case is that druid have to look via 30days*25Gb=750Gb of data to get about 200 points to fit them into graph.

Then we realized that for that kind of tasks we better create a new data source with `queryGranularity` like 1 hour, but we better have some extra metrics along side, like minimum and maximum value during hour. So we decided to re-index all our existing data to create an new data source called `reindex-1h`, for example. Re-indexing task seems to be the solution.

But it seems that we cannot achieve that via re-indexing because each time our metrics, both new and existing one, are 0 in result :(

Yesterday I manage to get at least `count` metric to be non-zero, but `val` is always 0. I cannot use the same specs as in primary data source since in primary data source we have `val` metric defined as

```
{"type": "longSum", "name": "val", "fieldName": "value" }
```

because we have `value` field coming from kafka, and we store them as `val` in druid.

So I tried this as `metricsSpec` 

```
{ "name": "count",  "type": "count" },
{ "name": "val",    "type": "longSum",   "fieldName":"val" }
```

or 

```
{ "name": "count",  "type": "count" },
{ "name": "value",    "type": "longSum",   "fieldName":"val" }
```

and it gave `count` metric > 0 but `val` was still zeroes all the time.

So unfortunately it seems that we cannot re-index old data so that it could have couple more metrics :(

**Comment by himanshug** [comment]
My understanding is, that in KafkaIndexingService, your metric spec was...
```
{ "name": "count",  "type": "count" },
{ "name": "val",    "type": "longSum",   "fieldName":"value" }
```
using same in reindex task is totally expected to work and I can confirm that we regularly use that in many of our own reindexing jobs. What version of Druid are you using?

Now, on the topic of being able to change metricSpec for reindexing jobs, I think it does make sense to have a config enabling that use case. Quick Patch in #5294 provides a boolean flag "readDruidRowsWithAggs" in "ioConfig" section to enable using arbitrary aggregators while reindexing. ( I'll probably need to change the flag name to something else more intuitive , but thatz for later).
Is it possible for you to apply the patch to Druid version you're using and run with that?

**Comment by kaytrance** [comment]
Thanks @himanshug! 

So if I specify exact same `metricSpecs` that was in original data source (even if it does not makes sense since `value` field existed in kafka, and in druid it's `val`, so referring to `value` field seems illogical, but nwm) or do not specify anything there at all I will get aggregations working.

When it comes to patch we will evaluate it at some day, because now we are forced to forget about historical data and make a new ingestion spec with different granularity. I would love to see this patch integrated into upcoming `v.0.12`.

I will close this case for now.
