### ISSUE TITLE
SQL filtering with "__Time =" does not work in Pivot

### ISSUE THREAD

**Issue by millbraeming** [druid-io/druid#5337]
SQL filtering with "__Time =" returns error, while "__Time <" or "__Time >" work correctly.  Please find attached screen shots. 

**Case where __Time filter works :** 
<img width="1260" alt="screen shot 2018-02-02 at 1 59 36 pm" src="https://user-images.githubusercontent.com/9752231/35757671-1b5c611a-0825-11e8-95f4-b344de631085.png">

**Case where __Time filter does not work**
<img width="1180" alt="screen shot 2018-02-02 at 2 19 28 pm" src="https://user-images.githubusercontent.com/9752231/35757721-4c41e62e-0825-11e8-9527-9d0f2f822201.png">
<img width="1269" alt="screen shot 2018-02-02 at 2 19 58 pm" src="https://user-images.githubusercontent.com/9752231/35757722-4c58864a-0825-11e8-8f10-6d642d4aebf6.png">

**Comment by jihoonson** [comment]
@millbraeming thank you for reporting, but it looks not a bug to me. The reason that the last query returns an empty result is that there is no row having `2016-06-27T00:00:36.000Z` value for `__time` column. I guess it should be `2016-06-27T00:00:36.027Z` if you want to get the second row. Would you try again?

**Comment by jihoonson** [comment]
Ok. This is a feature request rather than a bug. It looks good to me to support it.

**Comment by gianm** [comment]
Check this out:

`__time = TIMESTAMP '2017-11-20 19:07:26.561'` plans to intervals `"2017-11-20T19:07:26.000Z/2017-11-20T19:07:26.001Z"`

but `__time >= TIMESTAMP '2017-11-20 19:07:26.561'` plans to `"2017-11-20T19:07:26.561Z/146140482-04-24T15:36:27.903Z"`

So, there is at least a bug here somewhere.

The exception applying `DruidQueryRule:WHERE_FILTER` also is a bug, rules shouldn't fail outright like that.

**Comment by jihoonson** [comment]
@gianm thanks for clarifying this issue. I didn't know that the Calcite timestamp type supports millisecond fraction. Good to know.
