### ISSUE TITLE
Turn ObjectColumnSelector into an abstract class. 

### ISSUE THREAD

**Issue by nishantmonu51** [druid-io/druid#5346]
This task is to see if ObjectColumnSelector could be turned into abstract class from interface, and isNull method is made final. Follow up comment from https://github.com/druid-io/druid/pull/5278#discussion_r166013339

**Comment by leventov** [comment]
It's a very small thing (goal was just to make one method `final`), I thought it could be a part of that PR, otherwise doesn't worth a separate issue IMO.

**Comment by leventov** [comment]
I just checked and can say - it could be turned into an abstract class.
