### ISSUE TITLE
[Proposal] Support Map in orc-extensions

### ISSUE THREAD

**Issue by visualskyrim** [druid-io/druid#5362]
I saw `orc-extensions` [support List](https://github.com/druid-io/druid/blob/master/extensions-contrib/orc-extensions/src/main/java/io/druid/data/input/orc/OrcHadoopInputRowParser.java#L95).

I wonder if we can make it also support `Map`.

**Comment by dansuzuki** [comment]
I would like to take on this with the following handling.

Explode map-type field into several fields having its name prefixed with parent fieldname + underscore. E.g.

From this...
```
  "a_map_type_field" : {
    "key1" : "value1",
    "key2" : "value2",
    .
    .
    .
    "keyN": "valueN"
```

To this...
```
  "a_map_type_field_key1" : "value1",
  "a_map_type_field_key2" : "value2",
  .
  .
  .
  "a_map_type_field_keyN" : "valueN"
```

**Comment by visualskyrim** [comment]
Thanks a lot for making those changes!
