### ISSUE TITLE
mysql connector should (probably) allow utf8mb4 as character set

### ISSUE THREAD

**Issue by hoesler** [druid-io/druid#5377]
I tried to set up druid with mysql as metadata storage. It has utf8mb4 as default character set, which currently seems to be the [recommended best practice](https://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci). Druid rejected it with "Database default character set is not UTF-8." [here](https://github.com/druid-io/druid/blob/0105cdbc19828009d21de57a30ba55794a518d30/extensions-core/mysql-metadata-storage/src/main/java/io/druid/metadata/storage/mysql/MySQLConnector.java#L167).
I guess, without further testing, that this is too restrictive and druid should allow utf8mb4.

**Comment by drcrallen** [comment]
hmmm

https://github.com/druid-io/druid/blob/druid-0.11.0/extensions-core/mysql-metadata-storage/src/main/java/io/druid/metadata/storage/mysql/MySQLConnector.java#L98-L108 is where the check is enforced. Do you have any good suggestions on how to make sure the DB is configured sanely?

Also, if it does need to change to not just utf8, then https://github.com/druid-io/druid/blob/druid-0.11.0/docs/content/development/extensions-core/mysql.md will need updated as well

**Comment by gianm** [comment]
It sounds like utf8mb4 is the right thing to do these days. @hoesler would you mind doing a PR to loosen up the check in Druid?

**Comment by hoesler** [comment]
Okay, I'll take a look.
