### ISSUE TITLE
DefaultLimitSpec doesn't respect sortByDimsFirst

### ISSUE THREAD

**Issue by jihoonson** [druid-io/druid#5378]
The timestamp is always compared first in the ordering created by DefaultLimitSpec (https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/query/groupby/orderby/DefaultLimitSpec.java#L201-L253). This breaks the behavior `sortByDimsFirst`.

I'm fixing this bug, and wonder what is the correct behavior of `sortByDimsFirst`. If some metrics are specified as well as dimensions for ordering in limitSpec, should they be compared before comparing timestamp? or only dimensions should be compared before timestamp?

IMO, it looks to make sense to compare metrics as well as dimensions before timestamp if `sortByDimsFirst` is set to true, because `sortByDimsFirst` option is introduced to avoid sorting in each time bucket and thus get the result sorted by columns.

@himanshug what do you think?

**Comment by himanshug** [comment]
> IMO, it looks to make sense to compare metrics as well as dimensions before timestamp if sortByDimsFirst is set to true, because sortByDimsFirst option is introduced to avoid sorting in each time bucket and thus get the result sorted by columns.

@jihoonson yes I agree.
