### ISSUE TITLE
SQL: Selecting column names that are keywords always needs to be escaped

### ISSUE THREAD

**Issue by hetul** [druid-io/druid#5389]
I have a datasource with a dimension called `year`, which becomes a `VARCHAR` column name in the SQL schema.

The following SELECT statement fails:
```
SELECT year FROM mydatasource LIMIT 1
```

This results in a `org.apache.calcite.sql.parser.SqlParseException`.

The workaround is to escape all column names in Druid SQL queries like so:
```
SELECT "year" FROM mydatasource LIMIT 1
```

But other flavors of SQL that I've worked with do not share this problem (i.e. MySQL, Postgres tend to recognize that `year` is a column name based on the surrounding syntax).

The same issue also occurs with other columns that are keywords, such as `count` which appears on all Druid SQL schemas.

**Comment by gianm** [comment]
Hi @hetul, as far as I know we inherit this behavior from Calcite (which we use for SQL parsing & planning). I don't know if it's customizable. If it is, I'd definitely merge a PR that changed the behavior to be less finicky. Otherwise I think we should close this wontfix.

Do you (or anyone else listening) happen to know?

**Comment by hetul** [comment]
Thanks @gianm, it does sound like a Calcite issue. I don't have experience with Calcite, so I don't know if it's configurable.

Totally fair to close as wontfix since the workaround is simple enough, though mildly surprising. I just wanted to point it out if it was an unknown issue!

**Comment by gianm** [comment]
Hmm, I checked the Calcite SQL parser config briefly and don't see an obvious way to change this. So I'll close this. Hope it's not too bad of an inconvenience!

**Comment by UIPath-Harshit** [comment]
@gianm landed into this issue as we are building something similar for our use case in UIPath. Could you help us understand what workaround druid or customers did for this?
