### ISSUE TITLE
Segment filtering should be done by looking at the inner most query of a nested query

### ISSUE THREAD

**Issue by samarthjain** [druid-io/druid#5493]

**Comment by samarthjain** [comment]
[5493.txt](https://github.com/druid-io/druid/files/1813764/5493.txt)

Patch file with fix and test case attached.

**Comment by samarthjain** [comment]
@jihoonson, @gianm  - as part of working on https://github.com/druid-io/druid/pull/5471/, I discovered this issue with nested queries. When you get a chance, can you please take a look? Thanks!

**Comment by jihoonson** [comment]
@samarthjain is the attached patch is for #5471? If so, you can simply push more commits to your repository. It will be reflected automatically to your PR.

**Comment by samarthjain** [comment]
@jihoonson, the patch is not related to 5471. It looks like a bug in general.

**Comment by jihoonson** [comment]
@samarthjain oh nice! Then, would you make another PR for this issue? It would be much better to review your work.

**Comment by samarthjain** [comment]
Created https://github.com/druid-io/druid/pull/5496

**Comment by jihoonson** [comment]
Close via #5496.
