### ISSUE TITLE
coordinator web console not work 

### ISSUE THREAD

**Issue by terry19850829** [druid-io/druid#5574]
The cordinator web console error msg is :

druid.js:125 GET http://COORDINATOR_HOST:PORT/coordinator/false 404 (Not Found)
druid.js:125 GET http://COORDINATOR_HOST:PORT/overlord/false 404 (Not Found)

And the whole page can't not load completely.

Any ideas ?
my druid verison is druid-0.11.0.

**Comment by magor** [comment]
hey @terry19850829 , I stumbled upon the same problem, how did you deal with it?

**Comment by terry19850829** [comment]
@magor the problem occured when there is zero datasource. When the indexing service add one, the problem disappear.
