### ISSUE TITLE
Kafka Indexing Service creates segments with `rollup` set to `null`

### ISSUE THREAD

**Issue by pdeva** [druid-io/druid#5620]
this is reference #5611 

even though the task is seemingly run with `rollup: true`, the generated segment has `rollup: null` in metadata.

example:

```
2018-04-09 14:28:16,476 INFO i.d.i.w.e.ExecutorLifecycle [main] Running with task: {
  "type" : "index_kafka",
  "id" : "index_kafka_pctile-hour_00e3999bb72c9c8_oakmcogn",
  "resource" : {
    "availabilityGroup" : "index_kafka_pctile-hour_00e3999bb72c9c8",
    "requiredCapacity" : 1
  },
  "dataSchema" : {
    "dataSource" : "pctile-hour",
    "parser" : {
      "type" : "string",
      "parseSpec" : {
        "format" : "json",
        "timestampSpec" : {
          "column" : "timestamp",
          "format" : "auto"
        },
        "dimensionsSpec" : {
          "dimensions" : [ "accountid", "appid", "jvmid", "metrictype", "name" ]
        }
      }
    },
    "metricsSpec" : [ {
      "type" : "count",
      "name" : "count"
    }, {
      "type" : "quantilesDoublesSketch",
      "name" : "value",
      "fieldName" : "value",
      "k" : 512
    } ],
    "granularitySpec" : {
      "type" : "uniform",
      "segmentGranularity" : "DAY",
      "queryGranularity" : "HOUR",
      "rollup" : true,
      "intervals" : null
    },
    "transformSpec" : {
      "filter" : null,
      "transforms" : [ ]
    }
  },
  "tuningConfig" : {
    "type" : "KafkaTuningConfig",
    "maxRowsInMemory" : 75000,
    "maxRowsPerSegment" : 5000000,
    "intermediatePersistPeriod" : "PT10M",
    "basePersistDirectory" : "/tmp/1522938445282-0",
    "maxPendingPersists" : 0,
    "indexSpec" : {
      "bitmap" : {
        "type" : "concise"
      },
      "dimensionCompression" : "lz4",
      "metricCompression" : "lz4",
      "longEncoding" : "longs"
    },
    "buildV9Directly" : true,
    "reportParseExceptions" : false,
    "handoffConditionTimeout" : 0,
    "resetOffsetAutomatically" : false,
    "segmentWriteOutMediumFactory" : null
  },
  "ioConfig" : {
    "type" : "kafka",
    "baseSequenceName" : "index_kafka_pctile-hour_00e3999bb72c9c8",
    "startPartitions" : {
      "topic" : "dupercentile",
      "partitionOffsetMap" : {
        "0" : 1215429707
      }
    },
    "endPartitions" : {
      "topic" : "dupercentile",
      "partitionOffsetMap" : {
        "0" : 9223372036854775807
      }
    },
    "consumerProperties" : {
      "bootstrap.servers" : "xx"
    },
    "useTransaction" : true,
    "pauseAfterRead" : false,
    "minimumMessageTime" : null,
    "maximumMessageTime" : null,
    "skipOffsetGaps" : false
  },
  "context" : {
    "checkpoints" : "{\"0\":{\"0\":1215429707}}",
    "IS_INCREMENTAL_HANDOFF_SUPPORTED" : true
  },
  "groupId" : "index_kafka_pctile-hour",
  "dataSource" : "pctile-hour"
}
```

**Comment by pdeva** [comment]
@gianm can this be added to 0.12.1 milestone please

**Comment by gianm** [comment]
@pdeva I would say sure if there is a patch available, but I don't want to hold up 0.12.1 for this if we have not yet investigated the cause and written a patch.

**Comment by pdeva** [comment]
@gianm is there someone i can tag for this issue. i do believe this deserves some priority as it seems to invalidate segments produced by Kafka indexing task.
i dont know enough about the druid internals in this area to find the root cause but am willing to cooperate to the extent possible as far as providing any relevant info is concerned

**Comment by pdeva** [comment]
ok specifying `"analysisTypes": ["rollup"]` in segment metadata query it seems the other segments do have `rollup: true`, so this may be a non-issue so far. i will wait for a few days and let more segments generate. if the issue doesnt resurface, i will close it

**Comment by pdeva** [comment]
i can confirm that new segments have rollup set to true. closing this for now. will reopen if this reemerges

**Comment by suhassumukhv** [comment]
@pdeva @gianm Happens on `0.12.0` as well. `rollup` always returns `null` and `size` always returns `0`. After explicitly using `"analysisTypes": ["rollup", "size"]`, do I get them right.

**Comment by gianm** [comment]
Hi @suhassumukhv, this sounds like it's working as it's supposed to. Rollup isn't included in segmentMetadata analysis by default, but it will be if you include the "rollup" analysisType.

**Comment by suhassumukhv** [comment]
@gianm True thing. But if it isn't included by default, it shouldn't display in the result either. So should it be for `size` and other analysis types. This kind of functionality is very confusing.

**Comment by jihoonson** [comment]
@suhassumukhv that sounds good to me. Are you interested in making a patch for this?
