### ISSUE TITLE
mem-leak in historical 0.12

### ISSUE THREAD

**Issue by sixtus** [druid-io/druid#5629]
it's been haunting me since the 0.12 deploy, because it's very slow to grow. It looks triggered by new segments. Just my preliminary findings.

I just restarted the cluster with druid.query.groupBy.numParallelCombineThreads=1 and I can finally seen GC in mem usage again.

**Comment by gianm** [comment]
Can you tell what kinds of objects are being retained that shouldn't be? Maybe from looking through a heap histogram on an idle node for things that "shouldn't" be there.

**Comment by gianm** [comment]
Can you tell if you had any exceptions that occurred in the `ParallelCombine.combine` method (or callees of it)? It looks like there is a resource leak that occurs if that happens.

**Comment by gianm** [comment]
#5630 fixes that particular leak. I'm not sure if it's the one you saw or not.

**Comment by sixtus** [comment]
one of the nodes just doubled the ram usage after setting it to 1.

Apr 11 23:10:00 alexandria2 druid-historical[22230]: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Cancelled
Apr 11 23:10:00 alexandria2 druid-historical[22230]:         at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:177) ~[druid-services-0.12.0-selfcontained.jar:0.12.0]

within 20min the ram usage doubled afterwards.

**Comment by sixtus** [comment]
I guess I have to update the ticket. Setting parallelCombiner to one did not solve the mem leak. More when I know more.

**Comment by gianm** [comment]
@sixtus It might be helpful to analyze a heap dump from a time when the historicals are misbehaving?

**Comment by sixtus** [comment]
status update: we need to restart our historicals every ~12h atm. Heap dumps point at http://www.evanjones.ca/java-bytebuffer-leak.html - we testing the change on one server, looks very promising.

**Comment by gianm** [comment]
@sixtus Do you mean you added `-Djdk.nio.maxCachedBufferSize=262144`?

What JVM brand / version are you running?

**Comment by sixtus** [comment]
it looks like it was just the cruft of 6 years old recipes. It went away after tuning jvm and druid options.
