### ISSUE TITLE
Kafka Indexing Service task pause forever until timeout if no events in taskduration?

### ISSUE THREAD

**Issue by Oooocean** [druid-io/druid#5656]
We wanna use kafka indexing serivce for streaming events. But I  encounter some problem even in very simple case.
1. Install druid on one machine. (use imply-2.5.8.tar.gz)
2. Install kafka on same machine.
3. create topic, and submit a spec:
{
  "type": "kafka",
  "dataSchema": {
    "dataSource": "metrics-ocean4",
    "parser": {
      "type": "string",
      "parseSpec": {
        "format": "json",
        "timestampSpec": {
          "column": "timestamp",
          "format": "auto"
        },
        "dimensionsSpec": {
          "dimensions": [],
          "dimensionExclusions": [
            "timestamp",
            "value"
          ]
        }
      }
    },
    "metricsSpec": [
      {
        "name": "count",
        "type": "count"
      },
      {
        "name": "value_sum",
        "fieldName": "value",
        "type": "doubleSum"
      },
      {
        "name": "value_min",
        "fieldName": "value",
        "type": "doubleMin"
      },
      {
        "name": "value_max",
        "fieldName": "value",
        "type": "doubleMax"
      }
    ],
    "granularitySpec": {
      "type": "uniform",
      "segmentGranularity": "MINUTE",
      "queryGranularity": "NONE"
    }
  },
  "tuningConfig": {
    "type": "kafka",
    "maxRowsPerSegment": 5000000,
    "intermediatePersistPeriod": "PT5M",
    "basePersistDirectory": "/home/qspace/data/mmgamedruiddata/tmp"
  },
  "ioConfig": {
    "topic": "oceantopic4",
    "consumerProperties": {
      "bootstrap.servers": "10.242.20.145:9092"
    },
    "taskCount": 1,
    "replicas": 1,
    "taskDuration": "PT10M",
    "completionTimeout": "PT10M"
  }
}
Note that I set task duration to 10M, because I wanna hava a quick test. But my tasks mostly failed in publishing status.

![image](https://user-images.githubusercontent.com/13477599/38879963-2123cb68-4297-11e8-954c-cef2491781bc.png)
Failed task log seems that stop at 
"2018-04-17T11:25:33,184 INFO [task-runner-0-priority-0] io.druid.indexing.kafka.KafkaIndexTask - Pausing ingestion until resumed" and never resume.

I set process overlord log to debug. When index task(middleMgr) paused, overload will send offset/end to index task to publish segments.
If there aren't any envets, offsets would not changed. So overload will not send "offset/end" any more? 
If index task(middleMgr) cannot receive resume, it will pause forever until taskCompleteTimeout.
Am i miss something? Could anyone help. Thx advance!
 
SUCC index task overlord: ![ok_overlord](https://user-images.githubusercontent.com/13477599/38880203-b55934ee-4297-11e8-8241-76fa0cb79965.png)
FAIL index task overload log: 
![fail_overlord](https://user-images.githubusercontent.com/13477599/38880268-e074215c-4297-11e8-8112-7701ce8d2649.png)

**Comment by jon-wei** [comment]
This issue was also reported here: https://github.com/druid-io/druid/issues/5666

This thread on the druid-user mailing list also seems to describe the same or a similar issue:
- https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/druid-user/3v38kko5bss/x4vze-RlBwAJ (In the attached log, the KafkaIndexTask also ends with the line `2018-04-13T17:58:17,790 INFO [task-runner-0-priority-0] io.druid.indexing.kafka.KafkaIndexTask - Pausing ingestion until resumed`, but this task seems to have ingested some data)

**Comment by teeram** [comment]
Hey guys, wanted to mention that I am also having this problem ever since I upgraded to 0.12.0.  This didn't seem to be a problem in 0.11.0.

**Comment by gianm** [comment]
I believe this is fixed by #5899 and #5902. If anyone notices this issue reoccurring after having deployed a build with both of those two, please let us know.

**Comment by helianthuslulu** [comment]
Hi,team. I  met this problem now. I used community version：V 0.12.3  .
I proceed as follows:
0)nohup bin/kafka-server-start.sh config/server.properties &
```
1)cd $KAFKA_HOME && 
./bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test-wiki
```
```
2)cd $DRUID_HOME &&
curl -X POST -H'Content-Type:application/json' -d@quickstart/tutorial/wikipedia-kafka-supervisor.json http://101.8.101.20:8090/druid/indexer/v1/supervisor
```
```
3)cd $KAFKA_HOME && 
./bin/kafka-console-producer.sh --broker-list localhost:9092 --topic wikipedia_sample < /opt/druid/quickstart/tutorial/wikipedia-kafka-supervisor.json
```
but, task log shows 
"2019-01-08T16:03:59,535 INFO [task-runner-0-priority-0] **io.druid.indexing.kafka.KafkaIndexTask - Pausing ingestion until resumed**"
and endly
"2019-01-08T16:03:59,599 INFO [publish-0] io.druid.segment.realtime.appenderator.BaseAppenderatorDriver - **Nothing to publish, skipping publish step**."

 Am i miss something? Could anyone help. I VERY MUCH appreciate all replies.

**Comment by helianthuslulu** [comment]
The same data.json and spec.json were tested in imply version successfully.  I  found that Discover the differences by analyzing the imply task log and druid-0.12.3 task log. I will ask around and see if anyone can help.  Thanks.
