### ISSUE TITLE
Should Aggregator, BufferAggregator and PostAggregator implement equals() and hashCode()?

### ISSUE THREAD

**Issue by leventov** [druid-io/druid#5669]
I couldn't find any cases when `equals()` or `hashCode()` is called on `Aggregator`, `BufferAggregator` or `PostAggregator` (except in `PostAggregatorFactory`, which is unused - FYI @gianm).

Could we ditch the complexity of implementing those methods in dozens of implementations of those interfaces altogether?

@gianm @himanshug @jon-wei @jihoonson

**Comment by gianm** [comment]
I think PostAggregator should have equals/hashCode methods. One is that they're specified directly in queries, and are used to check if two queries are equal or not (like TimeseriesQuery.equals for example). I'm not sure if this capability is needed in production code, but it is useful enough for tests that I think it makes sense to keep it. And I am not confident that it is _not_ important in production code.

Aggregator and BufferAggregator are different. They are more transient objects that are not meant to be serialized or compared to other objects. So I don't think they need equals or hashCode.

**Comment by leventov** [comment]
Looks like Aggregator and BufferAggregator impls never actually override equals() and hashCode(), so they are ok.
