### ISSUE TITLE
[help] How to use Nested groupBys ?

### ISSUE THREAD

**Issue by lianglingbo** [druid-io/druid#5685]
SQL:
select sum(maxdata) from
(SELECT "deviceId",max("data") as maxdata FROM "dataTest2"
group by "deviceId")
percentage

I don't known how can I parse the SQL to JSON
thanks!

**Comment by jihoonson** [comment]
Hi, Druid supports [SQL](http://druid.io/docs/latest/querying/sql.html). You can try it.
