### ISSUE TITLE
Using druid.storage.type=noop get error

### ISSUE THREAD

**Issue by davidkeeper** [druid-io/druid#5687]
when I try to use deep storage  = noop (not storage segments, only segments-cache), then I get an error below:

1) Unknown provider[noop] of Key[type=io.druid.segment.loading.DataSegmentPusher, annotation=[none]], known options[[hdfs, s3, local]]
  at io.druid.guice.PolyBind.createChoice(PolyBind.java:70) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.LocalDataStorageDruidModule)
  while locating io.druid.segment.loading.DataSegmentPusher
    for the 4th parameter of io.druid.indexing.common.TaskToolboxFactory.<init>(TaskToolboxFactory.java:108)
  at io.druid.cli.CliPeon$1.configure(CliPeon.java:165) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliPeon$1)
  while locating io.druid.indexing.common.TaskToolboxFactory
    for the 1st parameter of io.druid.indexing.overlord.ThreadPoolTaskRunner.<init>(ThreadPoolTaskRunner.java:100)
  at io.druid.cli.CliPeon$1.configure(CliPeon.java:192) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliPeon$1)
  while locating io.druid.indexing.overlord.ThreadPoolTaskRunner
  while locating io.druid.indexing.overlord.TaskRunner
    for the 4th parameter of io.druid.indexing.worker.executor.ExecutorLifecycle.<init>(ExecutorLifecycle.java:78)
  at io.druid.cli.CliPeon$1.configure(CliPeon.java:182) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliPeon$1)
  while locating io.druid.indexing.worker.executor.ExecutorLifecycle

**Comment by lianglingbo** [comment]
check your address

**Comment by davidkeeper** [comment]
@lianglingbo sorry I can't understand what's your meaning, all config points a localhost  address in a single node machine.

**Comment by gianm** [comment]
Hi @davidkeeper - you may have a misunderstanding of how Druid works. Deep storage is required and must be configured to _something_. If you have a single node deployment then `local` should work. Otherwise it should point to some sort of shared storage.

I am going to close this but feel free to check our docs (http://druid.io/docs/latest/tutorials/cluster.html) or write in to the user list (http://druid.io/community/) if you have some more questions about how to get Druid up and running.

**Comment by davidkeeper** [comment]
@gianm Thanks for your reply, but still some confuse about noop mode. Here I post the detail question:
https://groups.google.com/forum/#!topic/druid-user/CzNNRK74y2k

**Comment by mrmassis** [comment]
Hi
In my point of view, what happens is that there is a logic problem in "case" inside the druid.sh. To both overload or coordinator take to the same location.
In my opinion, the options should be separated:

original druid.sh
```
getConfPath() {
    cluster_conf_base=/tmp/conf/druid/cluster
    case "$1" in
    _common) echo $cluster_conf_base/_common ;;
    historical) echo $cluster_conf_base/data/historical ;;
    middleManager) echo $cluster_conf_base/data/middleManager ;;
    coordinator | overlord) echo $cluster_conf_base/master/coordinator-overlord ;;
    broker) echo $cluster_conf_base/query/broker ;;
    router) echo $cluster_conf_base/query/router ;;
    esac
}
```

My modification:

```
getConfPath() {
    cluster_conf_base=/tmp/conf/druid/cluster
    case "$1" in
    _common) echo $cluster_conf_base/cluster/_common ;;
    historical) echo $cluster_conf_base/cluste/data/historical ;;
    middleManager) echo $cluster_conf_base/cluster/data/middleManager ;;
    coordinator) echo $cluster_conf_base/cluster/data/coordinator-overlord ;;
    overlord) echo $cluster_conf_base/cluster/master/overlord ;;
    broker) echo $cluster_conf_base/cluster/query/broker ;;
    router) echo $cluster_conf_base/cluster/query/router ;;
    esac
}
```

The entiry druid.sh and start process (logic and code) must be revised. I can do it ;)

Tkz

**Comment by gianm** [comment]
> The entiry druid.sh and start process (logic and code) must be revised. I can do it ;)

Hmm, the idea behind the original druid.sh is that we're shipping with a combined coordinator-overlord config, i.e. `druid.coordinator.asOverlord.enabled = true`. Could you describe what problem that caused and how your change fixes it? Thanks!
