### ISSUE TITLE
not support webflux

### ISSUE THREAD

**Issue by liyunde** [druid-io/druid#5736]
spring boot2
spring5
webflux
Error creating bean with name 'webStatFilterRegistrationBean' defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/stat/DruidWebStatFilterConfiguration.class]

using
spring.datasource.druid.stat-view-servlet.enabled=false
spring.datasource.druid.filter.stat.enabled=false
spring.datasource.druid.filters=

all of this config can not block error
how can i do

**Comment by Dylan1312** [comment]
Hey @liyunde 

Wrong project it just happens to have the same name, you want these guys -> https://github.com/alibaba/druid

**Comment by liyunde** [comment]
sorry,this is my carelessness;thanks
