### ISSUE TITLE
how to DELETE a datasource?

### ISSUE THREAD

**Issue by bainadeashish** [druid-io/druid#5786]
Hi folks,

I am newbie to druid,I followed druid docs to ingest data & it was successful.Now I want to delete the Datasource ,As per documentation I fired DELETE method in postman with below url:

http://XX.XX.XX.XX:8090/druid/coordinator/v1/datasources/my_data  #my_data is my datasource name

XX.XX.XX.XX is IP where my druid is running.
But I can see datasource is still present & up and running.

Please let me know What i am missing here?

Thanks & Regards,
Ashish Bainade

**Comment by bainadeashish** [comment]
Got the solution,i was using wrong port number.
worked with 8081 port.(Coordinator)
Thank you

**Comment by vikashirwani** [comment]
> Hi folks,
> 
> I am newbie to druid,I followed druid docs to ingest data & it was successful.Now I want to delete the Datasource ,As per documentation I fired DELETE method in postman with below url:
> 
> http://XX.XX.XX.XX:8090/druid/coordinator/v1/datasources/my_data #my_data is my datasource name
> 
> XX.XX.XX.XX is IP where my druid is running.
> But I can see datasource is still present & up and running.
> 
> Please let me know What i am missing here?
> 
> Thanks & Regards,
> Ashish Bainad

> Got the solution,i was using wrong port number.
> worked with 8081 port.(Coordinator)
> Thank you

hello,
good day!
I am new to druid.

How you are exactly deleting a datasource?
can you plz tell me the command?
I am getting an error as Unauthorized request. I checked with possibilities to resolve the issue, but I didn't get the proper solution.
