### ISSUE TITLE
Datasources not displayed on coordinator console

### ISSUE THREAD

**Issue by nateMJ** [druid-io/druid#5799]
I am unable to view datasources on the Druid UI. When I check in the old coordination console, I see all the datasources have been disabled which is not the case because I am still able to query them in CLI.

<img width="675" alt="screen shot 2018-05-24 at 15 26 37" src="https://user-images.githubusercontent.com/9557550/40485354-f8cd5304-5f66-11e8-8d5a-8ffa6bb674bb.png">

This is the error displayed in the console:

<img width="1275" alt="screen shot 2018-05-24 at 15 28 21" src="https://user-images.githubusercontent.com/9557550/40485433-2b1d0944-5f67-11e8-9087-37e05ed4a2e5.png">

**Comment by nateMJ** [comment]
I didn't quite figure out the issue but a redeploy of the coordinator node fixed it.

**Comment by andani-09P** [comment]
hi 
have you found any solution
