### ISSUE TITLE
incorrect sql query plan returned

### ISSUE THREAD

**Issue by pdeva** [druid-io/druid#5810]
druid 0.12.0

Query send via the json endpoint

Query:
```
{
	"query": "explain plan for SELECT FLOOR(__time TO HOUR), SUM(\"value\") AS val FROM \"zzz-tablename\" where __time BETWEEN CURRENT_TIMESTAMP AND CURRENT_TIMESTAMP - INTERVAL '20' HOUR group by FLOOR(__time TO HOUR) ORDER BY val DESC limit 500"
}

```

Result

```
[
	{
		"PLAN": "BindableSort(sort0=[$1], dir0=[DESC], fetch=[500])\n  BindableValues(tuples=[[]])\n"
	}
]
```

**Comment by gianm** [comment]
```BETWEEN CURRENT_TIMESTAMP AND CURRENT_TIMESTAMP - INTERVAL '20' HOUR```

should be

```BETWEEN CURRENT_TIMESTAMP - INTERVAL '20' HOUR AND CURRENT_TIMESTAMP```

(the order matters)

In the first case, the query is correctly simplified to a nil resultset.
