### ISSUE TITLE
hadoop rollup not perfect

### ISSUE THREAD

**Issue by Gauravshah** [druid-io/druid#5819]
we are running hadoop batch task on druid 0.10 via emr hadoop 2.7.3
Used the following dimensions to process the data:
verb ,actor.type,actor.guest,actor.gender,actor.ab_segment

Querying the row_count
curl -X POST 'prod-druid-broker-1:8082/druid/v2?pretty' -H 'Content-Type:application/json' -d '{"queryType":"timeseries","dataSource":"raw_events","granularity":"day","descending":"true","aggregations":[{"type":"count","name":"sample_name1"}],"intervals":["2017-05-30T00:00:00.000/2017-06-02T00:00:00.000"]}'
```
[ {
  "timestamp" : "2017-06-01T00:00:00.000Z",
  "result" : {
    "sample_name1" : 32125
  }
} ]

```
But the counts on raw_data is much lower 26806[
```
select count(*) from (
select verb ,actor.type,actor.guest,actor.gender,actor.ab_segment
group by verb ,actor.type,actor.guest,actor.gender,actor.ab_segment
)
```

Discussion from : 

https://groups.google.com/d/msgid/druid-user/50516391-db64-4154-ab91-679922282cf9%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by gianm** [comment]
What do you get if you do the Druid SQL query:

```select * from raw_events where __time >= timestamp '2017-05-30 00:00:00' and __time < timestamp '2017-06-02 00:00:00'```

Do you see two different rows that should have rolled up together?

It's possible that you are missing the time factor (maybe you need to add a time component to your groupby query on raw_data that you're using to verify).

**Comment by Gauravshah** [comment]
we did add the time rolled up to earliest 15th minute within the group by clause. Will take a dump of 32k rows and come back with few examples

**Comment by Gauravshah** [comment]
sorry about it. It does seem that pre-processing the data on my end was blowing it up.
