### ISSUE TITLE
kafka indexing service query slowdown when handoff segments

### ISSUE THREAD

**Issue by terry19850829** [druid-io/druid#5889]
druid version is 0.11.0

We monitor the broker query/time. When the time point for handoff the segments generated by kafka indexing service peons, the query for the data is slowdown. I've ensured that there is no 
long time GC at middlemanager or coordinator and all the metric about historical is low and normal.
So I think maybe the peons have some lock or bottleneck at this peak time point?

![15_59_36__06_19_2018](https://user-images.githubusercontent.com/13132142/41584467-ec0d7496-73d9-11e8-83a9-16dcd146a23e.jpg)

coordinator dynamic config:

```
{
    "millisToWaitBeforeDeleting":900000,
    "mergeBytesLimit":524288000,
    "mergeSegmentsLimit":100,
    "maxSegmentsToMove":20,
    "replicantLifetime":15,
    "replicationThrottleLimit":20,
    "balancerComputeThreads":1,
    "emitBalancingStats":false,
    "killDataSourceWhitelist":[

    ],
    "killAllDataSources":false,
    "maxSegmentsInNodeLoadingQueue":0
}
```

All query is success. But the query at the peak time is quite slow. The peak time is the peons start next ingestion tasks and the coordinator ask peon server load and processing segments.

This phenomenon I think is quite common。 
The coordinator rebalancer processing cause this issue or other reasons? Any ideas?
I really need some help.

**Comment by josephglanville** [comment]
`query/time` only shows time spent after request has been accepted and begun processing on HTTP server thread, if all HTTP server threads are being tied up during handoff this could cause these numbers to look suspiciously small whilst the queries are slow due to blocking on available thread. Most likely `druid.server.http.numThreads` is being reached somewhere. Potentially there is also the max outgoing HTTP connection limit of the broker that should be considered also: `druid.broker.http.numConnections`.

**Comment by terry19850829** [comment]
@josephglanville Thanks a lot! I will increase the two configuration num and try again.

**Comment by terry19850829** [comment]
@josephglanville 
I've config **druid.broker.http.numConnections** refer to http://druid.io/docs/latest/configuration/production-cluster.html.

How the druid thread pool and connections pool configuration should ? Is there a best practice or a startup suggestion?

**Comment by terry19850829** [comment]
I increment **druid.broker.http.numConnections=40** to 120, and the problem resolved.
@josephglanville Thanks!

**Comment by terry19850829** [comment]
It's not a issue, but a capacity planning problem.
