### ISSUE TITLE
Overlord doesnt reassign kafka indexing tasks

### ISSUE THREAD

**Issue by pdeva** [druid-io/druid#5926]
Druid 0.12.1
Druid installation with Overlord+Coordinator (mixed mode) node.

**Steps to reproduce:**

1. Spin up a Middle Manager (MM) node and assign it some kafka indexing tasks.
2. Delete that node
3. Spin up a new MM node

**Expected:**

Overlord will notice the previous MM node no longer exists.
Automatically reassigns the kafka indexing tasks to the new MM node.

**Actual:**

Overlord notices the previous MM node no longer exists.
Keeps trying to ping the old tasks (on the killed MM node) and saying it cant reach them.

Task has to be manually killed from the overlord console (web ui). 
Only once the task is manually killed, it is reassigned by the overlord to the new MM node

**Comment by nishantmonu51** [comment]
After a MM is unreachable, the overlord waits for taskCleanupTimeout before removing the tasks associated with that MM. Default taskCleanupTimeout is 15 mins. 
If you wait for the taskCleanupTimeout and tasks are cleaned up after that from overlord, KIS should be able to spin up new tasks.
