### ISSUE TITLE
groupBy returns different value for each run

### ISSUE THREAD

**Issue by chtn** [druid-io/druid#678]
If a group by query returns aggregated value more than 1 billion, results are not consistent.
e.g. I am running following query on our data set

{
    "aggregations": [
        {
            "fieldName": "metric_1",
            "name": "metric_1",
            "type": "longSum"
        }
    ],
    "dataSource": "dataSource_1",
    "dimensions": [
        "dimension_1"
    ],
    "filter": {
                "type": "or",
                "fields": [
                    {
                        "type": "selector",
                        "dimension": "dimension_2",
                        "value": ""
                    },
                    {
                        "type": "selector",
                        "dimension": "dimension_2",
                        "value": "1"
                    }
                ]
    },
    "granularity": {
        "origin": "2014-07-01T00:00:00",
        "period": "P32D",
        "timeZone": "Etc/GMT",
        "type": "period"
    },
    "intervals": [
        "2014-07-01T00:00:00/2014-07-31T23:59:59"
    ],
    "queryType": "groupBy"
}

When I run it for smaller data range and sum is less than 1 billion, results are consistent. But when sum crosses 1 billion, I see result varies by +/- 25 for every run.
It could be related to https://github.com/metamx/druid/issues/372 where druid returns different result for timeseries and groupby query.

**Comment by fjy** [comment]
I am closing this issue. Please reopen if it has not been resolved in the latest Druid versions.
