### ISSUE TITLE
feature to remove some aggregation from being included in response from broker

### ISSUE THREAD

**Issue by himanshug** [druid-io/druid#688]
Sometimes we add aggregations to a query just because they are needed in a post-aggregation. On getting the response, we completely disregard the those aggregations and only use post-aggregations.

Currently, Is there any way to tell druid broker not to include some aggregations in the response?

Basically, I am looking for a feature where we could specify something at per aggregation basis like following...

  "aggregations": [
    { "type": "longSum", "name": "sample_name1", "fieldName": "sample_fieldName1" , "includeInResponse":"false"},
    { "type": "doubleSum", "name": "sample_name2", "fieldName": "sample_fieldName2" }
  ],

and the aggregation "sample_name1" is not included in the response.

**Comment by fjy** [comment]
Closing this for duplication.

**Comment by reemasaluja** [comment]
Hello Team! 
Could any body confirm if this issue is resolved , and if yes then what is the solution

**Comment by vogievetsky** [comment]
This is effectively solved by DruidSQL where you can select which columns you want back
