### ISSUE TITLE
Documentation about realtime shardSpecs

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#706]
We don't seem to have documentation about shardSpecs, but we should. It should cover:

- What shardSpecs are for (replication, scale-out)
- How to choose which shardSpecs to use

**Comment by swistakm** [comment]
Any plans for updating docs? From what I understand having shardSpecs defined is a must for multiple realtime nodes ingesting same datasource and Druid is for large data streams. I think it should be documented as soon as possible.

**Comment by textractor** [comment]
In fact only the requirement @swistakm mentions is documented (http://druid.io/docs/latest/Realtime-ingestion.html) but not any of the types and when you'd use which. I am working on adding some docs around this.

**Comment by textractor** [comment]
There's a pr for a sharding section for 0.6.x. One for 0.7.x coming up shortly to close this issue.

**Comment by fjy** [comment]
Fixed by #1042
