### ISSUE TITLE
realtime node's memory keep increasing

### ISSUE THREAD

**Issue by zhenchuan** [druid-io/druid#754]
From my understanding, after each segmentGranularity(e.g.1 hour)+windowPeriod , 
the realtime node will hand off the merged segment to Historical Server , so that it's memory usage will not too high, but I found that the usage keep on increasing all the time.

and the JVM option -xmx:20G seems has no effect....

```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                           
32338 lucas.w  16   0 38.1g  27g 8.7g S 21.2 21.7 126:44.04 java 
```

**Comment by fjy** [comment]
I am closing this. Please reopen if this is still an issue.
