### ISSUE TITLE
SearchQueries default limit is 1000.  Seems like default should be to return everything?

### ISSUE THREAD

**Issue by ethanocentricity** [druid-io/druid#762]
https://github.com/metamx/druid/blob/85f739797f43ce708ccfb160af81dd0bac4129e2/processing/src/main/java/io/druid/query/search/search/SearchQuery.java#L68

Other query types don't seem to default the limit.
And since the results are just truncated, it doesn't seem like the limit saves any computation, and it certainly caused us a few minutes of confusion.

**Comment by fjy** [comment]
I am also closing this. Please reopen if it is still a concern for you.
