### ISSUE TITLE
ZK reconnect issues

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#783]
If ZK is brought down and back up, Druid nodes cannot always reconnect. This appears to be a curator PathChildrenCache issue and tracked with:

https://issues.apache.org/jira/browse/CURATOR-153

**Comment by drcrallen** [comment]
@fjy : the AnnouncerTest uses `org.apache.curator.test.KillSession#kill(org.apache.zookeeper.ZooKeeper, java.lang.String)`  to simulate ZK outages. 

Do you think that could help pinpoint this problem?

**Comment by fjy** [comment]
I am closing this for now as no one has reported it to be a problem for quite some time.
